#!/usr/bin/env python

import argparse
import datetime
import numpy as np
import ROOT as r
import shutil

from numpy.lib import recfunctions as rfn

from rootpy.io import root_open
from rootpy.plotting import Hist

from root_numpy import array2tree, list_branches, list_trees, root2array

r.gROOT.SetBatch()
r.gStyle.SetOptStat(0)

parser = argparse.ArgumentParser(description='create likelihood mapping for combining MVAs')
parser.add_argument('--bins', help='how many bins to use', type=int, default=60)
parser.add_argument('infile', help='input filename')
parser.add_argument('outfile', help='output filename')
parser.add_argument('ntuple', help='ntuple to add likelihood to', nargs='?')
args = parser.parse_args()

with root_open(args.infile) as f:
    likelihood = r.TH2F("hist", "Likelihood;BDT score for tt;BDT score for ttZ", args.bins, -1, 1, args.bins, -1, 1)
    f.ttH2Nonbb_125_train_mva.Draw("tmva_tt:tmva_ttZ", hist=likelihood)

    for x in range(likelihood.GetNbinsX()):
        avg = 0.
        n = 0
        for y in range(likelihood.GetNbinsY()):
            bn = likelihood.GetBin(x + 1, y + 1)
            val = likelihood.GetBinContent(bn)
            if val > 0:
                n += 1
                avg += val
        if n == 0:
            continue
        avg /= n
        for y in range(likelihood.GetNbinsY()):
            bn = likelihood.GetBin(x + 1, y + 1)
            val = likelihood.GetBinContent(bn)
            if val > 0:
                val = avg + (val - avg) / 2
                likelihood.SetBinContent(bn, val)

    likelihood.Scale(1. / likelihood.GetMaximum())
    with root_open(args.outfile, "recreate") as of:
        of.WriteObject(likelihood, "likelihood_raw", "WriteDelete")
    c = r.TCanvas()
    likelihood.Draw("COLZ")
    c.SaveAs("likelihood_raw.pdf")

    t = f.ttH2Nonbb_125_train_mva
    values = [likelihood.GetBinContent(likelihood.FindBin(e.tmva_tt, e.tmva_ttZ)) for e in t]

    fractions = np.linspace(0, 100, 5)
    quants = [np.percentile(values, n) for n in fractions]
    quants[-1] += .001
    remap_linear = Hist(quants)
    fractions = [0, 5, 17.5, 37.5, 65, 100]
    quants = [np.percentile(values, n) for n in fractions]
    quants[-1] += .001
    remap = Hist(quants)

    likelihood_linear = likelihood.Clone()
    for x in range(likelihood.GetNbinsX()):
        for y in range(likelihood.GetNbinsY()):
            bn = likelihood.GetBin(x + 1, y + 1)
            likelihood.SetBinContent(bn, remap.FindBin(likelihood.GetBinContent(bn)) - 1)
            likelihood_linear.SetBinContent(bn, remap_linear.FindBin(likelihood_linear.GetBinContent(bn)) - 1)
    with root_open(args.outfile, "update") as of:
        of.WriteObject(likelihood, "likelihood", "WriteDelete")
        of.WriteObject(likelihood_linear, "likelihood_linear", "WriteDelete")
    likelihood.Draw("COLZ")
    c.SaveAs("likelihood.pdf")
    likelihood_linear.Draw("COLZ")
    c.SaveAs("likelihood_linear.pdf")

    trees = "ttH2Nonbb_125 ttZ ttjets_sl_pow ttjets_dl_pow".split()
    hists = []

    for tree in trees:
        t = getattr(f, tree + "_train_mva")
        hist = r.TH2F("remapped_" + tree, "Likelihood;BDT score for tt;BDT score for ttZ", args.bins, -1, 1, args.bins, -1, 1)
        t.Draw("tmva_tt:tmva_ttZ", hist=hist)

        hist.Draw("COLZ")
        c.SaveAs("contribution_{}.pdf".format(tree))
        c.SetLogz()
        c.SaveAs("contribution_{}_log.pdf".format(tree))
        c.SetLogz(False)
        hists.append(hist)

    h = hists[-2]
    h.Add(hists[-1])
    h.Draw("COLZ")
    c.SaveAs("contribution_tt.pdf")
    c.SetLogz()
    c.SaveAs("contribution_tt_log.pdf")
    c.SetLogz(False)

    hists = []
    for t in [getattr(f, t + "_train_mva") for t in trees]:
        mapped = Hist(np.linspace(0, 4, 5), name=t.GetName() + '_hist')
        for e in t:
            mapped.Fill(likelihood.GetBinContent(likelihood.FindBin(e.tmva_tt, e.tmva_ttZ)))
        hists.append(mapped)
    last = hists.pop(-1)
    hists[-1].Add(last)

    for h in hists:
        h.Scale(1. / h.Integral())

    ttH, ttZ, ttjets = hists
    ttH.SetLineColor(r.kRed)
    ttZ.SetLineColor(r.kGreen)
    ttjets.SetLineColor(r.kBlack)
    ttjets.Draw()
    ttZ.Draw("same")
    ttH.Draw("same")
    c.SaveAs("output.pdf")

    likelihood.SetDirectory(0)
    likelihood_linear.SetDirectory(0)

if args.ntuple:
    backup = "{}.{:%Y-%m-%d_%H%M}".format(args.ntuple, datetime.datetime.now())
    shutil.copy(args.ntuple, backup)
    for treename in list_trees(backup):
        if not treename.endswith('_mva'):
            continue
        branches = []
        print "processing", treename
        for b in list_branches(backup, treename):
            if 'likelihood' not in b:
                branches.append(b)
        try:
            data = root2array(backup, treename, branches)
        except ValueError:
            tree = array2tree(
                np.array([], dtype=[(b, 'float64') for b in branches + 'tmva_likelihood tmva_likelihood_linear'.split()]),
                treename
            )
            with root_open(args.ntuple, 'update') as f:
                f.WriteObject(tree, treename, "WriteDelete")
            continue
        likelihoods = []
        likelihoods_linear = []
        for tt, ttZ in zip(data['tmva_tt'], data['tmva_ttZ']):
            likelihoods.append(likelihood.GetBinContent(likelihood.FindBin(tt, ttZ)))
            likelihoods_linear.append(likelihood_linear.GetBinContent(likelihood.FindBin(tt, ttZ)))
        tree = array2tree(
            rfn.append_fields(data, names=['tmva_likelihood', 'tmva_likelihood_linear'], data=[likelihoods, likelihoods_linear]),
            treename
        )
        with root_open(args.ntuple, 'update') as f:
            f.WriteObject(tree, treename, "WriteDelete")
