#!/usr/bin/env python

import copy
import re

officialnames = {
        "JES": "CMS_scale_j",
        "JER": "CMS_res_j"
}
sysre = re.compile(r'(.*)(Up|Down)$')

def officialize(s):
    stem, way = sysre.match(s).groups()
    return officialnames[stem] + way

def add_systematics(configs):
    sys = ["NA", "JESUp", "JESDown", "JERUp", "JERDown"]

    for dirname, config in configs:
        for s in sys:
            newconfig = copy.deepcopy(config)
            newdir = dirname
            if s != "NA":
                newdir += "_" + s
                newconfig['histformat'] += "_" + officialize(s)

            newconfig['systematics'] = s
            newconfig['outdir'] = newdir

            yield newdir, newconfig

import argparse
import os
import yaml

parser = argparse.ArgumentParser(description='Get stuff ready to be analyzed.')
parser.add_argument('configuration')
parser.add_argument('directory')
args = parser.parse_args()

with open(args.configuration) as f:
    config = yaml.load(f)

for dn, conf in add_systematics([[os.path.join(args.directory, 'ttl'), config]]):
    os.makedirs(dn)
    with open(os.path.join(dn, 'roaster.yaml'), 'w') as f:
        yaml.dump(conf, f, allow_unicode=True)
