// vim: ts=4:sw=4:et:sta
#include "../interface/Branches.h"

using namespace roast;

void
Branches::Clear()
{
    // >>> Begin clear <<<
    CSVeventWeight->clear();
    CSVeventWeightCErr1down->clear();
    CSVeventWeightCErr1up->clear();
    CSVeventWeightCErr2down->clear();
    CSVeventWeightCErr2up->clear();
    CSVeventWeightHFStats1down->clear();
    CSVeventWeightHFStats1up->clear();
    CSVeventWeightHFStats2down->clear();
    CSVeventWeightHFStats2up->clear();
    CSVeventWeightHFdown->clear();
    CSVeventWeightHFup->clear();
    CSVeventWeightLFStats1down->clear();
    CSVeventWeightLFStats1up->clear();
    CSVeventWeightLFStats2down->clear();
    CSVeventWeightLFStats2up->clear();
    CSVeventWeightLFdown->clear();
    CSVeventWeightLFup->clear();
    GJ_Eta->clear();
    GJ_IsBjet->clear();
    GJ_MomentumRank->clear();
    GJ_Phi->clear();
    GJ_Pt->clear();
    GT_Eta->clear();
    GT_MomentumRank->clear();
    GT_ParentEta->clear();
    GT_ParentId->clear();
    GT_ParentP->clear();
    GT_ParentPhi->clear();
    GT_ParentPt->clear();
    GT_Phi->clear();
    GT_Pt->clear();
    GT_ToElectron->clear();
    GT_ToHadrons->clear();
    GT_ToMuon->clear();
    GT_VisEta->clear();
    GT_VisPhi->clear();
    GT_VisPt->clear();
    HT->clear();
    IsTauEvent = 0;
    J_Charge->clear();
    J_MomentumRank->clear();
    J_NumJets->clear();
    J_P->clear();
    J_PartonGrandParentId->clear();
    J_PartonGrandmother00Id->clear();
    J_PartonGrandmother00Status->clear();
    J_PartonGrandmother01Id->clear();
    J_PartonGrandmother01Status->clear();
    J_PartonGrandmother10Id->clear();
    J_PartonGrandmother10Status->clear();
    J_PartonGrandmother11Id->clear();
    J_PartonGrandmother11Status->clear();
    J_PartonId->clear();
    J_PartonMother0Id->clear();
    J_PartonMother0Status->clear();
    J_PartonMother1Id->clear();
    J_PartonMother1Status->clear();
    J_PartonParentId->clear();
    J_PartonStatus->clear();
    J_combSecVtxBTag->clear();
    J_combSecVtxLooseBTag->clear();
    J_combSecVtxMediumBTag->clear();
    J_combSecVtxTightBTag->clear();
    MET_P->clear();
    MHT->clear();
    MomentumRank->clear();
    NTruePV = 0;
    NumCSVLbtagJets->clear();
    NumCSVMbtagJets->clear();
    NumCSVTbtagJets->clear();
    NumCleanCSVLbtagJets->clear();
    NumCleanCSVMbtagJets->clear();
    NumCleanCSVTbtagJets->clear();
    NumCleanNonCSVLbtagJets->clear();
    NumCleanNonCSVMbtagJets->clear();
    NumCleanNonCSVTbtagJets->clear();
    NumCombos = 0;
    NumExLooseElectrons->clear();
    NumExLooseMuons->clear();
    NumGenJets = 0;
    NumGenTaus = 0;
    NumInteractionsBX0 = 0;
    NumInteractionsBXm1 = 0;
    NumInteractionsBXp1 = 0;
    NumLooseElectrons->clear();
    NumLooseMuons->clear();
    NumNonCSVLbtagJets->clear();
    NumNonCSVMbtagJets->clear();
    NumNonCSVTbtagJets->clear();
    NumRecoTaus = 0;
    NumTaus = 0;
    NumTightElectrons->clear();
    NumTightMuons->clear();
    NumVertices = 0;
    RT_Charge->clear();
    RT_DecayMode->clear();
    RT_EmFraction->clear();
    RT_GenMatchDaughter0Id->clear();
    RT_GenMatchDaughter0Status->clear();
    RT_GenMatchDaughter1Id->clear();
    RT_GenMatchDaughter1Status->clear();
    RT_GenMatchGrandmother00Id->clear();
    RT_GenMatchGrandmother00Status->clear();
    RT_GenMatchGrandmother01Id->clear();
    RT_GenMatchGrandmother01Status->clear();
    RT_GenMatchGrandmother10Id->clear();
    RT_GenMatchGrandmother10Status->clear();
    RT_GenMatchGrandmother11Id->clear();
    RT_GenMatchGrandmother11Status->clear();
    RT_GenMatchId->clear();
    RT_GenMatchMother0Id->clear();
    RT_GenMatchMother0Status->clear();
    RT_GenMatchMother1Id->clear();
    RT_GenMatchMother1Status->clear();
    RT_GenMatchStatus->clear();
    RT_HPSagainstElectronDeadECAL->clear();
    RT_HPSagainstElectronLoose->clear();
    RT_HPSagainstElectronLooseMVA2->clear();
    RT_HPSagainstElectronLooseMVA3->clear();
    RT_HPSagainstElectronMVA->clear();
    RT_HPSagainstElectronMVA2category->clear();
    RT_HPSagainstElectronMVA2raw->clear();
    RT_HPSagainstElectronMVA3category->clear();
    RT_HPSagainstElectronMVA3raw->clear();
    RT_HPSagainstElectronMedium->clear();
    RT_HPSagainstElectronMediumMVA2->clear();
    RT_HPSagainstElectronMediumMVA3->clear();
    RT_HPSagainstElectronTight->clear();
    RT_HPSagainstElectronTightMVA2->clear();
    RT_HPSagainstElectronTightMVA3->clear();
    RT_HPSagainstElectronVLooseMVA2->clear();
    RT_HPSagainstElectronVTightMVA3->clear();
    RT_HPSagainstMuonLoose->clear();
    RT_HPSagainstMuonLoose2->clear();
    RT_HPSagainstMuonMedium->clear();
    RT_HPSagainstMuonMedium2->clear();
    RT_HPSagainstMuonTight->clear();
    RT_HPSagainstMuonTight2->clear();
    RT_HPSbyCombinedIsolationDeltaBetaCorrRaw->clear();
    RT_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits->clear();
    RT_HPSbyIsolationMVA2raw->clear();
    RT_HPSbyIsolationMVAraw->clear();
    RT_HPSbyLooseCombinedIsolationDeltaBetaCorr->clear();
    RT_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits->clear();
    RT_HPSbyLooseIsolationMVA->clear();
    RT_HPSbyLooseIsolationMVA2->clear();
    RT_HPSbyMediumCombinedIsolationDeltaBetaCorr->clear();
    RT_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits->clear();
    RT_HPSbyMediumIsolationMVA->clear();
    RT_HPSbyMediumIsolationMVA2->clear();
    RT_HPSbyTightCombinedIsolationDeltaBetaCorr->clear();
    RT_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits->clear();
    RT_HPSbyTightIsolationMVA->clear();
    RT_HPSbyTightIsolationMVA2->clear();
    RT_HPSbyVLooseCombinedIsolationDeltaBetaCorr->clear();
    RT_HPSdecayModeFinding->clear();
    RT_IsInTheCracks->clear();
    RT_JetCSV->clear();
    RT_LTIpVtdxy->clear();
    RT_LTIpVtdxyError->clear();
    RT_LTIpVtdz->clear();
    RT_LTIpVtdzError->clear();
    RT_LTNormChiSqrd->clear();
    RT_LTPt->clear();
    RT_LTValidHits->clear();
    RT_LTvalid->clear();
    RT_LTvx->clear();
    RT_LTvy->clear();
    RT_LTvz->clear();
    RT_MomentumRank->clear();
    RT_NProngs->clear();
    RT_NSignalGammas->clear();
    RT_NSignalNeutrals->clear();
    RT_P->clear();
    TriggerEventWeight->clear();
    V_NormChiSquared->clear();
    V_NumDOF->clear();
    V_Rho->clear();
    V_Xcoord->clear();
    V_XcoordErr->clear();
    V_Ycoord->clear();
    V_YcoordErr->clear();
    V_Zcoord->clear();
    V_ZcoordErr->clear();
    bQuarkCount = 0;
    cQuarkCount = 0;
    event = 0;
    higgsDecayMode = 0;
    lumi = 0;
    puWeight = 0;
    puWeightDown = 0;
    puWeightUp = 0;
    q2WeightDown = 0;
    q2WeightUp = 0;
    run = 0;
    topPtWeight = 0;
    topPtWeightDown = 0;
    topPtWeightUp = 0;
    // >>> End clear <<<
}

void
Branches::Delete()
{
    // >>> Begin delete <<<
    delete CSVeventWeight;
    delete CSVeventWeightCErr1down;
    delete CSVeventWeightCErr1up;
    delete CSVeventWeightCErr2down;
    delete CSVeventWeightCErr2up;
    delete CSVeventWeightHFStats1down;
    delete CSVeventWeightHFStats1up;
    delete CSVeventWeightHFStats2down;
    delete CSVeventWeightHFStats2up;
    delete CSVeventWeightHFdown;
    delete CSVeventWeightHFup;
    delete CSVeventWeightLFStats1down;
    delete CSVeventWeightLFStats1up;
    delete CSVeventWeightLFStats2down;
    delete CSVeventWeightLFStats2up;
    delete CSVeventWeightLFdown;
    delete CSVeventWeightLFup;
    delete GJ_Eta;
    delete GJ_IsBjet;
    delete GJ_MomentumRank;
    delete GJ_Phi;
    delete GJ_Pt;
    delete GT_Eta;
    delete GT_MomentumRank;
    delete GT_ParentEta;
    delete GT_ParentId;
    delete GT_ParentP;
    delete GT_ParentPhi;
    delete GT_ParentPt;
    delete GT_Phi;
    delete GT_Pt;
    delete GT_ToElectron;
    delete GT_ToHadrons;
    delete GT_ToMuon;
    delete GT_VisEta;
    delete GT_VisPhi;
    delete GT_VisPt;
    delete HT;
    delete J_Charge;
    delete J_MomentumRank;
    delete J_NumJets;
    delete J_P;
    delete J_PartonGrandParentId;
    delete J_PartonGrandmother00Id;
    delete J_PartonGrandmother00Status;
    delete J_PartonGrandmother01Id;
    delete J_PartonGrandmother01Status;
    delete J_PartonGrandmother10Id;
    delete J_PartonGrandmother10Status;
    delete J_PartonGrandmother11Id;
    delete J_PartonGrandmother11Status;
    delete J_PartonId;
    delete J_PartonMother0Id;
    delete J_PartonMother0Status;
    delete J_PartonMother1Id;
    delete J_PartonMother1Status;
    delete J_PartonParentId;
    delete J_PartonStatus;
    delete J_combSecVtxBTag;
    delete J_combSecVtxLooseBTag;
    delete J_combSecVtxMediumBTag;
    delete J_combSecVtxTightBTag;
    delete MET_P;
    delete MHT;
    delete MomentumRank;
    delete NumCSVLbtagJets;
    delete NumCSVMbtagJets;
    delete NumCSVTbtagJets;
    delete NumCleanCSVLbtagJets;
    delete NumCleanCSVMbtagJets;
    delete NumCleanCSVTbtagJets;
    delete NumCleanNonCSVLbtagJets;
    delete NumCleanNonCSVMbtagJets;
    delete NumCleanNonCSVTbtagJets;
    delete NumExLooseElectrons;
    delete NumExLooseMuons;
    delete NumLooseElectrons;
    delete NumLooseMuons;
    delete NumNonCSVLbtagJets;
    delete NumNonCSVMbtagJets;
    delete NumNonCSVTbtagJets;
    delete NumTightElectrons;
    delete NumTightMuons;
    delete RT_Charge;
    delete RT_DecayMode;
    delete RT_EmFraction;
    delete RT_GenMatchDaughter0Id;
    delete RT_GenMatchDaughter0Status;
    delete RT_GenMatchDaughter1Id;
    delete RT_GenMatchDaughter1Status;
    delete RT_GenMatchGrandmother00Id;
    delete RT_GenMatchGrandmother00Status;
    delete RT_GenMatchGrandmother01Id;
    delete RT_GenMatchGrandmother01Status;
    delete RT_GenMatchGrandmother10Id;
    delete RT_GenMatchGrandmother10Status;
    delete RT_GenMatchGrandmother11Id;
    delete RT_GenMatchGrandmother11Status;
    delete RT_GenMatchId;
    delete RT_GenMatchMother0Id;
    delete RT_GenMatchMother0Status;
    delete RT_GenMatchMother1Id;
    delete RT_GenMatchMother1Status;
    delete RT_GenMatchStatus;
    delete RT_HPSagainstElectronDeadECAL;
    delete RT_HPSagainstElectronLoose;
    delete RT_HPSagainstElectronLooseMVA2;
    delete RT_HPSagainstElectronLooseMVA3;
    delete RT_HPSagainstElectronMVA;
    delete RT_HPSagainstElectronMVA2category;
    delete RT_HPSagainstElectronMVA2raw;
    delete RT_HPSagainstElectronMVA3category;
    delete RT_HPSagainstElectronMVA3raw;
    delete RT_HPSagainstElectronMedium;
    delete RT_HPSagainstElectronMediumMVA2;
    delete RT_HPSagainstElectronMediumMVA3;
    delete RT_HPSagainstElectronTight;
    delete RT_HPSagainstElectronTightMVA2;
    delete RT_HPSagainstElectronTightMVA3;
    delete RT_HPSagainstElectronVLooseMVA2;
    delete RT_HPSagainstElectronVTightMVA3;
    delete RT_HPSagainstMuonLoose;
    delete RT_HPSagainstMuonLoose2;
    delete RT_HPSagainstMuonMedium;
    delete RT_HPSagainstMuonMedium2;
    delete RT_HPSagainstMuonTight;
    delete RT_HPSagainstMuonTight2;
    delete RT_HPSbyCombinedIsolationDeltaBetaCorrRaw;
    delete RT_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits;
    delete RT_HPSbyIsolationMVA2raw;
    delete RT_HPSbyIsolationMVAraw;
    delete RT_HPSbyLooseCombinedIsolationDeltaBetaCorr;
    delete RT_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits;
    delete RT_HPSbyLooseIsolationMVA;
    delete RT_HPSbyLooseIsolationMVA2;
    delete RT_HPSbyMediumCombinedIsolationDeltaBetaCorr;
    delete RT_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits;
    delete RT_HPSbyMediumIsolationMVA;
    delete RT_HPSbyMediumIsolationMVA2;
    delete RT_HPSbyTightCombinedIsolationDeltaBetaCorr;
    delete RT_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits;
    delete RT_HPSbyTightIsolationMVA;
    delete RT_HPSbyTightIsolationMVA2;
    delete RT_HPSbyVLooseCombinedIsolationDeltaBetaCorr;
    delete RT_HPSdecayModeFinding;
    delete RT_IsInTheCracks;
    delete RT_JetCSV;
    delete RT_LTIpVtdxy;
    delete RT_LTIpVtdxyError;
    delete RT_LTIpVtdz;
    delete RT_LTIpVtdzError;
    delete RT_LTNormChiSqrd;
    delete RT_LTPt;
    delete RT_LTValidHits;
    delete RT_LTvalid;
    delete RT_LTvx;
    delete RT_LTvy;
    delete RT_LTvz;
    delete RT_MomentumRank;
    delete RT_NProngs;
    delete RT_NSignalGammas;
    delete RT_NSignalNeutrals;
    delete RT_P;
    delete TriggerEventWeight;
    delete V_NormChiSquared;
    delete V_NumDOF;
    delete V_Rho;
    delete V_Xcoord;
    delete V_XcoordErr;
    delete V_Ycoord;
    delete V_YcoordErr;
    delete V_Zcoord;
    delete V_ZcoordErr;
    // >>> End delete <<<
}

void
Branches::Null()
{
    // >>> Begin null <<<
    CSVeventWeight = 0;
    CSVeventWeightCErr1down = 0;
    CSVeventWeightCErr1up = 0;
    CSVeventWeightCErr2down = 0;
    CSVeventWeightCErr2up = 0;
    CSVeventWeightHFStats1down = 0;
    CSVeventWeightHFStats1up = 0;
    CSVeventWeightHFStats2down = 0;
    CSVeventWeightHFStats2up = 0;
    CSVeventWeightHFdown = 0;
    CSVeventWeightHFup = 0;
    CSVeventWeightLFStats1down = 0;
    CSVeventWeightLFStats1up = 0;
    CSVeventWeightLFStats2down = 0;
    CSVeventWeightLFStats2up = 0;
    CSVeventWeightLFdown = 0;
    CSVeventWeightLFup = 0;
    GJ_Eta = 0;
    GJ_IsBjet = 0;
    GJ_MomentumRank = 0;
    GJ_Phi = 0;
    GJ_Pt = 0;
    GT_Eta = 0;
    GT_MomentumRank = 0;
    GT_ParentEta = 0;
    GT_ParentId = 0;
    GT_ParentP = 0;
    GT_ParentPhi = 0;
    GT_ParentPt = 0;
    GT_Phi = 0;
    GT_Pt = 0;
    GT_ToElectron = 0;
    GT_ToHadrons = 0;
    GT_ToMuon = 0;
    GT_VisEta = 0;
    GT_VisPhi = 0;
    GT_VisPt = 0;
    HT = 0;
    IsTauEvent = 0;
    J_Charge = 0;
    J_MomentumRank = 0;
    J_NumJets = 0;
    J_P = 0;
    J_PartonGrandParentId = 0;
    J_PartonGrandmother00Id = 0;
    J_PartonGrandmother00Status = 0;
    J_PartonGrandmother01Id = 0;
    J_PartonGrandmother01Status = 0;
    J_PartonGrandmother10Id = 0;
    J_PartonGrandmother10Status = 0;
    J_PartonGrandmother11Id = 0;
    J_PartonGrandmother11Status = 0;
    J_PartonId = 0;
    J_PartonMother0Id = 0;
    J_PartonMother0Status = 0;
    J_PartonMother1Id = 0;
    J_PartonMother1Status = 0;
    J_PartonParentId = 0;
    J_PartonStatus = 0;
    J_combSecVtxBTag = 0;
    J_combSecVtxLooseBTag = 0;
    J_combSecVtxMediumBTag = 0;
    J_combSecVtxTightBTag = 0;
    MET_P = 0;
    MHT = 0;
    MomentumRank = 0;
    NTruePV = 0;
    NumCSVLbtagJets = 0;
    NumCSVMbtagJets = 0;
    NumCSVTbtagJets = 0;
    NumCleanCSVLbtagJets = 0;
    NumCleanCSVMbtagJets = 0;
    NumCleanCSVTbtagJets = 0;
    NumCleanNonCSVLbtagJets = 0;
    NumCleanNonCSVMbtagJets = 0;
    NumCleanNonCSVTbtagJets = 0;
    NumCombos = 0;
    NumExLooseElectrons = 0;
    NumExLooseMuons = 0;
    NumGenJets = 0;
    NumGenTaus = 0;
    NumInteractionsBX0 = 0;
    NumInteractionsBXm1 = 0;
    NumInteractionsBXp1 = 0;
    NumLooseElectrons = 0;
    NumLooseMuons = 0;
    NumNonCSVLbtagJets = 0;
    NumNonCSVMbtagJets = 0;
    NumNonCSVTbtagJets = 0;
    NumRecoTaus = 0;
    NumTaus = 0;
    NumTightElectrons = 0;
    NumTightMuons = 0;
    NumVertices = 0;
    RT_Charge = 0;
    RT_DecayMode = 0;
    RT_EmFraction = 0;
    RT_GenMatchDaughter0Id = 0;
    RT_GenMatchDaughter0Status = 0;
    RT_GenMatchDaughter1Id = 0;
    RT_GenMatchDaughter1Status = 0;
    RT_GenMatchGrandmother00Id = 0;
    RT_GenMatchGrandmother00Status = 0;
    RT_GenMatchGrandmother01Id = 0;
    RT_GenMatchGrandmother01Status = 0;
    RT_GenMatchGrandmother10Id = 0;
    RT_GenMatchGrandmother10Status = 0;
    RT_GenMatchGrandmother11Id = 0;
    RT_GenMatchGrandmother11Status = 0;
    RT_GenMatchId = 0;
    RT_GenMatchMother0Id = 0;
    RT_GenMatchMother0Status = 0;
    RT_GenMatchMother1Id = 0;
    RT_GenMatchMother1Status = 0;
    RT_GenMatchStatus = 0;
    RT_HPSagainstElectronDeadECAL = 0;
    RT_HPSagainstElectronLoose = 0;
    RT_HPSagainstElectronLooseMVA2 = 0;
    RT_HPSagainstElectronLooseMVA3 = 0;
    RT_HPSagainstElectronMVA = 0;
    RT_HPSagainstElectronMVA2category = 0;
    RT_HPSagainstElectronMVA2raw = 0;
    RT_HPSagainstElectronMVA3category = 0;
    RT_HPSagainstElectronMVA3raw = 0;
    RT_HPSagainstElectronMedium = 0;
    RT_HPSagainstElectronMediumMVA2 = 0;
    RT_HPSagainstElectronMediumMVA3 = 0;
    RT_HPSagainstElectronTight = 0;
    RT_HPSagainstElectronTightMVA2 = 0;
    RT_HPSagainstElectronTightMVA3 = 0;
    RT_HPSagainstElectronVLooseMVA2 = 0;
    RT_HPSagainstElectronVTightMVA3 = 0;
    RT_HPSagainstMuonLoose = 0;
    RT_HPSagainstMuonLoose2 = 0;
    RT_HPSagainstMuonMedium = 0;
    RT_HPSagainstMuonMedium2 = 0;
    RT_HPSagainstMuonTight = 0;
    RT_HPSagainstMuonTight2 = 0;
    RT_HPSbyCombinedIsolationDeltaBetaCorrRaw = 0;
    RT_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits = 0;
    RT_HPSbyIsolationMVA2raw = 0;
    RT_HPSbyIsolationMVAraw = 0;
    RT_HPSbyLooseCombinedIsolationDeltaBetaCorr = 0;
    RT_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits = 0;
    RT_HPSbyLooseIsolationMVA = 0;
    RT_HPSbyLooseIsolationMVA2 = 0;
    RT_HPSbyMediumCombinedIsolationDeltaBetaCorr = 0;
    RT_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits = 0;
    RT_HPSbyMediumIsolationMVA = 0;
    RT_HPSbyMediumIsolationMVA2 = 0;
    RT_HPSbyTightCombinedIsolationDeltaBetaCorr = 0;
    RT_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits = 0;
    RT_HPSbyTightIsolationMVA = 0;
    RT_HPSbyTightIsolationMVA2 = 0;
    RT_HPSbyVLooseCombinedIsolationDeltaBetaCorr = 0;
    RT_HPSdecayModeFinding = 0;
    RT_IsInTheCracks = 0;
    RT_JetCSV = 0;
    RT_LTIpVtdxy = 0;
    RT_LTIpVtdxyError = 0;
    RT_LTIpVtdz = 0;
    RT_LTIpVtdzError = 0;
    RT_LTNormChiSqrd = 0;
    RT_LTPt = 0;
    RT_LTValidHits = 0;
    RT_LTvalid = 0;
    RT_LTvx = 0;
    RT_LTvy = 0;
    RT_LTvz = 0;
    RT_MomentumRank = 0;
    RT_NProngs = 0;
    RT_NSignalGammas = 0;
    RT_NSignalNeutrals = 0;
    RT_P = 0;
    TriggerEventWeight = 0;
    V_NormChiSquared = 0;
    V_NumDOF = 0;
    V_Rho = 0;
    V_Xcoord = 0;
    V_XcoordErr = 0;
    V_Ycoord = 0;
    V_YcoordErr = 0;
    V_Zcoord = 0;
    V_ZcoordErr = 0;
    bQuarkCount = 0;
    cQuarkCount = 0;
    event = 0;
    higgsDecayMode = 0;
    lumi = 0;
    puWeight = 0;
    puWeightDown = 0;
    puWeightUp = 0;
    q2WeightDown = 0;
    q2WeightUp = 0;
    run = 0;
    topPtWeight = 0;
    topPtWeightDown = 0;
    topPtWeightUp = 0;
    // >>> End null <<<
}

void
Branches::SetBranchAddresses()
{
    // >>> Begin address <<<
    fChain->SetBranchAddress("CSVeventWeight", &CSVeventWeight);
    fChain->SetBranchAddress("CSVeventWeightCErr1down", &CSVeventWeightCErr1down);
    fChain->SetBranchAddress("CSVeventWeightCErr1up", &CSVeventWeightCErr1up);
    fChain->SetBranchAddress("CSVeventWeightCErr2down", &CSVeventWeightCErr2down);
    fChain->SetBranchAddress("CSVeventWeightCErr2up", &CSVeventWeightCErr2up);
    fChain->SetBranchAddress("CSVeventWeightHFStats1down", &CSVeventWeightHFStats1down);
    fChain->SetBranchAddress("CSVeventWeightHFStats1up", &CSVeventWeightHFStats1up);
    fChain->SetBranchAddress("CSVeventWeightHFStats2down", &CSVeventWeightHFStats2down);
    fChain->SetBranchAddress("CSVeventWeightHFStats2up", &CSVeventWeightHFStats2up);
    fChain->SetBranchAddress("CSVeventWeightHFdown", &CSVeventWeightHFdown);
    fChain->SetBranchAddress("CSVeventWeightHFup", &CSVeventWeightHFup);
    fChain->SetBranchAddress("CSVeventWeightLFStats1down", &CSVeventWeightLFStats1down);
    fChain->SetBranchAddress("CSVeventWeightLFStats1up", &CSVeventWeightLFStats1up);
    fChain->SetBranchAddress("CSVeventWeightLFStats2down", &CSVeventWeightLFStats2down);
    fChain->SetBranchAddress("CSVeventWeightLFStats2up", &CSVeventWeightLFStats2up);
    fChain->SetBranchAddress("CSVeventWeightLFdown", &CSVeventWeightLFdown);
    fChain->SetBranchAddress("CSVeventWeightLFup", &CSVeventWeightLFup);
    fChain->SetBranchAddress("GJ_Eta", &GJ_Eta);
    fChain->SetBranchAddress("GJ_IsBjet", &GJ_IsBjet);
    fChain->SetBranchAddress("GJ_MomentumRank", &GJ_MomentumRank);
    fChain->SetBranchAddress("GJ_Phi", &GJ_Phi);
    fChain->SetBranchAddress("GJ_Pt", &GJ_Pt);
    fChain->SetBranchAddress("GT_Eta", &GT_Eta);
    fChain->SetBranchAddress("GT_MomentumRank", &GT_MomentumRank);
    fChain->SetBranchAddress("GT_ParentEta", &GT_ParentEta);
    fChain->SetBranchAddress("GT_ParentId", &GT_ParentId);
    fChain->SetBranchAddress("GT_ParentP", &GT_ParentP);
    fChain->SetBranchAddress("GT_ParentPhi", &GT_ParentPhi);
    fChain->SetBranchAddress("GT_ParentPt", &GT_ParentPt);
    fChain->SetBranchAddress("GT_Phi", &GT_Phi);
    fChain->SetBranchAddress("GT_Pt", &GT_Pt);
    fChain->SetBranchAddress("GT_ToElectron", &GT_ToElectron);
    fChain->SetBranchAddress("GT_ToHadrons", &GT_ToHadrons);
    fChain->SetBranchAddress("GT_ToMuon", &GT_ToMuon);
    fChain->SetBranchAddress("GT_VisEta", &GT_VisEta);
    fChain->SetBranchAddress("GT_VisPhi", &GT_VisPhi);
    fChain->SetBranchAddress("GT_VisPt", &GT_VisPt);
    fChain->SetBranchAddress("HT", &HT);
    fChain->SetBranchAddress("IsTauEvent", &IsTauEvent);
    fChain->SetBranchAddress("J_Charge", &J_Charge);
    fChain->SetBranchAddress("J_MomentumRank", &J_MomentumRank);
    fChain->SetBranchAddress("J_NumJets", &J_NumJets);
    fChain->SetBranchAddress("J_P", &J_P);
    fChain->SetBranchAddress("J_PartonGrandParentId", &J_PartonGrandParentId);
    fChain->SetBranchAddress("J_PartonGrandmother00Id", &J_PartonGrandmother00Id);
    fChain->SetBranchAddress("J_PartonGrandmother00Status", &J_PartonGrandmother00Status);
    fChain->SetBranchAddress("J_PartonGrandmother01Id", &J_PartonGrandmother01Id);
    fChain->SetBranchAddress("J_PartonGrandmother01Status", &J_PartonGrandmother01Status);
    fChain->SetBranchAddress("J_PartonGrandmother10Id", &J_PartonGrandmother10Id);
    fChain->SetBranchAddress("J_PartonGrandmother10Status", &J_PartonGrandmother10Status);
    fChain->SetBranchAddress("J_PartonGrandmother11Id", &J_PartonGrandmother11Id);
    fChain->SetBranchAddress("J_PartonGrandmother11Status", &J_PartonGrandmother11Status);
    fChain->SetBranchAddress("J_PartonId", &J_PartonId);
    fChain->SetBranchAddress("J_PartonMother0Id", &J_PartonMother0Id);
    fChain->SetBranchAddress("J_PartonMother0Status", &J_PartonMother0Status);
    fChain->SetBranchAddress("J_PartonMother1Id", &J_PartonMother1Id);
    fChain->SetBranchAddress("J_PartonMother1Status", &J_PartonMother1Status);
    fChain->SetBranchAddress("J_PartonParentId", &J_PartonParentId);
    fChain->SetBranchAddress("J_PartonStatus", &J_PartonStatus);
    fChain->SetBranchAddress("J_combSecVtxBTag", &J_combSecVtxBTag);
    fChain->SetBranchAddress("J_combSecVtxLooseBTag", &J_combSecVtxLooseBTag);
    fChain->SetBranchAddress("J_combSecVtxMediumBTag", &J_combSecVtxMediumBTag);
    fChain->SetBranchAddress("J_combSecVtxTightBTag", &J_combSecVtxTightBTag);
    fChain->SetBranchAddress("MET_P", &MET_P);
    fChain->SetBranchAddress("MHT", &MHT);
    fChain->SetBranchAddress("MomentumRank", &MomentumRank);
    fChain->SetBranchAddress("NTruePV", &NTruePV);
    fChain->SetBranchAddress("NumCSVLbtagJets", &NumCSVLbtagJets);
    fChain->SetBranchAddress("NumCSVMbtagJets", &NumCSVMbtagJets);
    fChain->SetBranchAddress("NumCSVTbtagJets", &NumCSVTbtagJets);
    fChain->SetBranchAddress("NumCleanCSVLbtagJets", &NumCleanCSVLbtagJets);
    fChain->SetBranchAddress("NumCleanCSVMbtagJets", &NumCleanCSVMbtagJets);
    fChain->SetBranchAddress("NumCleanCSVTbtagJets", &NumCleanCSVTbtagJets);
    fChain->SetBranchAddress("NumCleanNonCSVLbtagJets", &NumCleanNonCSVLbtagJets);
    fChain->SetBranchAddress("NumCleanNonCSVMbtagJets", &NumCleanNonCSVMbtagJets);
    fChain->SetBranchAddress("NumCleanNonCSVTbtagJets", &NumCleanNonCSVTbtagJets);
    fChain->SetBranchAddress("NumCombos", &NumCombos);
    fChain->SetBranchAddress("NumExLooseElectrons", &NumExLooseElectrons);
    fChain->SetBranchAddress("NumExLooseMuons", &NumExLooseMuons);
    fChain->SetBranchAddress("NumGenJets", &NumGenJets);
    fChain->SetBranchAddress("NumGenTaus", &NumGenTaus);
    fChain->SetBranchAddress("NumInteractionsBX0", &NumInteractionsBX0);
    fChain->SetBranchAddress("NumInteractionsBXm1", &NumInteractionsBXm1);
    fChain->SetBranchAddress("NumInteractionsBXp1", &NumInteractionsBXp1);
    fChain->SetBranchAddress("NumLooseElectrons", &NumLooseElectrons);
    fChain->SetBranchAddress("NumLooseMuons", &NumLooseMuons);
    fChain->SetBranchAddress("NumNonCSVLbtagJets", &NumNonCSVLbtagJets);
    fChain->SetBranchAddress("NumNonCSVMbtagJets", &NumNonCSVMbtagJets);
    fChain->SetBranchAddress("NumNonCSVTbtagJets", &NumNonCSVTbtagJets);
    fChain->SetBranchAddress("NumRecoTaus", &NumRecoTaus);
    fChain->SetBranchAddress("NumTaus", &NumTaus);
    fChain->SetBranchAddress("NumTightElectrons", &NumTightElectrons);
    fChain->SetBranchAddress("NumTightMuons", &NumTightMuons);
    fChain->SetBranchAddress("NumVertices", &NumVertices);
    fChain->SetBranchAddress("RT_Charge", &RT_Charge);
    fChain->SetBranchAddress("RT_DecayMode", &RT_DecayMode);
    fChain->SetBranchAddress("RT_EmFraction", &RT_EmFraction);
    fChain->SetBranchAddress("RT_GenMatchDaughter0Id", &RT_GenMatchDaughter0Id);
    fChain->SetBranchAddress("RT_GenMatchDaughter0Status", &RT_GenMatchDaughter0Status);
    fChain->SetBranchAddress("RT_GenMatchDaughter1Id", &RT_GenMatchDaughter1Id);
    fChain->SetBranchAddress("RT_GenMatchDaughter1Status", &RT_GenMatchDaughter1Status);
    fChain->SetBranchAddress("RT_GenMatchGrandmother00Id", &RT_GenMatchGrandmother00Id);
    fChain->SetBranchAddress("RT_GenMatchGrandmother00Status", &RT_GenMatchGrandmother00Status);
    fChain->SetBranchAddress("RT_GenMatchGrandmother01Id", &RT_GenMatchGrandmother01Id);
    fChain->SetBranchAddress("RT_GenMatchGrandmother01Status", &RT_GenMatchGrandmother01Status);
    fChain->SetBranchAddress("RT_GenMatchGrandmother10Id", &RT_GenMatchGrandmother10Id);
    fChain->SetBranchAddress("RT_GenMatchGrandmother10Status", &RT_GenMatchGrandmother10Status);
    fChain->SetBranchAddress("RT_GenMatchGrandmother11Id", &RT_GenMatchGrandmother11Id);
    fChain->SetBranchAddress("RT_GenMatchGrandmother11Status", &RT_GenMatchGrandmother11Status);
    fChain->SetBranchAddress("RT_GenMatchId", &RT_GenMatchId);
    fChain->SetBranchAddress("RT_GenMatchMother0Id", &RT_GenMatchMother0Id);
    fChain->SetBranchAddress("RT_GenMatchMother0Status", &RT_GenMatchMother0Status);
    fChain->SetBranchAddress("RT_GenMatchMother1Id", &RT_GenMatchMother1Id);
    fChain->SetBranchAddress("RT_GenMatchMother1Status", &RT_GenMatchMother1Status);
    fChain->SetBranchAddress("RT_GenMatchStatus", &RT_GenMatchStatus);
    fChain->SetBranchAddress("RT_HPSagainstElectronDeadECAL", &RT_HPSagainstElectronDeadECAL);
    fChain->SetBranchAddress("RT_HPSagainstElectronLoose", &RT_HPSagainstElectronLoose);
    fChain->SetBranchAddress("RT_HPSagainstElectronLooseMVA2", &RT_HPSagainstElectronLooseMVA2);
    fChain->SetBranchAddress("RT_HPSagainstElectronLooseMVA3", &RT_HPSagainstElectronLooseMVA3);
    fChain->SetBranchAddress("RT_HPSagainstElectronMVA", &RT_HPSagainstElectronMVA);
    fChain->SetBranchAddress("RT_HPSagainstElectronMVA2category", &RT_HPSagainstElectronMVA2category);
    fChain->SetBranchAddress("RT_HPSagainstElectronMVA2raw", &RT_HPSagainstElectronMVA2raw);
    fChain->SetBranchAddress("RT_HPSagainstElectronMVA3category", &RT_HPSagainstElectronMVA3category);
    fChain->SetBranchAddress("RT_HPSagainstElectronMVA3raw", &RT_HPSagainstElectronMVA3raw);
    fChain->SetBranchAddress("RT_HPSagainstElectronMedium", &RT_HPSagainstElectronMedium);
    fChain->SetBranchAddress("RT_HPSagainstElectronMediumMVA2", &RT_HPSagainstElectronMediumMVA2);
    fChain->SetBranchAddress("RT_HPSagainstElectronMediumMVA3", &RT_HPSagainstElectronMediumMVA3);
    fChain->SetBranchAddress("RT_HPSagainstElectronTight", &RT_HPSagainstElectronTight);
    fChain->SetBranchAddress("RT_HPSagainstElectronTightMVA2", &RT_HPSagainstElectronTightMVA2);
    fChain->SetBranchAddress("RT_HPSagainstElectronTightMVA3", &RT_HPSagainstElectronTightMVA3);
    fChain->SetBranchAddress("RT_HPSagainstElectronVLooseMVA2", &RT_HPSagainstElectronVLooseMVA2);
    fChain->SetBranchAddress("RT_HPSagainstElectronVTightMVA3", &RT_HPSagainstElectronVTightMVA3);
    fChain->SetBranchAddress("RT_HPSagainstMuonLoose", &RT_HPSagainstMuonLoose);
    fChain->SetBranchAddress("RT_HPSagainstMuonLoose2", &RT_HPSagainstMuonLoose2);
    fChain->SetBranchAddress("RT_HPSagainstMuonMedium", &RT_HPSagainstMuonMedium);
    fChain->SetBranchAddress("RT_HPSagainstMuonMedium2", &RT_HPSagainstMuonMedium2);
    fChain->SetBranchAddress("RT_HPSagainstMuonTight", &RT_HPSagainstMuonTight);
    fChain->SetBranchAddress("RT_HPSagainstMuonTight2", &RT_HPSagainstMuonTight2);
    fChain->SetBranchAddress("RT_HPSbyCombinedIsolationDeltaBetaCorrRaw", &RT_HPSbyCombinedIsolationDeltaBetaCorrRaw);
    fChain->SetBranchAddress("RT_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits", &RT_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits);
    fChain->SetBranchAddress("RT_HPSbyIsolationMVA2raw", &RT_HPSbyIsolationMVA2raw);
    fChain->SetBranchAddress("RT_HPSbyIsolationMVAraw", &RT_HPSbyIsolationMVAraw);
    fChain->SetBranchAddress("RT_HPSbyLooseCombinedIsolationDeltaBetaCorr", &RT_HPSbyLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("RT_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits", &RT_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("RT_HPSbyLooseIsolationMVA", &RT_HPSbyLooseIsolationMVA);
    fChain->SetBranchAddress("RT_HPSbyLooseIsolationMVA2", &RT_HPSbyLooseIsolationMVA2);
    fChain->SetBranchAddress("RT_HPSbyMediumCombinedIsolationDeltaBetaCorr", &RT_HPSbyMediumCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("RT_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits", &RT_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("RT_HPSbyMediumIsolationMVA", &RT_HPSbyMediumIsolationMVA);
    fChain->SetBranchAddress("RT_HPSbyMediumIsolationMVA2", &RT_HPSbyMediumIsolationMVA2);
    fChain->SetBranchAddress("RT_HPSbyTightCombinedIsolationDeltaBetaCorr", &RT_HPSbyTightCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("RT_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits", &RT_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("RT_HPSbyTightIsolationMVA", &RT_HPSbyTightIsolationMVA);
    fChain->SetBranchAddress("RT_HPSbyTightIsolationMVA2", &RT_HPSbyTightIsolationMVA2);
    fChain->SetBranchAddress("RT_HPSbyVLooseCombinedIsolationDeltaBetaCorr", &RT_HPSbyVLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("RT_HPSdecayModeFinding", &RT_HPSdecayModeFinding);
    fChain->SetBranchAddress("RT_IsInTheCracks", &RT_IsInTheCracks);
    fChain->SetBranchAddress("RT_JetCSV", &RT_JetCSV);
    fChain->SetBranchAddress("RT_LTIpVtdxy", &RT_LTIpVtdxy);
    fChain->SetBranchAddress("RT_LTIpVtdxyError", &RT_LTIpVtdxyError);
    fChain->SetBranchAddress("RT_LTIpVtdz", &RT_LTIpVtdz);
    fChain->SetBranchAddress("RT_LTIpVtdzError", &RT_LTIpVtdzError);
    fChain->SetBranchAddress("RT_LTNormChiSqrd", &RT_LTNormChiSqrd);
    fChain->SetBranchAddress("RT_LTPt", &RT_LTPt);
    fChain->SetBranchAddress("RT_LTValidHits", &RT_LTValidHits);
    fChain->SetBranchAddress("RT_LTvalid", &RT_LTvalid);
    fChain->SetBranchAddress("RT_LTvx", &RT_LTvx);
    fChain->SetBranchAddress("RT_LTvy", &RT_LTvy);
    fChain->SetBranchAddress("RT_LTvz", &RT_LTvz);
    fChain->SetBranchAddress("RT_MomentumRank", &RT_MomentumRank);
    fChain->SetBranchAddress("RT_NProngs", &RT_NProngs);
    fChain->SetBranchAddress("RT_NSignalGammas", &RT_NSignalGammas);
    fChain->SetBranchAddress("RT_NSignalNeutrals", &RT_NSignalNeutrals);
    fChain->SetBranchAddress("RT_P", &RT_P);
    fChain->SetBranchAddress("TriggerEventWeight", &TriggerEventWeight);
    fChain->SetBranchAddress("V_NormChiSquared", &V_NormChiSquared);
    fChain->SetBranchAddress("V_NumDOF", &V_NumDOF);
    fChain->SetBranchAddress("V_Rho", &V_Rho);
    fChain->SetBranchAddress("V_Xcoord", &V_Xcoord);
    fChain->SetBranchAddress("V_XcoordErr", &V_XcoordErr);
    fChain->SetBranchAddress("V_Ycoord", &V_Ycoord);
    fChain->SetBranchAddress("V_YcoordErr", &V_YcoordErr);
    fChain->SetBranchAddress("V_Zcoord", &V_Zcoord);
    fChain->SetBranchAddress("V_ZcoordErr", &V_ZcoordErr);
    fChain->SetBranchAddress("bQuarkCount", &bQuarkCount);
    fChain->SetBranchAddress("cQuarkCount", &cQuarkCount);
    fChain->SetBranchAddress("event", &event);
    fChain->SetBranchAddress("higgsDecayMode", &higgsDecayMode);
    fChain->SetBranchAddress("lumi", &lumi);
    fChain->SetBranchAddress("puWeight", &puWeight);
    fChain->SetBranchAddress("puWeightDown", &puWeightDown);
    fChain->SetBranchAddress("puWeightUp", &puWeightUp);
    fChain->SetBranchAddress("q2WeightDown", &q2WeightDown);
    fChain->SetBranchAddress("q2WeightUp", &q2WeightUp);
    fChain->SetBranchAddress("run", &run);
    fChain->SetBranchAddress("topPtWeight", &topPtWeight);
    fChain->SetBranchAddress("topPtWeightDown", &topPtWeightDown);
    fChain->SetBranchAddress("topPtWeightUp", &topPtWeightUp);
    // >>> End address <<<
}
