// vim: ts=4:sw=4:et:sta
#include "../interface/LLBranches.h"

using namespace roast;

void
ll::Branches::Clear()
{
    roast::Branches::Clear();

    // >>> Begin clear <<<
    J_Lepton1DeltaR->clear();
    J_Lepton2DeltaR->clear();
    LL_Lepton1Charge->clear();
    LL_Lepton1CorrectedD0->clear();
    LL_Lepton1CorrectedDZ->clear();
    LL_Lepton1Eta->clear();
    LL_Lepton1EventWeight->clear();
    LL_Lepton1GenMatchDaughter0Id->clear();
    LL_Lepton1GenMatchDaughter0Status->clear();
    LL_Lepton1GenMatchDaughter1Id->clear();
    LL_Lepton1GenMatchDaughter1Status->clear();
    LL_Lepton1GenMatchGrandmother00Id->clear();
    LL_Lepton1GenMatchGrandmother00Status->clear();
    LL_Lepton1GenMatchGrandmother01Id->clear();
    LL_Lepton1GenMatchGrandmother01Status->clear();
    LL_Lepton1GenMatchGrandmother10Id->clear();
    LL_Lepton1GenMatchGrandmother10Status->clear();
    LL_Lepton1GenMatchGrandmother11Id->clear();
    LL_Lepton1GenMatchGrandmother11Status->clear();
    LL_Lepton1GenMatchId->clear();
    LL_Lepton1GenMatchMother0Id->clear();
    LL_Lepton1GenMatchMother0Status->clear();
    LL_Lepton1GenMatchMother1Id->clear();
    LL_Lepton1GenMatchMother1Status->clear();
    LL_Lepton1GenMatchStatus->clear();
    LL_Lepton1ImpactParameter->clear();
    LL_Lepton1IsElectron->clear();
    LL_Lepton1IsLoose->clear();
    LL_Lepton1IsMuon->clear();
    LL_Lepton1IsTight->clear();
    LL_Lepton1Lepton2CosDeltaPhi->clear();
    LL_Lepton1Lepton2DeltaR->clear();
    LL_Lepton1Lepton2VisibleMass->clear();
    LL_Lepton1METCosDeltaPhi->clear();
    LL_Lepton1Mt->clear();
    LL_Lepton1Mt2->clear();
    LL_Lepton1P->clear();
    LL_Lepton1Phi->clear();
    LL_Lepton1Pt->clear();
    LL_Lepton1RelIso->clear();
    LL_Lepton2Charge->clear();
    LL_Lepton2CorrectedD0->clear();
    LL_Lepton2CorrectedDZ->clear();
    LL_Lepton2Eta->clear();
    LL_Lepton2EventWeight->clear();
    LL_Lepton2GenMatchDaughter0Id->clear();
    LL_Lepton2GenMatchDaughter0Status->clear();
    LL_Lepton2GenMatchDaughter1Id->clear();
    LL_Lepton2GenMatchDaughter1Status->clear();
    LL_Lepton2GenMatchGrandmother00Id->clear();
    LL_Lepton2GenMatchGrandmother00Status->clear();
    LL_Lepton2GenMatchGrandmother01Id->clear();
    LL_Lepton2GenMatchGrandmother01Status->clear();
    LL_Lepton2GenMatchGrandmother10Id->clear();
    LL_Lepton2GenMatchGrandmother10Status->clear();
    LL_Lepton2GenMatchGrandmother11Id->clear();
    LL_Lepton2GenMatchGrandmother11Status->clear();
    LL_Lepton2GenMatchId->clear();
    LL_Lepton2GenMatchMother0Id->clear();
    LL_Lepton2GenMatchMother0Status->clear();
    LL_Lepton2GenMatchMother1Id->clear();
    LL_Lepton2GenMatchMother1Status->clear();
    LL_Lepton2GenMatchStatus->clear();
    LL_Lepton2ImpactParameter->clear();
    LL_Lepton2IsElectron->clear();
    LL_Lepton2IsLoose->clear();
    LL_Lepton2IsMuon->clear();
    LL_Lepton2IsTight->clear();
    LL_Lepton2METCosDeltaPhi->clear();
    LL_Lepton2Mt->clear();
    LL_Lepton2Mt2->clear();
    LL_Lepton2P->clear();
    LL_Lepton2Phi->clear();
    LL_Lepton2Pt->clear();
    LL_Lepton2RelIso->clear();
    LL_PassZMask->clear();
    LL_PassZMask2->clear();
    LL_TriggerEventWeight->clear();
    // >>> End clear <<<
}

void
ll::Branches::Delete()
{
    roast::Branches::Delete();

    // >>> Begin delete <<<
    delete J_Lepton1DeltaR;
    delete J_Lepton2DeltaR;
    delete LL_Lepton1Charge;
    delete LL_Lepton1CorrectedD0;
    delete LL_Lepton1CorrectedDZ;
    delete LL_Lepton1Eta;
    delete LL_Lepton1EventWeight;
    delete LL_Lepton1GenMatchDaughter0Id;
    delete LL_Lepton1GenMatchDaughter0Status;
    delete LL_Lepton1GenMatchDaughter1Id;
    delete LL_Lepton1GenMatchDaughter1Status;
    delete LL_Lepton1GenMatchGrandmother00Id;
    delete LL_Lepton1GenMatchGrandmother00Status;
    delete LL_Lepton1GenMatchGrandmother01Id;
    delete LL_Lepton1GenMatchGrandmother01Status;
    delete LL_Lepton1GenMatchGrandmother10Id;
    delete LL_Lepton1GenMatchGrandmother10Status;
    delete LL_Lepton1GenMatchGrandmother11Id;
    delete LL_Lepton1GenMatchGrandmother11Status;
    delete LL_Lepton1GenMatchId;
    delete LL_Lepton1GenMatchMother0Id;
    delete LL_Lepton1GenMatchMother0Status;
    delete LL_Lepton1GenMatchMother1Id;
    delete LL_Lepton1GenMatchMother1Status;
    delete LL_Lepton1GenMatchStatus;
    delete LL_Lepton1ImpactParameter;
    delete LL_Lepton1IsElectron;
    delete LL_Lepton1IsLoose;
    delete LL_Lepton1IsMuon;
    delete LL_Lepton1IsTight;
    delete LL_Lepton1Lepton2CosDeltaPhi;
    delete LL_Lepton1Lepton2DeltaR;
    delete LL_Lepton1Lepton2VisibleMass;
    delete LL_Lepton1METCosDeltaPhi;
    delete LL_Lepton1Mt;
    delete LL_Lepton1Mt2;
    delete LL_Lepton1P;
    delete LL_Lepton1Phi;
    delete LL_Lepton1Pt;
    delete LL_Lepton1RelIso;
    delete LL_Lepton2Charge;
    delete LL_Lepton2CorrectedD0;
    delete LL_Lepton2CorrectedDZ;
    delete LL_Lepton2Eta;
    delete LL_Lepton2EventWeight;
    delete LL_Lepton2GenMatchDaughter0Id;
    delete LL_Lepton2GenMatchDaughter0Status;
    delete LL_Lepton2GenMatchDaughter1Id;
    delete LL_Lepton2GenMatchDaughter1Status;
    delete LL_Lepton2GenMatchGrandmother00Id;
    delete LL_Lepton2GenMatchGrandmother00Status;
    delete LL_Lepton2GenMatchGrandmother01Id;
    delete LL_Lepton2GenMatchGrandmother01Status;
    delete LL_Lepton2GenMatchGrandmother10Id;
    delete LL_Lepton2GenMatchGrandmother10Status;
    delete LL_Lepton2GenMatchGrandmother11Id;
    delete LL_Lepton2GenMatchGrandmother11Status;
    delete LL_Lepton2GenMatchId;
    delete LL_Lepton2GenMatchMother0Id;
    delete LL_Lepton2GenMatchMother0Status;
    delete LL_Lepton2GenMatchMother1Id;
    delete LL_Lepton2GenMatchMother1Status;
    delete LL_Lepton2GenMatchStatus;
    delete LL_Lepton2ImpactParameter;
    delete LL_Lepton2IsElectron;
    delete LL_Lepton2IsLoose;
    delete LL_Lepton2IsMuon;
    delete LL_Lepton2IsTight;
    delete LL_Lepton2METCosDeltaPhi;
    delete LL_Lepton2Mt;
    delete LL_Lepton2Mt2;
    delete LL_Lepton2P;
    delete LL_Lepton2Phi;
    delete LL_Lepton2Pt;
    delete LL_Lepton2RelIso;
    delete LL_PassZMask;
    delete LL_PassZMask2;
    delete LL_TriggerEventWeight;
    // >>> End delete <<<
}

void
ll::Branches::Null()
{
    roast::Branches::Null();

    // >>> Begin null <<<
    J_Lepton1DeltaR = 0;
    J_Lepton2DeltaR = 0;
    LL_Lepton1Charge = 0;
    LL_Lepton1CorrectedD0 = 0;
    LL_Lepton1CorrectedDZ = 0;
    LL_Lepton1Eta = 0;
    LL_Lepton1EventWeight = 0;
    LL_Lepton1GenMatchDaughter0Id = 0;
    LL_Lepton1GenMatchDaughter0Status = 0;
    LL_Lepton1GenMatchDaughter1Id = 0;
    LL_Lepton1GenMatchDaughter1Status = 0;
    LL_Lepton1GenMatchGrandmother00Id = 0;
    LL_Lepton1GenMatchGrandmother00Status = 0;
    LL_Lepton1GenMatchGrandmother01Id = 0;
    LL_Lepton1GenMatchGrandmother01Status = 0;
    LL_Lepton1GenMatchGrandmother10Id = 0;
    LL_Lepton1GenMatchGrandmother10Status = 0;
    LL_Lepton1GenMatchGrandmother11Id = 0;
    LL_Lepton1GenMatchGrandmother11Status = 0;
    LL_Lepton1GenMatchId = 0;
    LL_Lepton1GenMatchMother0Id = 0;
    LL_Lepton1GenMatchMother0Status = 0;
    LL_Lepton1GenMatchMother1Id = 0;
    LL_Lepton1GenMatchMother1Status = 0;
    LL_Lepton1GenMatchStatus = 0;
    LL_Lepton1ImpactParameter = 0;
    LL_Lepton1IsElectron = 0;
    LL_Lepton1IsLoose = 0;
    LL_Lepton1IsMuon = 0;
    LL_Lepton1IsTight = 0;
    LL_Lepton1Lepton2CosDeltaPhi = 0;
    LL_Lepton1Lepton2DeltaR = 0;
    LL_Lepton1Lepton2VisibleMass = 0;
    LL_Lepton1METCosDeltaPhi = 0;
    LL_Lepton1Mt = 0;
    LL_Lepton1Mt2 = 0;
    LL_Lepton1P = 0;
    LL_Lepton1Phi = 0;
    LL_Lepton1Pt = 0;
    LL_Lepton1RelIso = 0;
    LL_Lepton2Charge = 0;
    LL_Lepton2CorrectedD0 = 0;
    LL_Lepton2CorrectedDZ = 0;
    LL_Lepton2Eta = 0;
    LL_Lepton2EventWeight = 0;
    LL_Lepton2GenMatchDaughter0Id = 0;
    LL_Lepton2GenMatchDaughter0Status = 0;
    LL_Lepton2GenMatchDaughter1Id = 0;
    LL_Lepton2GenMatchDaughter1Status = 0;
    LL_Lepton2GenMatchGrandmother00Id = 0;
    LL_Lepton2GenMatchGrandmother00Status = 0;
    LL_Lepton2GenMatchGrandmother01Id = 0;
    LL_Lepton2GenMatchGrandmother01Status = 0;
    LL_Lepton2GenMatchGrandmother10Id = 0;
    LL_Lepton2GenMatchGrandmother10Status = 0;
    LL_Lepton2GenMatchGrandmother11Id = 0;
    LL_Lepton2GenMatchGrandmother11Status = 0;
    LL_Lepton2GenMatchId = 0;
    LL_Lepton2GenMatchMother0Id = 0;
    LL_Lepton2GenMatchMother0Status = 0;
    LL_Lepton2GenMatchMother1Id = 0;
    LL_Lepton2GenMatchMother1Status = 0;
    LL_Lepton2GenMatchStatus = 0;
    LL_Lepton2ImpactParameter = 0;
    LL_Lepton2IsElectron = 0;
    LL_Lepton2IsLoose = 0;
    LL_Lepton2IsMuon = 0;
    LL_Lepton2IsTight = 0;
    LL_Lepton2METCosDeltaPhi = 0;
    LL_Lepton2Mt = 0;
    LL_Lepton2Mt2 = 0;
    LL_Lepton2P = 0;
    LL_Lepton2Phi = 0;
    LL_Lepton2Pt = 0;
    LL_Lepton2RelIso = 0;
    LL_PassZMask = 0;
    LL_PassZMask2 = 0;
    LL_TriggerEventWeight = 0;
    // >>> End null <<<
}

void
ll::Branches::SetBranchAddresses()
{
    roast::Branches::SetBranchAddresses();

    // >>> Begin address <<<
    fChain->SetBranchAddress("J_Lepton1DeltaR", &J_Lepton1DeltaR);
    fChain->SetBranchAddress("J_Lepton2DeltaR", &J_Lepton2DeltaR);
    fChain->SetBranchAddress("LL_CSVeventWeight", &CSVeventWeight);
    fChain->SetBranchAddress("LL_CSVeventWeightCErr1down", &CSVeventWeightCErr1down);
    fChain->SetBranchAddress("LL_CSVeventWeightCErr1up", &CSVeventWeightCErr1up);
    fChain->SetBranchAddress("LL_CSVeventWeightCErr2down", &CSVeventWeightCErr2down);
    fChain->SetBranchAddress("LL_CSVeventWeightCErr2up", &CSVeventWeightCErr2up);
    fChain->SetBranchAddress("LL_CSVeventWeightHFStats1down", &CSVeventWeightHFStats1down);
    fChain->SetBranchAddress("LL_CSVeventWeightHFStats1up", &CSVeventWeightHFStats1up);
    fChain->SetBranchAddress("LL_CSVeventWeightHFStats2down", &CSVeventWeightHFStats2down);
    fChain->SetBranchAddress("LL_CSVeventWeightHFStats2up", &CSVeventWeightHFStats2up);
    fChain->SetBranchAddress("LL_CSVeventWeightHFdown", &CSVeventWeightHFdown);
    fChain->SetBranchAddress("LL_CSVeventWeightHFup", &CSVeventWeightHFup);
    fChain->SetBranchAddress("LL_CSVeventWeightLFStats1down", &CSVeventWeightLFStats1down);
    fChain->SetBranchAddress("LL_CSVeventWeightLFStats1up", &CSVeventWeightLFStats1up);
    fChain->SetBranchAddress("LL_CSVeventWeightLFStats2down", &CSVeventWeightLFStats2down);
    fChain->SetBranchAddress("LL_CSVeventWeightLFStats2up", &CSVeventWeightLFStats2up);
    fChain->SetBranchAddress("LL_CSVeventWeightLFdown", &CSVeventWeightLFdown);
    fChain->SetBranchAddress("LL_CSVeventWeightLFup", &CSVeventWeightLFup);
    fChain->SetBranchAddress("LL_CleanJetCSVMIndices", &CleanJetCSVMIndices);
    fChain->SetBranchAddress("LL_CleanJetIndices", &CleanJetIndices);
    fChain->SetBranchAddress("LL_CleanJetNonCSVMIndices", &CleanJetNonCSVMIndices);
    fChain->SetBranchAddress("LL_HT", &HT);
    fChain->SetBranchAddress("LL_Lepton1Charge", &LL_Lepton1Charge);
    fChain->SetBranchAddress("LL_Lepton1CorrectedD0", &LL_Lepton1CorrectedD0);
    fChain->SetBranchAddress("LL_Lepton1CorrectedDZ", &LL_Lepton1CorrectedDZ);
    fChain->SetBranchAddress("LL_Lepton1Eta", &LL_Lepton1Eta);
    fChain->SetBranchAddress("LL_Lepton1EventWeight", &LL_Lepton1EventWeight);
    fChain->SetBranchAddress("LL_Lepton1GenMatchDaughter0Id", &LL_Lepton1GenMatchDaughter0Id);
    fChain->SetBranchAddress("LL_Lepton1GenMatchDaughter0Status", &LL_Lepton1GenMatchDaughter0Status);
    fChain->SetBranchAddress("LL_Lepton1GenMatchDaughter1Id", &LL_Lepton1GenMatchDaughter1Id);
    fChain->SetBranchAddress("LL_Lepton1GenMatchDaughter1Status", &LL_Lepton1GenMatchDaughter1Status);
    fChain->SetBranchAddress("LL_Lepton1GenMatchGrandmother00Id", &LL_Lepton1GenMatchGrandmother00Id);
    fChain->SetBranchAddress("LL_Lepton1GenMatchGrandmother00Status", &LL_Lepton1GenMatchGrandmother00Status);
    fChain->SetBranchAddress("LL_Lepton1GenMatchGrandmother01Id", &LL_Lepton1GenMatchGrandmother01Id);
    fChain->SetBranchAddress("LL_Lepton1GenMatchGrandmother01Status", &LL_Lepton1GenMatchGrandmother01Status);
    fChain->SetBranchAddress("LL_Lepton1GenMatchGrandmother10Id", &LL_Lepton1GenMatchGrandmother10Id);
    fChain->SetBranchAddress("LL_Lepton1GenMatchGrandmother10Status", &LL_Lepton1GenMatchGrandmother10Status);
    fChain->SetBranchAddress("LL_Lepton1GenMatchGrandmother11Id", &LL_Lepton1GenMatchGrandmother11Id);
    fChain->SetBranchAddress("LL_Lepton1GenMatchGrandmother11Status", &LL_Lepton1GenMatchGrandmother11Status);
    fChain->SetBranchAddress("LL_Lepton1GenMatchId", &LL_Lepton1GenMatchId);
    fChain->SetBranchAddress("LL_Lepton1GenMatchMother0Id", &LL_Lepton1GenMatchMother0Id);
    fChain->SetBranchAddress("LL_Lepton1GenMatchMother0Status", &LL_Lepton1GenMatchMother0Status);
    fChain->SetBranchAddress("LL_Lepton1GenMatchMother1Id", &LL_Lepton1GenMatchMother1Id);
    fChain->SetBranchAddress("LL_Lepton1GenMatchMother1Status", &LL_Lepton1GenMatchMother1Status);
    fChain->SetBranchAddress("LL_Lepton1GenMatchStatus", &LL_Lepton1GenMatchStatus);
    fChain->SetBranchAddress("LL_Lepton1ImpactParameter", &LL_Lepton1ImpactParameter);
    fChain->SetBranchAddress("LL_Lepton1IsElectron", &LL_Lepton1IsElectron);
    fChain->SetBranchAddress("LL_Lepton1IsLoose", &LL_Lepton1IsLoose);
    fChain->SetBranchAddress("LL_Lepton1IsMuon", &LL_Lepton1IsMuon);
    fChain->SetBranchAddress("LL_Lepton1IsTight", &LL_Lepton1IsTight);
    fChain->SetBranchAddress("LL_Lepton1Lepton2CosDeltaPhi", &LL_Lepton1Lepton2CosDeltaPhi);
    fChain->SetBranchAddress("LL_Lepton1Lepton2DeltaR", &LL_Lepton1Lepton2DeltaR);
    fChain->SetBranchAddress("LL_Lepton1Lepton2VisibleMass", &LL_Lepton1Lepton2VisibleMass);
    fChain->SetBranchAddress("LL_Lepton1METCosDeltaPhi", &LL_Lepton1METCosDeltaPhi);
    fChain->SetBranchAddress("LL_Lepton1Mt", &LL_Lepton1Mt);
    fChain->SetBranchAddress("LL_Lepton1Mt2", &LL_Lepton1Mt2);
    fChain->SetBranchAddress("LL_Lepton1P", &LL_Lepton1P);
    fChain->SetBranchAddress("LL_Lepton1Phi", &LL_Lepton1Phi);
    fChain->SetBranchAddress("LL_Lepton1Pt", &LL_Lepton1Pt);
    fChain->SetBranchAddress("LL_Lepton1RelIso", &LL_Lepton1RelIso);
    fChain->SetBranchAddress("LL_Lepton2Charge", &LL_Lepton2Charge);
    fChain->SetBranchAddress("LL_Lepton2CorrectedD0", &LL_Lepton2CorrectedD0);
    fChain->SetBranchAddress("LL_Lepton2CorrectedDZ", &LL_Lepton2CorrectedDZ);
    fChain->SetBranchAddress("LL_Lepton2Eta", &LL_Lepton2Eta);
    fChain->SetBranchAddress("LL_Lepton2EventWeight", &LL_Lepton2EventWeight);
    fChain->SetBranchAddress("LL_Lepton2GenMatchDaughter0Id", &LL_Lepton2GenMatchDaughter0Id);
    fChain->SetBranchAddress("LL_Lepton2GenMatchDaughter0Status", &LL_Lepton2GenMatchDaughter0Status);
    fChain->SetBranchAddress("LL_Lepton2GenMatchDaughter1Id", &LL_Lepton2GenMatchDaughter1Id);
    fChain->SetBranchAddress("LL_Lepton2GenMatchDaughter1Status", &LL_Lepton2GenMatchDaughter1Status);
    fChain->SetBranchAddress("LL_Lepton2GenMatchGrandmother00Id", &LL_Lepton2GenMatchGrandmother00Id);
    fChain->SetBranchAddress("LL_Lepton2GenMatchGrandmother00Status", &LL_Lepton2GenMatchGrandmother00Status);
    fChain->SetBranchAddress("LL_Lepton2GenMatchGrandmother01Id", &LL_Lepton2GenMatchGrandmother01Id);
    fChain->SetBranchAddress("LL_Lepton2GenMatchGrandmother01Status", &LL_Lepton2GenMatchGrandmother01Status);
    fChain->SetBranchAddress("LL_Lepton2GenMatchGrandmother10Id", &LL_Lepton2GenMatchGrandmother10Id);
    fChain->SetBranchAddress("LL_Lepton2GenMatchGrandmother10Status", &LL_Lepton2GenMatchGrandmother10Status);
    fChain->SetBranchAddress("LL_Lepton2GenMatchGrandmother11Id", &LL_Lepton2GenMatchGrandmother11Id);
    fChain->SetBranchAddress("LL_Lepton2GenMatchGrandmother11Status", &LL_Lepton2GenMatchGrandmother11Status);
    fChain->SetBranchAddress("LL_Lepton2GenMatchId", &LL_Lepton2GenMatchId);
    fChain->SetBranchAddress("LL_Lepton2GenMatchMother0Id", &LL_Lepton2GenMatchMother0Id);
    fChain->SetBranchAddress("LL_Lepton2GenMatchMother0Status", &LL_Lepton2GenMatchMother0Status);
    fChain->SetBranchAddress("LL_Lepton2GenMatchMother1Id", &LL_Lepton2GenMatchMother1Id);
    fChain->SetBranchAddress("LL_Lepton2GenMatchMother1Status", &LL_Lepton2GenMatchMother1Status);
    fChain->SetBranchAddress("LL_Lepton2GenMatchStatus", &LL_Lepton2GenMatchStatus);
    fChain->SetBranchAddress("LL_Lepton2ImpactParameter", &LL_Lepton2ImpactParameter);
    fChain->SetBranchAddress("LL_Lepton2IsElectron", &LL_Lepton2IsElectron);
    fChain->SetBranchAddress("LL_Lepton2IsLoose", &LL_Lepton2IsLoose);
    fChain->SetBranchAddress("LL_Lepton2IsMuon", &LL_Lepton2IsMuon);
    fChain->SetBranchAddress("LL_Lepton2IsTight", &LL_Lepton2IsTight);
    fChain->SetBranchAddress("LL_Lepton2METCosDeltaPhi", &LL_Lepton2METCosDeltaPhi);
    fChain->SetBranchAddress("LL_Lepton2Mt", &LL_Lepton2Mt);
    fChain->SetBranchAddress("LL_Lepton2Mt2", &LL_Lepton2Mt2);
    fChain->SetBranchAddress("LL_Lepton2P", &LL_Lepton2P);
    fChain->SetBranchAddress("LL_Lepton2Phi", &LL_Lepton2Phi);
    fChain->SetBranchAddress("LL_Lepton2Pt", &LL_Lepton2Pt);
    fChain->SetBranchAddress("LL_Lepton2RelIso", &LL_Lepton2RelIso);
    fChain->SetBranchAddress("LL_MHT", &MHT);
    fChain->SetBranchAddress("LL_MomentumRank", &MomentumRank);
    fChain->SetBranchAddress("LL_NumCSVLbtagJets", &NumCSVLbtagJets);
    fChain->SetBranchAddress("LL_NumCSVMbtagJets", &NumCSVMbtagJets);
    fChain->SetBranchAddress("LL_NumCSVTbtagJets", &NumCSVTbtagJets);
    fChain->SetBranchAddress("LL_NumCleanCSVLbtagJets", &NumCleanCSVLbtagJets);
    fChain->SetBranchAddress("LL_NumCleanCSVMbtagJets", &NumCleanCSVMbtagJets);
    fChain->SetBranchAddress("LL_NumCleanCSVTbtagJets", &NumCleanCSVTbtagJets);
    fChain->SetBranchAddress("LL_NumCleanNonCSVLbtagJets", &NumCleanNonCSVLbtagJets);
    fChain->SetBranchAddress("LL_NumCleanNonCSVMbtagJets", &NumCleanNonCSVMbtagJets);
    fChain->SetBranchAddress("LL_NumCleanNonCSVTbtagJets", &NumCleanNonCSVTbtagJets);
    fChain->SetBranchAddress("LL_NumCombos", &NumCombos);
    fChain->SetBranchAddress("LL_NumExLooseElectrons", &NumExLooseElectrons);
    fChain->SetBranchAddress("LL_NumExLooseMuons", &NumExLooseMuons);
    fChain->SetBranchAddress("LL_NumLooseElectrons", &NumLooseElectrons);
    fChain->SetBranchAddress("LL_NumLooseMuons", &NumLooseMuons);
    fChain->SetBranchAddress("LL_NumNonCSVLbtagJets", &NumNonCSVLbtagJets);
    fChain->SetBranchAddress("LL_NumNonCSVMbtagJets", &NumNonCSVMbtagJets);
    fChain->SetBranchAddress("LL_NumNonCSVTbtagJets", &NumNonCSVTbtagJets);
    fChain->SetBranchAddress("LL_NumTightElectrons", &NumTightElectrons);
    fChain->SetBranchAddress("LL_NumTightMuons", &NumTightMuons);
    fChain->SetBranchAddress("LL_PassZMask", &LL_PassZMask);
    fChain->SetBranchAddress("LL_PassZMask2", &LL_PassZMask2);
    fChain->SetBranchAddress("LL_TriggerEventWeight", &LL_TriggerEventWeight);
    // >>> End address <<<
}
