// vim: ts=4:sw=4:et:sta
#include "../interface/TLBranches.h"

using namespace roast;

void
tl::Branches::Clear()
{
    roast::Branches::Clear();

    // >>> Begin clear <<<
    Ev_METcov->clear();
    Ev_NTruePV = 0;
    J_LeptonDeltaR->clear();
    TL_LeptonCharge->clear();
    TL_LeptonCorrectedD0->clear();
    TL_LeptonCorrectedDZ->clear();
    TL_LeptonEta->clear();
    TL_LeptonEventWeight->clear();
    TL_LeptonGenMatchDaughter0Id->clear();
    TL_LeptonGenMatchDaughter0Status->clear();
    TL_LeptonGenMatchDaughter1Id->clear();
    TL_LeptonGenMatchDaughter1Status->clear();
    TL_LeptonGenMatchGrandmother00Id->clear();
    TL_LeptonGenMatchGrandmother00Status->clear();
    TL_LeptonGenMatchGrandmother01Id->clear();
    TL_LeptonGenMatchGrandmother01Status->clear();
    TL_LeptonGenMatchGrandmother10Id->clear();
    TL_LeptonGenMatchGrandmother10Status->clear();
    TL_LeptonGenMatchGrandmother11Id->clear();
    TL_LeptonGenMatchGrandmother11Status->clear();
    TL_LeptonGenMatchId->clear();
    TL_LeptonGenMatchMother0Id->clear();
    TL_LeptonGenMatchMother0Status->clear();
    TL_LeptonGenMatchMother1Id->clear();
    TL_LeptonGenMatchMother1Status->clear();
    TL_LeptonGenMatchStatus->clear();
    TL_LeptonImpactParameter->clear();
    TL_LeptonIsElectron->clear();
    TL_LeptonIsLoose->clear();
    TL_LeptonIsMuon->clear();
    TL_LeptonIsTight->clear();
    TL_LeptonMt->clear();
    TL_LeptonMt2->clear();
    TL_LeptonP->clear();
    TL_LeptonPhi->clear();
    TL_LeptonPt->clear();
    TL_LeptonRelIso->clear();
    TL_TauCharge->clear();
    TL_TauDecayMode->clear();
    TL_TauEmFraction->clear();
    TL_TauEta->clear();
    TL_TauGenMatchDaughter0Id->clear();
    TL_TauGenMatchDaughter0Status->clear();
    TL_TauGenMatchDaughter1Id->clear();
    TL_TauGenMatchDaughter1Status->clear();
    TL_TauGenMatchGrandmother00Id->clear();
    TL_TauGenMatchGrandmother00Status->clear();
    TL_TauGenMatchGrandmother01Id->clear();
    TL_TauGenMatchGrandmother01Status->clear();
    TL_TauGenMatchGrandmother10Id->clear();
    TL_TauGenMatchGrandmother10Status->clear();
    TL_TauGenMatchGrandmother11Id->clear();
    TL_TauGenMatchGrandmother11Status->clear();
    TL_TauGenMatchId->clear();
    TL_TauGenMatchMother0Id->clear();
    TL_TauGenMatchMother0Status->clear();
    TL_TauGenMatchMother1Id->clear();
    TL_TauGenMatchMother1Status->clear();
    TL_TauGenMatchStatus->clear();
    TL_TauHPSagainstElectronDeadECAL->clear();
    TL_TauHPSagainstElectronLoose->clear();
    TL_TauHPSagainstElectronLooseMVA2->clear();
    TL_TauHPSagainstElectronLooseMVA3->clear();
    TL_TauHPSagainstElectronMVA->clear();
    TL_TauHPSagainstElectronMVA2category->clear();
    TL_TauHPSagainstElectronMVA2raw->clear();
    TL_TauHPSagainstElectronMVA3category->clear();
    TL_TauHPSagainstElectronMVA3raw->clear();
    TL_TauHPSagainstElectronMedium->clear();
    TL_TauHPSagainstElectronMediumMVA2->clear();
    TL_TauHPSagainstElectronMediumMVA3->clear();
    TL_TauHPSagainstElectronTight->clear();
    TL_TauHPSagainstElectronTightMVA2->clear();
    TL_TauHPSagainstElectronTightMVA3->clear();
    TL_TauHPSagainstElectronVLooseMVA2->clear();
    TL_TauHPSagainstElectronVTightMVA3->clear();
    TL_TauHPSagainstMuonLoose->clear();
    TL_TauHPSagainstMuonLoose2->clear();
    TL_TauHPSagainstMuonMedium->clear();
    TL_TauHPSagainstMuonMedium2->clear();
    TL_TauHPSagainstMuonTight->clear();
    TL_TauHPSagainstMuonTight2->clear();
    TL_TauHPSbyCombinedIsolationDeltaBetaCorrRaw->clear();
    TL_TauHPSbyCombinedIsolationDeltaBetaCorrRaw3Hits->clear();
    TL_TauHPSbyIsolationMVA2raw->clear();
    TL_TauHPSbyIsolationMVAraw->clear();
    TL_TauHPSbyLooseCombinedIsolationDeltaBetaCorr->clear();
    TL_TauHPSbyLooseCombinedIsolationDeltaBetaCorr3Hits->clear();
    TL_TauHPSbyLooseIsolationMVA->clear();
    TL_TauHPSbyLooseIsolationMVA2->clear();
    TL_TauHPSbyMediumCombinedIsolationDeltaBetaCorr->clear();
    TL_TauHPSbyMediumCombinedIsolationDeltaBetaCorr3Hits->clear();
    TL_TauHPSbyMediumIsolationMVA->clear();
    TL_TauHPSbyMediumIsolationMVA2->clear();
    TL_TauHPSbyTightCombinedIsolationDeltaBetaCorr->clear();
    TL_TauHPSbyTightCombinedIsolationDeltaBetaCorr3Hits->clear();
    TL_TauHPSbyTightIsolationMVA->clear();
    TL_TauHPSbyTightIsolationMVA2->clear();
    TL_TauHPSbyVLooseCombinedIsolationDeltaBetaCorr->clear();
    TL_TauHPSdecayModeFinding->clear();
    TL_TauIsInTheCracks->clear();
    TL_TauLTIpVtdxy->clear();
    TL_TauLTIpVtdxyError->clear();
    TL_TauLTIpVtdz->clear();
    TL_TauLTIpVtdzError->clear();
    TL_TauLTNormChiSqrd->clear();
    TL_TauLTPt->clear();
    TL_TauLTValidHits->clear();
    TL_TauLTvalid->clear();
    TL_TauLTvx->clear();
    TL_TauLTvy->clear();
    TL_TauLTvz->clear();
    TL_TauLeptonCosDeltaPhi->clear();
    TL_TauLeptonDeltaR->clear();
    TL_TauLeptonMETMass->clear();
    TL_TauLeptonVisibleMass->clear();
    TL_TauMomentumRank->clear();
    TL_TauNProngs->clear();
    TL_TauNSignalGammas->clear();
    TL_TauNSignalNeutrals->clear();
    TL_TauP->clear();
    TL_TauPhi->clear();
    TL_TauPt->clear();
    TL_TriggerEventWeight->clear();
    // >>> End clear <<<
}

void
tl::Branches::Delete()
{
    roast::Branches::Delete();

    // >>> Begin delete <<<
    delete Ev_METcov;
    delete J_LeptonDeltaR;
    delete TL_LeptonCharge;
    delete TL_LeptonCorrectedD0;
    delete TL_LeptonCorrectedDZ;
    delete TL_LeptonEta;
    delete TL_LeptonEventWeight;
    delete TL_LeptonGenMatchDaughter0Id;
    delete TL_LeptonGenMatchDaughter0Status;
    delete TL_LeptonGenMatchDaughter1Id;
    delete TL_LeptonGenMatchDaughter1Status;
    delete TL_LeptonGenMatchGrandmother00Id;
    delete TL_LeptonGenMatchGrandmother00Status;
    delete TL_LeptonGenMatchGrandmother01Id;
    delete TL_LeptonGenMatchGrandmother01Status;
    delete TL_LeptonGenMatchGrandmother10Id;
    delete TL_LeptonGenMatchGrandmother10Status;
    delete TL_LeptonGenMatchGrandmother11Id;
    delete TL_LeptonGenMatchGrandmother11Status;
    delete TL_LeptonGenMatchId;
    delete TL_LeptonGenMatchMother0Id;
    delete TL_LeptonGenMatchMother0Status;
    delete TL_LeptonGenMatchMother1Id;
    delete TL_LeptonGenMatchMother1Status;
    delete TL_LeptonGenMatchStatus;
    delete TL_LeptonImpactParameter;
    delete TL_LeptonIsElectron;
    delete TL_LeptonIsLoose;
    delete TL_LeptonIsMuon;
    delete TL_LeptonIsTight;
    delete TL_LeptonMt;
    delete TL_LeptonMt2;
    delete TL_LeptonP;
    delete TL_LeptonPhi;
    delete TL_LeptonPt;
    delete TL_LeptonRelIso;
    delete TL_TauCharge;
    delete TL_TauDecayMode;
    delete TL_TauEmFraction;
    delete TL_TauEta;
    delete TL_TauGenMatchDaughter0Id;
    delete TL_TauGenMatchDaughter0Status;
    delete TL_TauGenMatchDaughter1Id;
    delete TL_TauGenMatchDaughter1Status;
    delete TL_TauGenMatchGrandmother00Id;
    delete TL_TauGenMatchGrandmother00Status;
    delete TL_TauGenMatchGrandmother01Id;
    delete TL_TauGenMatchGrandmother01Status;
    delete TL_TauGenMatchGrandmother10Id;
    delete TL_TauGenMatchGrandmother10Status;
    delete TL_TauGenMatchGrandmother11Id;
    delete TL_TauGenMatchGrandmother11Status;
    delete TL_TauGenMatchId;
    delete TL_TauGenMatchMother0Id;
    delete TL_TauGenMatchMother0Status;
    delete TL_TauGenMatchMother1Id;
    delete TL_TauGenMatchMother1Status;
    delete TL_TauGenMatchStatus;
    delete TL_TauHPSagainstElectronDeadECAL;
    delete TL_TauHPSagainstElectronLoose;
    delete TL_TauHPSagainstElectronLooseMVA2;
    delete TL_TauHPSagainstElectronLooseMVA3;
    delete TL_TauHPSagainstElectronMVA;
    delete TL_TauHPSagainstElectronMVA2category;
    delete TL_TauHPSagainstElectronMVA2raw;
    delete TL_TauHPSagainstElectronMVA3category;
    delete TL_TauHPSagainstElectronMVA3raw;
    delete TL_TauHPSagainstElectronMedium;
    delete TL_TauHPSagainstElectronMediumMVA2;
    delete TL_TauHPSagainstElectronMediumMVA3;
    delete TL_TauHPSagainstElectronTight;
    delete TL_TauHPSagainstElectronTightMVA2;
    delete TL_TauHPSagainstElectronTightMVA3;
    delete TL_TauHPSagainstElectronVLooseMVA2;
    delete TL_TauHPSagainstElectronVTightMVA3;
    delete TL_TauHPSagainstMuonLoose;
    delete TL_TauHPSagainstMuonLoose2;
    delete TL_TauHPSagainstMuonMedium;
    delete TL_TauHPSagainstMuonMedium2;
    delete TL_TauHPSagainstMuonTight;
    delete TL_TauHPSagainstMuonTight2;
    delete TL_TauHPSbyCombinedIsolationDeltaBetaCorrRaw;
    delete TL_TauHPSbyCombinedIsolationDeltaBetaCorrRaw3Hits;
    delete TL_TauHPSbyIsolationMVA2raw;
    delete TL_TauHPSbyIsolationMVAraw;
    delete TL_TauHPSbyLooseCombinedIsolationDeltaBetaCorr;
    delete TL_TauHPSbyLooseCombinedIsolationDeltaBetaCorr3Hits;
    delete TL_TauHPSbyLooseIsolationMVA;
    delete TL_TauHPSbyLooseIsolationMVA2;
    delete TL_TauHPSbyMediumCombinedIsolationDeltaBetaCorr;
    delete TL_TauHPSbyMediumCombinedIsolationDeltaBetaCorr3Hits;
    delete TL_TauHPSbyMediumIsolationMVA;
    delete TL_TauHPSbyMediumIsolationMVA2;
    delete TL_TauHPSbyTightCombinedIsolationDeltaBetaCorr;
    delete TL_TauHPSbyTightCombinedIsolationDeltaBetaCorr3Hits;
    delete TL_TauHPSbyTightIsolationMVA;
    delete TL_TauHPSbyTightIsolationMVA2;
    delete TL_TauHPSbyVLooseCombinedIsolationDeltaBetaCorr;
    delete TL_TauHPSdecayModeFinding;
    delete TL_TauIsInTheCracks;
    delete TL_TauLTIpVtdxy;
    delete TL_TauLTIpVtdxyError;
    delete TL_TauLTIpVtdz;
    delete TL_TauLTIpVtdzError;
    delete TL_TauLTNormChiSqrd;
    delete TL_TauLTPt;
    delete TL_TauLTValidHits;
    delete TL_TauLTvalid;
    delete TL_TauLTvx;
    delete TL_TauLTvy;
    delete TL_TauLTvz;
    delete TL_TauLeptonCosDeltaPhi;
    delete TL_TauLeptonDeltaR;
    delete TL_TauLeptonMETMass;
    delete TL_TauLeptonVisibleMass;
    delete TL_TauMomentumRank;
    delete TL_TauNProngs;
    delete TL_TauNSignalGammas;
    delete TL_TauNSignalNeutrals;
    delete TL_TauP;
    delete TL_TauPhi;
    delete TL_TauPt;
    delete TL_TriggerEventWeight;
    // >>> End delete <<<
}

void
tl::Branches::Null()
{
    roast::Branches::Null();

    // >>> Begin null <<<
    Ev_METcov = 0;
    Ev_NTruePV = 0;
    J_LeptonDeltaR = 0;
    TL_LeptonCharge = 0;
    TL_LeptonCorrectedD0 = 0;
    TL_LeptonCorrectedDZ = 0;
    TL_LeptonEta = 0;
    TL_LeptonEventWeight = 0;
    TL_LeptonGenMatchDaughter0Id = 0;
    TL_LeptonGenMatchDaughter0Status = 0;
    TL_LeptonGenMatchDaughter1Id = 0;
    TL_LeptonGenMatchDaughter1Status = 0;
    TL_LeptonGenMatchGrandmother00Id = 0;
    TL_LeptonGenMatchGrandmother00Status = 0;
    TL_LeptonGenMatchGrandmother01Id = 0;
    TL_LeptonGenMatchGrandmother01Status = 0;
    TL_LeptonGenMatchGrandmother10Id = 0;
    TL_LeptonGenMatchGrandmother10Status = 0;
    TL_LeptonGenMatchGrandmother11Id = 0;
    TL_LeptonGenMatchGrandmother11Status = 0;
    TL_LeptonGenMatchId = 0;
    TL_LeptonGenMatchMother0Id = 0;
    TL_LeptonGenMatchMother0Status = 0;
    TL_LeptonGenMatchMother1Id = 0;
    TL_LeptonGenMatchMother1Status = 0;
    TL_LeptonGenMatchStatus = 0;
    TL_LeptonImpactParameter = 0;
    TL_LeptonIsElectron = 0;
    TL_LeptonIsLoose = 0;
    TL_LeptonIsMuon = 0;
    TL_LeptonIsTight = 0;
    TL_LeptonMt = 0;
    TL_LeptonMt2 = 0;
    TL_LeptonP = 0;
    TL_LeptonPhi = 0;
    TL_LeptonPt = 0;
    TL_LeptonRelIso = 0;
    TL_TauCharge = 0;
    TL_TauDecayMode = 0;
    TL_TauEmFraction = 0;
    TL_TauEta = 0;
    TL_TauGenMatchDaughter0Id = 0;
    TL_TauGenMatchDaughter0Status = 0;
    TL_TauGenMatchDaughter1Id = 0;
    TL_TauGenMatchDaughter1Status = 0;
    TL_TauGenMatchGrandmother00Id = 0;
    TL_TauGenMatchGrandmother00Status = 0;
    TL_TauGenMatchGrandmother01Id = 0;
    TL_TauGenMatchGrandmother01Status = 0;
    TL_TauGenMatchGrandmother10Id = 0;
    TL_TauGenMatchGrandmother10Status = 0;
    TL_TauGenMatchGrandmother11Id = 0;
    TL_TauGenMatchGrandmother11Status = 0;
    TL_TauGenMatchId = 0;
    TL_TauGenMatchMother0Id = 0;
    TL_TauGenMatchMother0Status = 0;
    TL_TauGenMatchMother1Id = 0;
    TL_TauGenMatchMother1Status = 0;
    TL_TauGenMatchStatus = 0;
    TL_TauHPSagainstElectronDeadECAL = 0;
    TL_TauHPSagainstElectronLoose = 0;
    TL_TauHPSagainstElectronLooseMVA2 = 0;
    TL_TauHPSagainstElectronLooseMVA3 = 0;
    TL_TauHPSagainstElectronMVA = 0;
    TL_TauHPSagainstElectronMVA2category = 0;
    TL_TauHPSagainstElectronMVA2raw = 0;
    TL_TauHPSagainstElectronMVA3category = 0;
    TL_TauHPSagainstElectronMVA3raw = 0;
    TL_TauHPSagainstElectronMedium = 0;
    TL_TauHPSagainstElectronMediumMVA2 = 0;
    TL_TauHPSagainstElectronMediumMVA3 = 0;
    TL_TauHPSagainstElectronTight = 0;
    TL_TauHPSagainstElectronTightMVA2 = 0;
    TL_TauHPSagainstElectronTightMVA3 = 0;
    TL_TauHPSagainstElectronVLooseMVA2 = 0;
    TL_TauHPSagainstElectronVTightMVA3 = 0;
    TL_TauHPSagainstMuonLoose = 0;
    TL_TauHPSagainstMuonLoose2 = 0;
    TL_TauHPSagainstMuonMedium = 0;
    TL_TauHPSagainstMuonMedium2 = 0;
    TL_TauHPSagainstMuonTight = 0;
    TL_TauHPSagainstMuonTight2 = 0;
    TL_TauHPSbyCombinedIsolationDeltaBetaCorrRaw = 0;
    TL_TauHPSbyCombinedIsolationDeltaBetaCorrRaw3Hits = 0;
    TL_TauHPSbyIsolationMVA2raw = 0;
    TL_TauHPSbyIsolationMVAraw = 0;
    TL_TauHPSbyLooseCombinedIsolationDeltaBetaCorr = 0;
    TL_TauHPSbyLooseCombinedIsolationDeltaBetaCorr3Hits = 0;
    TL_TauHPSbyLooseIsolationMVA = 0;
    TL_TauHPSbyLooseIsolationMVA2 = 0;
    TL_TauHPSbyMediumCombinedIsolationDeltaBetaCorr = 0;
    TL_TauHPSbyMediumCombinedIsolationDeltaBetaCorr3Hits = 0;
    TL_TauHPSbyMediumIsolationMVA = 0;
    TL_TauHPSbyMediumIsolationMVA2 = 0;
    TL_TauHPSbyTightCombinedIsolationDeltaBetaCorr = 0;
    TL_TauHPSbyTightCombinedIsolationDeltaBetaCorr3Hits = 0;
    TL_TauHPSbyTightIsolationMVA = 0;
    TL_TauHPSbyTightIsolationMVA2 = 0;
    TL_TauHPSbyVLooseCombinedIsolationDeltaBetaCorr = 0;
    TL_TauHPSdecayModeFinding = 0;
    TL_TauIsInTheCracks = 0;
    TL_TauLTIpVtdxy = 0;
    TL_TauLTIpVtdxyError = 0;
    TL_TauLTIpVtdz = 0;
    TL_TauLTIpVtdzError = 0;
    TL_TauLTNormChiSqrd = 0;
    TL_TauLTPt = 0;
    TL_TauLTValidHits = 0;
    TL_TauLTvalid = 0;
    TL_TauLTvx = 0;
    TL_TauLTvy = 0;
    TL_TauLTvz = 0;
    TL_TauLeptonCosDeltaPhi = 0;
    TL_TauLeptonDeltaR = 0;
    TL_TauLeptonMETMass = 0;
    TL_TauLeptonVisibleMass = 0;
    TL_TauMomentumRank = 0;
    TL_TauNProngs = 0;
    TL_TauNSignalGammas = 0;
    TL_TauNSignalNeutrals = 0;
    TL_TauP = 0;
    TL_TauPhi = 0;
    TL_TauPt = 0;
    TL_TriggerEventWeight = 0;
    // >>> End null <<<
}

void
tl::Branches::SetBranchAddresses()
{
    roast::Branches::SetBranchAddresses();

    // >>> Begin address <<<
    fChain->SetBranchAddress("Ev_METcov", &Ev_METcov);
    fChain->SetBranchAddress("Ev_NTruePV", &Ev_NTruePV);
    fChain->SetBranchAddress("J_LeptonDeltaR", &J_LeptonDeltaR);
    fChain->SetBranchAddress("TL_CSVeventWeight", &CSVeventWeight);
    fChain->SetBranchAddress("TL_CSVeventWeightCErr1down", &CSVeventWeightCErr1down);
    fChain->SetBranchAddress("TL_CSVeventWeightCErr1up", &CSVeventWeightCErr1up);
    fChain->SetBranchAddress("TL_CSVeventWeightCErr2down", &CSVeventWeightCErr2down);
    fChain->SetBranchAddress("TL_CSVeventWeightCErr2up", &CSVeventWeightCErr2up);
    fChain->SetBranchAddress("TL_CSVeventWeightHFStats1down", &CSVeventWeightHFStats1down);
    fChain->SetBranchAddress("TL_CSVeventWeightHFStats1up", &CSVeventWeightHFStats1up);
    fChain->SetBranchAddress("TL_CSVeventWeightHFStats2down", &CSVeventWeightHFStats2down);
    fChain->SetBranchAddress("TL_CSVeventWeightHFStats2up", &CSVeventWeightHFStats2up);
    fChain->SetBranchAddress("TL_CSVeventWeightHFdown", &CSVeventWeightHFdown);
    fChain->SetBranchAddress("TL_CSVeventWeightHFup", &CSVeventWeightHFup);
    fChain->SetBranchAddress("TL_CSVeventWeightLFStats1down", &CSVeventWeightLFStats1down);
    fChain->SetBranchAddress("TL_CSVeventWeightLFStats1up", &CSVeventWeightLFStats1up);
    fChain->SetBranchAddress("TL_CSVeventWeightLFStats2down", &CSVeventWeightLFStats2down);
    fChain->SetBranchAddress("TL_CSVeventWeightLFStats2up", &CSVeventWeightLFStats2up);
    fChain->SetBranchAddress("TL_CSVeventWeightLFdown", &CSVeventWeightLFdown);
    fChain->SetBranchAddress("TL_CSVeventWeightLFup", &CSVeventWeightLFup);
    fChain->SetBranchAddress("TL_CleanJetCSVMIndices", &CleanJetCSVMIndices);
    fChain->SetBranchAddress("TL_CleanJetIndices", &CleanJetIndices);
    fChain->SetBranchAddress("TL_CleanJetNonCSVMIndices", &CleanJetNonCSVMIndices);
    fChain->SetBranchAddress("TL_HT", &HT);
    fChain->SetBranchAddress("TL_LeptonCharge", &TL_LeptonCharge);
    fChain->SetBranchAddress("TL_LeptonCorrectedD0", &TL_LeptonCorrectedD0);
    fChain->SetBranchAddress("TL_LeptonCorrectedDZ", &TL_LeptonCorrectedDZ);
    fChain->SetBranchAddress("TL_LeptonEta", &TL_LeptonEta);
    fChain->SetBranchAddress("TL_LeptonEventWeight", &TL_LeptonEventWeight);
    fChain->SetBranchAddress("TL_LeptonGenMatchDaughter0Id", &TL_LeptonGenMatchDaughter0Id);
    fChain->SetBranchAddress("TL_LeptonGenMatchDaughter0Status", &TL_LeptonGenMatchDaughter0Status);
    fChain->SetBranchAddress("TL_LeptonGenMatchDaughter1Id", &TL_LeptonGenMatchDaughter1Id);
    fChain->SetBranchAddress("TL_LeptonGenMatchDaughter1Status", &TL_LeptonGenMatchDaughter1Status);
    fChain->SetBranchAddress("TL_LeptonGenMatchGrandmother00Id", &TL_LeptonGenMatchGrandmother00Id);
    fChain->SetBranchAddress("TL_LeptonGenMatchGrandmother00Status", &TL_LeptonGenMatchGrandmother00Status);
    fChain->SetBranchAddress("TL_LeptonGenMatchGrandmother01Id", &TL_LeptonGenMatchGrandmother01Id);
    fChain->SetBranchAddress("TL_LeptonGenMatchGrandmother01Status", &TL_LeptonGenMatchGrandmother01Status);
    fChain->SetBranchAddress("TL_LeptonGenMatchGrandmother10Id", &TL_LeptonGenMatchGrandmother10Id);
    fChain->SetBranchAddress("TL_LeptonGenMatchGrandmother10Status", &TL_LeptonGenMatchGrandmother10Status);
    fChain->SetBranchAddress("TL_LeptonGenMatchGrandmother11Id", &TL_LeptonGenMatchGrandmother11Id);
    fChain->SetBranchAddress("TL_LeptonGenMatchGrandmother11Status", &TL_LeptonGenMatchGrandmother11Status);
    fChain->SetBranchAddress("TL_LeptonGenMatchId", &TL_LeptonGenMatchId);
    fChain->SetBranchAddress("TL_LeptonGenMatchMother0Id", &TL_LeptonGenMatchMother0Id);
    fChain->SetBranchAddress("TL_LeptonGenMatchMother0Status", &TL_LeptonGenMatchMother0Status);
    fChain->SetBranchAddress("TL_LeptonGenMatchMother1Id", &TL_LeptonGenMatchMother1Id);
    fChain->SetBranchAddress("TL_LeptonGenMatchMother1Status", &TL_LeptonGenMatchMother1Status);
    fChain->SetBranchAddress("TL_LeptonGenMatchStatus", &TL_LeptonGenMatchStatus);
    fChain->SetBranchAddress("TL_LeptonImpactParameter", &TL_LeptonImpactParameter);
    fChain->SetBranchAddress("TL_LeptonIsElectron", &TL_LeptonIsElectron);
    fChain->SetBranchAddress("TL_LeptonIsLoose", &TL_LeptonIsLoose);
    fChain->SetBranchAddress("TL_LeptonIsMuon", &TL_LeptonIsMuon);
    fChain->SetBranchAddress("TL_LeptonIsTight", &TL_LeptonIsTight);
    fChain->SetBranchAddress("TL_LeptonMt", &TL_LeptonMt);
    fChain->SetBranchAddress("TL_LeptonMt2", &TL_LeptonMt2);
    fChain->SetBranchAddress("TL_LeptonP", &TL_LeptonP);
    fChain->SetBranchAddress("TL_LeptonPhi", &TL_LeptonPhi);
    fChain->SetBranchAddress("TL_LeptonPt", &TL_LeptonPt);
    fChain->SetBranchAddress("TL_LeptonRelIso", &TL_LeptonRelIso);
    fChain->SetBranchAddress("TL_MHT", &MHT);
    fChain->SetBranchAddress("TL_MomentumRank", &MomentumRank);
    fChain->SetBranchAddress("TL_NumCSVLbtagJets", &NumCSVLbtagJets);
    fChain->SetBranchAddress("TL_NumCSVMbtagJets", &NumCSVMbtagJets);
    fChain->SetBranchAddress("TL_NumCSVTbtagJets", &NumCSVTbtagJets);
    fChain->SetBranchAddress("TL_NumCleanCSVLbtagJets", &NumCleanCSVLbtagJets);
    fChain->SetBranchAddress("TL_NumCleanCSVMbtagJets", &NumCleanCSVMbtagJets);
    fChain->SetBranchAddress("TL_NumCleanCSVTbtagJets", &NumCleanCSVTbtagJets);
    fChain->SetBranchAddress("TL_NumCleanNonCSVLbtagJets", &NumCleanNonCSVLbtagJets);
    fChain->SetBranchAddress("TL_NumCleanNonCSVMbtagJets", &NumCleanNonCSVMbtagJets);
    fChain->SetBranchAddress("TL_NumCleanNonCSVTbtagJets", &NumCleanNonCSVTbtagJets);
    fChain->SetBranchAddress("TL_NumCombos", &NumCombos);
    fChain->SetBranchAddress("TL_NumExLooseElectrons", &NumExLooseElectrons);
    fChain->SetBranchAddress("TL_NumExLooseMuons", &NumExLooseMuons);
    fChain->SetBranchAddress("TL_NumLooseElectrons", &NumLooseElectrons);
    fChain->SetBranchAddress("TL_NumLooseMuons", &NumLooseMuons);
    fChain->SetBranchAddress("TL_NumNonCSVLbtagJets", &NumNonCSVLbtagJets);
    fChain->SetBranchAddress("TL_NumNonCSVMbtagJets", &NumNonCSVMbtagJets);
    fChain->SetBranchAddress("TL_NumNonCSVTbtagJets", &NumNonCSVTbtagJets);
    fChain->SetBranchAddress("TL_NumTaus", &NumTaus);
    fChain->SetBranchAddress("TL_NumTightElectrons", &NumTightElectrons);
    fChain->SetBranchAddress("TL_NumTightMuons", &NumTightMuons);
    fChain->SetBranchAddress("TL_TauCharge", &TL_TauCharge);
    fChain->SetBranchAddress("TL_TauDecayMode", &TL_TauDecayMode);
    fChain->SetBranchAddress("TL_TauEmFraction", &TL_TauEmFraction);
    fChain->SetBranchAddress("TL_TauEta", &TL_TauEta);
    fChain->SetBranchAddress("TL_TauGenMatchDaughter0Id", &TL_TauGenMatchDaughter0Id);
    fChain->SetBranchAddress("TL_TauGenMatchDaughter0Status", &TL_TauGenMatchDaughter0Status);
    fChain->SetBranchAddress("TL_TauGenMatchDaughter1Id", &TL_TauGenMatchDaughter1Id);
    fChain->SetBranchAddress("TL_TauGenMatchDaughter1Status", &TL_TauGenMatchDaughter1Status);
    fChain->SetBranchAddress("TL_TauGenMatchGrandmother00Id", &TL_TauGenMatchGrandmother00Id);
    fChain->SetBranchAddress("TL_TauGenMatchGrandmother00Status", &TL_TauGenMatchGrandmother00Status);
    fChain->SetBranchAddress("TL_TauGenMatchGrandmother01Id", &TL_TauGenMatchGrandmother01Id);
    fChain->SetBranchAddress("TL_TauGenMatchGrandmother01Status", &TL_TauGenMatchGrandmother01Status);
    fChain->SetBranchAddress("TL_TauGenMatchGrandmother10Id", &TL_TauGenMatchGrandmother10Id);
    fChain->SetBranchAddress("TL_TauGenMatchGrandmother10Status", &TL_TauGenMatchGrandmother10Status);
    fChain->SetBranchAddress("TL_TauGenMatchGrandmother11Id", &TL_TauGenMatchGrandmother11Id);
    fChain->SetBranchAddress("TL_TauGenMatchGrandmother11Status", &TL_TauGenMatchGrandmother11Status);
    fChain->SetBranchAddress("TL_TauGenMatchId", &TL_TauGenMatchId);
    fChain->SetBranchAddress("TL_TauGenMatchMother0Id", &TL_TauGenMatchMother0Id);
    fChain->SetBranchAddress("TL_TauGenMatchMother0Status", &TL_TauGenMatchMother0Status);
    fChain->SetBranchAddress("TL_TauGenMatchMother1Id", &TL_TauGenMatchMother1Id);
    fChain->SetBranchAddress("TL_TauGenMatchMother1Status", &TL_TauGenMatchMother1Status);
    fChain->SetBranchAddress("TL_TauGenMatchStatus", &TL_TauGenMatchStatus);
    fChain->SetBranchAddress("TL_TauHPSagainstElectronDeadECAL", &TL_TauHPSagainstElectronDeadECAL);
    fChain->SetBranchAddress("TL_TauHPSagainstElectronLoose", &TL_TauHPSagainstElectronLoose);
    fChain->SetBranchAddress("TL_TauHPSagainstElectronLooseMVA2", &TL_TauHPSagainstElectronLooseMVA2);
    fChain->SetBranchAddress("TL_TauHPSagainstElectronLooseMVA3", &TL_TauHPSagainstElectronLooseMVA3);
    fChain->SetBranchAddress("TL_TauHPSagainstElectronMVA", &TL_TauHPSagainstElectronMVA);
    fChain->SetBranchAddress("TL_TauHPSagainstElectronMVA2category", &TL_TauHPSagainstElectronMVA2category);
    fChain->SetBranchAddress("TL_TauHPSagainstElectronMVA2raw", &TL_TauHPSagainstElectronMVA2raw);
    fChain->SetBranchAddress("TL_TauHPSagainstElectronMVA3category", &TL_TauHPSagainstElectronMVA3category);
    fChain->SetBranchAddress("TL_TauHPSagainstElectronMVA3raw", &TL_TauHPSagainstElectronMVA3raw);
    fChain->SetBranchAddress("TL_TauHPSagainstElectronMedium", &TL_TauHPSagainstElectronMedium);
    fChain->SetBranchAddress("TL_TauHPSagainstElectronMediumMVA2", &TL_TauHPSagainstElectronMediumMVA2);
    fChain->SetBranchAddress("TL_TauHPSagainstElectronMediumMVA3", &TL_TauHPSagainstElectronMediumMVA3);
    fChain->SetBranchAddress("TL_TauHPSagainstElectronTight", &TL_TauHPSagainstElectronTight);
    fChain->SetBranchAddress("TL_TauHPSagainstElectronTightMVA2", &TL_TauHPSagainstElectronTightMVA2);
    fChain->SetBranchAddress("TL_TauHPSagainstElectronTightMVA3", &TL_TauHPSagainstElectronTightMVA3);
    fChain->SetBranchAddress("TL_TauHPSagainstElectronVLooseMVA2", &TL_TauHPSagainstElectronVLooseMVA2);
    fChain->SetBranchAddress("TL_TauHPSagainstElectronVTightMVA3", &TL_TauHPSagainstElectronVTightMVA3);
    fChain->SetBranchAddress("TL_TauHPSagainstMuonLoose", &TL_TauHPSagainstMuonLoose);
    fChain->SetBranchAddress("TL_TauHPSagainstMuonLoose2", &TL_TauHPSagainstMuonLoose2);
    fChain->SetBranchAddress("TL_TauHPSagainstMuonMedium", &TL_TauHPSagainstMuonMedium);
    fChain->SetBranchAddress("TL_TauHPSagainstMuonMedium2", &TL_TauHPSagainstMuonMedium2);
    fChain->SetBranchAddress("TL_TauHPSagainstMuonTight", &TL_TauHPSagainstMuonTight);
    fChain->SetBranchAddress("TL_TauHPSagainstMuonTight2", &TL_TauHPSagainstMuonTight2);
    fChain->SetBranchAddress("TL_TauHPSbyCombinedIsolationDeltaBetaCorrRaw", &TL_TauHPSbyCombinedIsolationDeltaBetaCorrRaw);
    fChain->SetBranchAddress("TL_TauHPSbyCombinedIsolationDeltaBetaCorrRaw3Hits", &TL_TauHPSbyCombinedIsolationDeltaBetaCorrRaw3Hits);
    fChain->SetBranchAddress("TL_TauHPSbyIsolationMVA2raw", &TL_TauHPSbyIsolationMVA2raw);
    fChain->SetBranchAddress("TL_TauHPSbyIsolationMVAraw", &TL_TauHPSbyIsolationMVAraw);
    fChain->SetBranchAddress("TL_TauHPSbyLooseCombinedIsolationDeltaBetaCorr", &TL_TauHPSbyLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TL_TauHPSbyLooseCombinedIsolationDeltaBetaCorr3Hits", &TL_TauHPSbyLooseCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("TL_TauHPSbyLooseIsolationMVA", &TL_TauHPSbyLooseIsolationMVA);
    fChain->SetBranchAddress("TL_TauHPSbyLooseIsolationMVA2", &TL_TauHPSbyLooseIsolationMVA2);
    fChain->SetBranchAddress("TL_TauHPSbyMediumCombinedIsolationDeltaBetaCorr", &TL_TauHPSbyMediumCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TL_TauHPSbyMediumCombinedIsolationDeltaBetaCorr3Hits", &TL_TauHPSbyMediumCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("TL_TauHPSbyMediumIsolationMVA", &TL_TauHPSbyMediumIsolationMVA);
    fChain->SetBranchAddress("TL_TauHPSbyMediumIsolationMVA2", &TL_TauHPSbyMediumIsolationMVA2);
    fChain->SetBranchAddress("TL_TauHPSbyTightCombinedIsolationDeltaBetaCorr", &TL_TauHPSbyTightCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TL_TauHPSbyTightCombinedIsolationDeltaBetaCorr3Hits", &TL_TauHPSbyTightCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("TL_TauHPSbyTightIsolationMVA", &TL_TauHPSbyTightIsolationMVA);
    fChain->SetBranchAddress("TL_TauHPSbyTightIsolationMVA2", &TL_TauHPSbyTightIsolationMVA2);
    fChain->SetBranchAddress("TL_TauHPSbyVLooseCombinedIsolationDeltaBetaCorr", &TL_TauHPSbyVLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TL_TauHPSdecayModeFinding", &TL_TauHPSdecayModeFinding);
    fChain->SetBranchAddress("TL_TauIsInTheCracks", &TL_TauIsInTheCracks);
    fChain->SetBranchAddress("TL_TauLTIpVtdxy", &TL_TauLTIpVtdxy);
    fChain->SetBranchAddress("TL_TauLTIpVtdxyError", &TL_TauLTIpVtdxyError);
    fChain->SetBranchAddress("TL_TauLTIpVtdz", &TL_TauLTIpVtdz);
    fChain->SetBranchAddress("TL_TauLTIpVtdzError", &TL_TauLTIpVtdzError);
    fChain->SetBranchAddress("TL_TauLTNormChiSqrd", &TL_TauLTNormChiSqrd);
    fChain->SetBranchAddress("TL_TauLTPt", &TL_TauLTPt);
    fChain->SetBranchAddress("TL_TauLTValidHits", &TL_TauLTValidHits);
    fChain->SetBranchAddress("TL_TauLTvalid", &TL_TauLTvalid);
    fChain->SetBranchAddress("TL_TauLTvx", &TL_TauLTvx);
    fChain->SetBranchAddress("TL_TauLTvy", &TL_TauLTvy);
    fChain->SetBranchAddress("TL_TauLTvz", &TL_TauLTvz);
    fChain->SetBranchAddress("TL_TauLeptonCosDeltaPhi", &TL_TauLeptonCosDeltaPhi);
    fChain->SetBranchAddress("TL_TauLeptonDeltaR", &TL_TauLeptonDeltaR);
    fChain->SetBranchAddress("TL_TauLeptonMETMass", &TL_TauLeptonMETMass);
    fChain->SetBranchAddress("TL_TauLeptonVisibleMass", &TL_TauLeptonVisibleMass);
    fChain->SetBranchAddress("TL_TauMomentumRank", &TL_TauMomentumRank);
    fChain->SetBranchAddress("TL_TauNProngs", &TL_TauNProngs);
    fChain->SetBranchAddress("TL_TauNSignalGammas", &TL_TauNSignalGammas);
    fChain->SetBranchAddress("TL_TauNSignalNeutrals", &TL_TauNSignalNeutrals);
    fChain->SetBranchAddress("TL_TauP", &TL_TauP);
    fChain->SetBranchAddress("TL_TauPhi", &TL_TauPhi);
    fChain->SetBranchAddress("TL_TauPt", &TL_TauPt);
    fChain->SetBranchAddress("TL_TriggerEventWeight", &TL_TriggerEventWeight);
    // >>> End address <<<
}
