// vim: ts=4:sw=4:et:sta
#include "../interface/TTLBranches.h"

using namespace roast;

void
ttl::Branches::Clear()
{
    // >>> Begin clear <<<
    Ev_runNumber = 0;
    Ev_eventNumber = 0;
    Ev_lumiBlock = 0;
    puWeight = 0;
    puWeightUp = 0;
    puWeightDown = 0;
    topPtWeight = 0;
    topPtWeightUp = 0;
    topPtWeightDown = 0;
    q2WeightUp = 0;
    q2WeightDown = 0;
    Ev_MET = 0;
    Ev_METphi = 0;
    Ev_IsTauEvent = 0;
    puWeight2012A = 0;
    puWeight2012B = 0;
    puWeight2012C = 0;
    puWeight2012D = 0;
    puWeight2012AB = 0;
    puWeight2012BC = 0;
    puWeight2012CD = 0;
    puWeight2012ABC = 0;
    V_NumVertices = 0;
    V_NumInteractionsBXm1 = 0;
    V_NumInteractionsBX0 = 0;
    V_NumInteractionsBXp1 = 0;
    V_Xcoord->clear();
    V_XcoordErr->clear();
    V_Ycoord->clear();
    V_YcoordErr->clear();
    V_Zcoord->clear();
    V_ZcoordErr->clear();
    V_Rho->clear();
    V_NumDOF->clear();
    V_NormChiSquared->clear();
    GT_NumGenTaus = 0;
    GT_MomentumRank->clear();
    GT_Pt->clear();
    GT_Eta->clear();
    GT_Phi->clear();
    GT_VisPt->clear();
    GT_VisEta->clear();
    GT_VisPhi->clear();
    GT_ToElectron->clear();
    GT_ToMuon->clear();
    GT_ToHadrons->clear();
    GT_ParentId->clear();
    GT_ParentP->clear();
    GT_ParentPt->clear();
    GT_ParentEta->clear();
    GT_ParentPhi->clear();
    GJ_NumGenJets = 0;
    GJ_MomentumRank->clear();
    GJ_Pt->clear();
    GJ_Eta->clear();
    GJ_Phi->clear();
    GJ_IsBjet->clear();
    T_NumTaus = 0;
    T_MomentumRank->clear();
    T_Pt->clear();
    T_Eta->clear();
    T_Phi->clear();
    T_NProngs->clear();
    T_NSignalGammas->clear();
    T_NSignalNeutrals->clear();
    T_DecayMode->clear();
    T_EmFraction->clear();
    T_IsInTheCracks->clear();
    T_HPSagainstElectronDeadECAL->clear();
    T_HPSagainstElectronLoose->clear();
    T_HPSagainstElectronLooseMVA2->clear();
    T_HPSagainstElectronLooseMVA3->clear();
    T_HPSagainstElectronMVA->clear();
    T_HPSagainstElectronMVA2category->clear();
    T_HPSagainstElectronMVA2raw->clear();
    T_HPSagainstElectronMVA3category->clear();
    T_HPSagainstElectronMVA3raw->clear();
    T_HPSagainstElectronMedium->clear();
    T_HPSagainstElectronMediumMVA2->clear();
    T_HPSagainstElectronMediumMVA3->clear();
    T_HPSagainstElectronTight->clear();
    T_HPSagainstElectronTightMVA2->clear();
    T_HPSagainstElectronTightMVA3->clear();
    T_HPSagainstElectronVLooseMVA2->clear();
    T_HPSagainstElectronVTightMVA3->clear();
    T_HPSagainstMuonLoose->clear();
    T_HPSagainstMuonLoose2->clear();
    T_HPSagainstMuonMedium->clear();
    T_HPSagainstMuonMedium2->clear();
    T_HPSagainstMuonTight->clear();
    T_HPSagainstMuonTight2->clear();
    T_HPSbyCombinedIsolationDeltaBetaCorrRaw->clear();
    T_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits->clear();
    T_HPSbyIsolationMVA2raw->clear();
    T_HPSbyLooseCombinedIsolationDeltaBetaCorr->clear();
    T_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits->clear();
    T_HPSbyLooseIsolationMVA->clear();
    T_HPSbyLooseIsolationMVA2->clear();
    T_HPSbyMediumCombinedIsolationDeltaBetaCorr->clear();
    T_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits->clear();
    T_HPSbyMediumIsolationMVA->clear();
    T_HPSbyMediumIsolationMVA2->clear();
    T_HPSbyTightCombinedIsolationDeltaBetaCorr->clear();
    T_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits->clear();
    T_HPSbyTightIsolationMVA->clear();
    T_HPSbyTightIsolationMVA2->clear();
    T_HPSbyVLooseCombinedIsolationDeltaBetaCorr->clear();
    T_HPSdecayModeFinding->clear();
    T_HPSbyIsolationMVAraw->clear();
    T_LTPt->clear();
    T_Charge->clear();
    T_LTvalid->clear();
    T_LTIpVtdxy->clear();
    T_LTIpVtdz->clear();
    T_LTIpVtdxyError->clear();
    T_LTIpVtdzError->clear();
    T_LTvx->clear();
    T_LTvy->clear();
    T_LTvz->clear();
    T_LTValidHits->clear();
    T_LTNormChiSqrd->clear();
    T_TauGenMatchDaughter0Id->clear();
    T_TauGenMatchDaughter1Id->clear();
    T_TauGenMatchId->clear();
    T_TauGenMatchMother0Id->clear();
    T_TauGenMatchMother1Id->clear();
    T_TauGenMatchGrandmother00Id->clear();
    T_TauGenMatchGrandmother01Id->clear();
    T_TauGenMatchGrandmother10Id->clear();
    T_TauGenMatchGrandmother11Id->clear();
    T_TauGenMatchDaughter0Status->clear();
    T_TauGenMatchDaughter1Status->clear();
    T_TauGenMatchStatus->clear();
    T_TauGenMatchMother0Status->clear();
    T_TauGenMatchMother1Status->clear();
    T_TauGenMatchGrandmother00Status->clear();
    T_TauGenMatchGrandmother01Status->clear();
    T_TauGenMatchGrandmother10Status->clear();
    T_TauGenMatchGrandmother11Status->clear();
    E_NumElectrons = 0;
    E_MomentumRank->clear();
    E_Pt->clear();
    E_Eta->clear();
    E_Phi->clear();
    E_IsTightElectron->clear();
    E_IsLooseElectron->clear();
    E_ElectronGenMatchDaughter0Id->clear();
    E_ElectronGenMatchDaughter1Id->clear();
    E_ElectronGenMatchId->clear();
    E_ElectronGenMatchMother0Id->clear();
    E_ElectronGenMatchMother1Id->clear();
    E_ElectronGenMatchGrandmother00Id->clear();
    E_ElectronGenMatchGrandmother01Id->clear();
    E_ElectronGenMatchGrandmother10Id->clear();
    E_ElectronGenMatchGrandmother11Id->clear();
    E_ElectronGenMatchDaughter0Status->clear();
    E_ElectronGenMatchDaughter1Status->clear();
    E_ElectronGenMatchStatus->clear();
    E_ElectronGenMatchMother0Status->clear();
    E_ElectronGenMatchMother1Status->clear();
    E_ElectronGenMatchGrandmother00Status->clear();
    E_ElectronGenMatchGrandmother01Status->clear();
    E_ElectronGenMatchGrandmother10Status->clear();
    E_ElectronGenMatchGrandmother11Status->clear();
    M_NumMuons = 0;
    M_MomentumRank->clear();
    M_Pt->clear();
    M_Eta->clear();
    M_Phi->clear();
    M_RelIso->clear();
    M_IsTightMuon->clear();
    M_IsLooseMuon->clear();
    M_MuonGenMatchDaughter0Id->clear();
    M_MuonGenMatchDaughter1Id->clear();
    M_MuonGenMatchId->clear();
    M_MuonGenMatchMother0Id->clear();
    M_MuonGenMatchMother1Id->clear();
    M_MuonGenMatchGrandmother00Id->clear();
    M_MuonGenMatchGrandmother01Id->clear();
    M_MuonGenMatchGrandmother10Id->clear();
    M_MuonGenMatchGrandmother11Id->clear();
    M_MuonGenMatchDaughter0Status->clear();
    M_MuonGenMatchDaughter1Status->clear();
    M_MuonGenMatchStatus->clear();
    M_MuonGenMatchMother0Status->clear();
    M_MuonGenMatchMother1Status->clear();
    M_MuonGenMatchGrandmother00Status->clear();
    M_MuonGenMatchGrandmother01Status->clear();
    M_MuonGenMatchGrandmother10Status->clear();
    M_MuonGenMatchGrandmother11Status->clear();
    J_NumJets = 0;
    J_MomentumRank->clear();
    J_Pt->clear();
    J_Eta->clear();
    J_Phi->clear();
    J_combSecVtxBTag->clear();
    J_combSecVtxLooseBTag->clear();
    J_combSecVtxMediumBTag->clear();
    J_combSecVtxTightBTag->clear();
    TTL_NumTaus = 0;
    TTL_NumMuons = 0;
    TTL_NumElectrons = 0;
    TTL_NumLeptons = 0;
    TTL_NumCombos = 0;
    TTL_MomentumRank->clear();
    TTL_Tau1MomentumRank->clear();
    TTL_Tau1Pt->clear();
    TTL_Tau1Eta->clear();
    TTL_Tau1Phi->clear();
    TTL_Tau1NProngs->clear();
    TTL_Tau1NSignalGammas->clear();
    TTL_Tau1NSignalNeutrals->clear();
    TTL_Tau1DecayMode->clear();
    TTL_Tau1EmFraction->clear();
    TTL_Tau1IsInTheCracks->clear();
    TTL_Tau1HPSagainstElectronDeadECAL->clear();
    TTL_Tau1HPSagainstElectronLoose->clear();
    TTL_Tau1HPSagainstElectronLooseMVA2->clear();
    TTL_Tau1HPSagainstElectronLooseMVA3->clear();
    TTL_Tau1HPSagainstElectronMVA->clear();
    TTL_Tau1HPSagainstElectronMVA2category->clear();
    TTL_Tau1HPSagainstElectronMVA2raw->clear();
    TTL_Tau1HPSagainstElectronMVA3category->clear();
    TTL_Tau1HPSagainstElectronMVA3raw->clear();
    TTL_Tau1HPSagainstElectronMedium->clear();
    TTL_Tau1HPSagainstElectronMediumMVA2->clear();
    TTL_Tau1HPSagainstElectronMediumMVA3->clear();
    TTL_Tau1HPSagainstElectronTight->clear();
    TTL_Tau1HPSagainstElectronTightMVA2->clear();
    TTL_Tau1HPSagainstElectronTightMVA3->clear();
    TTL_Tau1HPSagainstElectronVLooseMVA2->clear();
    TTL_Tau1HPSagainstElectronVTightMVA3->clear();
    TTL_Tau1HPSagainstMuonLoose->clear();
    TTL_Tau1HPSagainstMuonLoose2->clear();
    TTL_Tau1HPSagainstMuonMedium->clear();
    TTL_Tau1HPSagainstMuonMedium2->clear();
    TTL_Tau1HPSagainstMuonTight->clear();
    TTL_Tau1HPSagainstMuonTight2->clear();
    TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw->clear();
    TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits->clear();
    TTL_Tau1HPSbyIsolationMVA2raw->clear();
    TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr->clear();
    TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits->clear();
    TTL_Tau1HPSbyLooseIsolationMVA->clear();
    TTL_Tau1HPSbyLooseIsolationMVA2->clear();
    TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr->clear();
    TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits->clear();
    TTL_Tau1HPSbyMediumIsolationMVA->clear();
    TTL_Tau1HPSbyMediumIsolationMVA2->clear();
    TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr->clear();
    TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr3Hits->clear();
    TTL_Tau1HPSbyTightIsolationMVA->clear();
    TTL_Tau1HPSbyTightIsolationMVA2->clear();
    TTL_Tau1HPSbyVLooseCombinedIsolationDeltaBetaCorr->clear();
    TTL_Tau1HPSdecayModeFinding->clear();
    TTL_Tau1HPSbyIsolationMVAraw->clear();
    TTL_Tau1LTPt->clear();
    TTL_Tau1Charge->clear();
    TTL_Tau1LTvalid->clear();
    TTL_Tau1LTIpVtdxy->clear();
    TTL_Tau1LTIpVtdz->clear();
    TTL_Tau1LTIpVtdxyError->clear();
    TTL_Tau1LTIpVtdzError->clear();
    TTL_Tau1LTvx->clear();
    TTL_Tau1LTvy->clear();
    TTL_Tau1LTvz->clear();
    TTL_Tau1LTValidHits->clear();
    TTL_Tau1LTNormChiSqrd->clear();
    TTL_Tau1GenMatchDaughter0Id->clear();
    TTL_Tau1GenMatchDaughter1Id->clear();
    TTL_Tau1GenMatchId->clear();
    TTL_Tau1GenMatchMother0Id->clear();
    TTL_Tau1GenMatchMother1Id->clear();
    TTL_Tau1GenMatchGrandmother00Id->clear();
    TTL_Tau1GenMatchGrandmother01Id->clear();
    TTL_Tau1GenMatchGrandmother10Id->clear();
    TTL_Tau1GenMatchGrandmother11Id->clear();
    TTL_Tau1GenMatchDaughter0Status->clear();
    TTL_Tau1GenMatchDaughter1Status->clear();
    TTL_Tau1GenMatchStatus->clear();
    TTL_Tau1GenMatchMother0Status->clear();
    TTL_Tau1GenMatchMother1Status->clear();
    TTL_Tau1GenMatchGrandmother00Status->clear();
    TTL_Tau1GenMatchGrandmother01Status->clear();
    TTL_Tau1GenMatchGrandmother10Status->clear();
    TTL_Tau1GenMatchGrandmother11Status->clear();
    TTL_Tau2MomentumRank->clear();
    TTL_Tau2Pt->clear();
    TTL_Tau2Eta->clear();
    TTL_Tau2Phi->clear();
    TTL_Tau2NProngs->clear();
    TTL_Tau2NSignalGammas->clear();
    TTL_Tau2NSignalNeutrals->clear();
    TTL_Tau2DecayMode->clear();
    TTL_Tau2EmFraction->clear();
    TTL_Tau2IsInTheCracks->clear();
    TTL_Tau2HPSagainstElectronDeadECAL->clear();
    TTL_Tau2HPSagainstElectronLoose->clear();
    TTL_Tau2HPSagainstElectronLooseMVA2->clear();
    TTL_Tau2HPSagainstElectronLooseMVA3->clear();
    TTL_Tau2HPSagainstElectronMVA->clear();
    TTL_Tau2HPSagainstElectronMVA2category->clear();
    TTL_Tau2HPSagainstElectronMVA2raw->clear();
    TTL_Tau2HPSagainstElectronMVA3category->clear();
    TTL_Tau2HPSagainstElectronMVA3raw->clear();
    TTL_Tau2HPSagainstElectronMedium->clear();
    TTL_Tau2HPSagainstElectronMediumMVA2->clear();
    TTL_Tau2HPSagainstElectronMediumMVA3->clear();
    TTL_Tau2HPSagainstElectronTight->clear();
    TTL_Tau2HPSagainstElectronTightMVA2->clear();
    TTL_Tau2HPSagainstElectronTightMVA3->clear();
    TTL_Tau2HPSagainstElectronVLooseMVA2->clear();
    TTL_Tau2HPSagainstElectronVTightMVA3->clear();
    TTL_Tau2HPSagainstMuonLoose->clear();
    TTL_Tau2HPSagainstMuonLoose2->clear();
    TTL_Tau2HPSagainstMuonMedium->clear();
    TTL_Tau2HPSagainstMuonMedium2->clear();
    TTL_Tau2HPSagainstMuonTight->clear();
    TTL_Tau2HPSagainstMuonTight2->clear();
    TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw->clear();
    TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits->clear();
    TTL_Tau2HPSbyIsolationMVA2raw->clear();
    TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr->clear();
    TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits->clear();
    TTL_Tau2HPSbyLooseIsolationMVA->clear();
    TTL_Tau2HPSbyLooseIsolationMVA2->clear();
    TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr->clear();
    TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits->clear();
    TTL_Tau2HPSbyMediumIsolationMVA->clear();
    TTL_Tau2HPSbyMediumIsolationMVA2->clear();
    TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr->clear();
    TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr3Hits->clear();
    TTL_Tau2HPSbyTightIsolationMVA->clear();
    TTL_Tau2HPSbyTightIsolationMVA2->clear();
    TTL_Tau2HPSbyVLooseCombinedIsolationDeltaBetaCorr->clear();
    TTL_Tau2HPSdecayModeFinding->clear();
    TTL_Tau2HPSbyIsolationMVAraw->clear();
    TTL_Tau2LTPt->clear();
    TTL_Tau2Charge->clear();
    TTL_Tau2LTvalid->clear();
    TTL_Tau2LTIpVtdxy->clear();
    TTL_Tau2LTIpVtdz->clear();
    TTL_Tau2LTIpVtdxyError->clear();
    TTL_Tau2LTIpVtdzError->clear();
    TTL_Tau2LTvx->clear();
    TTL_Tau2LTvy->clear();
    TTL_Tau2LTvz->clear();
    TTL_Tau2LTValidHits->clear();
    TTL_Tau2LTNormChiSqrd->clear();
    TTL_Tau2GenMatchDaughter0Id->clear();
    TTL_Tau2GenMatchDaughter1Id->clear();
    TTL_Tau2GenMatchId->clear();
    TTL_Tau2GenMatchMother0Id->clear();
    TTL_Tau2GenMatchMother1Id->clear();
    TTL_Tau2GenMatchGrandmother00Id->clear();
    TTL_Tau2GenMatchGrandmother01Id->clear();
    TTL_Tau2GenMatchGrandmother10Id->clear();
    TTL_Tau2GenMatchGrandmother11Id->clear();
    TTL_Tau2GenMatchDaughter0Status->clear();
    TTL_Tau2GenMatchDaughter1Status->clear();
    TTL_Tau2GenMatchStatus->clear();
    TTL_Tau2GenMatchMother0Status->clear();
    TTL_Tau2GenMatchMother1Status->clear();
    TTL_Tau2GenMatchGrandmother00Status->clear();
    TTL_Tau2GenMatchGrandmother01Status->clear();
    TTL_Tau2GenMatchGrandmother10Status->clear();
    TTL_Tau2GenMatchGrandmother11Status->clear();
    TTL_MuonMomentumRank->clear();
    TTL_ElectronMomentumRank->clear();
    TTL_LeptonMomentumRank->clear();
    TTL_LeptonIsMuon->clear();
    TTL_LeptonIsElectron->clear();
    TTL_LeptonPt->clear();
    TTL_LeptonEta->clear();
    TTL_LeptonPhi->clear();
    TTL_LeptonRelIso->clear();
    TTL_LeptonIsLoose->clear();
    TTL_LeptonIsTight->clear();
    TTL_NumLooseMuons->clear();
    TTL_NumExLooseMuons->clear();
    TTL_NumTightMuons->clear();
    TTL_NumLooseElectrons->clear();
    TTL_NumExLooseElectrons->clear();
    TTL_NumTightElectrons->clear();
    TTL_LeptonGenMatchDaughter0Id->clear();
    TTL_LeptonGenMatchDaughter1Id->clear();
    TTL_LeptonGenMatchId->clear();
    TTL_LeptonGenMatchMother0Id->clear();
    TTL_LeptonGenMatchMother1Id->clear();
    TTL_LeptonGenMatchGrandmother00Id->clear();
    TTL_LeptonGenMatchGrandmother01Id->clear();
    TTL_LeptonGenMatchGrandmother10Id->clear();
    TTL_LeptonGenMatchGrandmother11Id->clear();
    TTL_LeptonGenMatchDaughter0Status->clear();
    TTL_LeptonGenMatchDaughter1Status->clear();
    TTL_LeptonGenMatchStatus->clear();
    TTL_LeptonGenMatchMother0Status->clear();
    TTL_LeptonGenMatchMother1Status->clear();
    TTL_LeptonGenMatchGrandmother00Status->clear();
    TTL_LeptonGenMatchGrandmother01Status->clear();
    TTL_LeptonGenMatchGrandmother10Status->clear();
    TTL_LeptonGenMatchGrandmother11Status->clear();
    TTL_DitauVisibleMass->clear();
    TTL_DitauMETMass->clear();
    TTL_DitauCosDeltaPhi->clear();
    TTL_DitauDeltaR->clear();
    TTL_Tau1LeptonDeltaR->clear();
    TTL_Tau2LeptonDeltaR->clear();
    TTL_HT->clear();
    TTL_NumCSVLbtagJets->clear();
    TTL_NumCSVMbtagJets->clear();
    TTL_NumCSVTbtagJets->clear();
    TTL_NumNonCSVLbtagJets->clear();
    TTL_NumNonCSVMbtagJets->clear();
    TTL_NumNonCSVTbtagJets->clear();
    TTL_NumCleanCSVLbtagJets->clear();
    TTL_NumCleanCSVMbtagJets->clear();
    TTL_NumCleanCSVTbtagJets->clear();
    TTL_NumCleanNonCSVLbtagJets->clear();
    TTL_NumCleanNonCSVMbtagJets->clear();
    TTL_NumCleanNonCSVTbtagJets->clear();
    TTL_CleanJetIndices->clear();
    TTL_LeptonEventWeight->clear();
    CSVeventWeight->clear();
    CSVeventWeightHFdown->clear();
    CSVeventWeightHFup->clear();
    CSVeventWeightLFdown->clear();
    CSVeventWeightLFup->clear();
    CSVeventWeightHFStats1down->clear();
    CSVeventWeightHFStats1up->clear();
    CSVeventWeightLFStats1down->clear();
    CSVeventWeightLFStats1up->clear();
    CSVeventWeightHFStats2down->clear();
    CSVeventWeightHFStats2up->clear();
    CSVeventWeightLFStats2down->clear();
    CSVeventWeightLFStats2up->clear();
    CSVeventWeightCErr1up->clear();
    CSVeventWeightCErr1down->clear();
    CSVeventWeightCErr2up->clear();
    CSVeventWeightCErr2down->clear();
    // >>> End clear <<<
}

void
ttl::Branches::Delete()
{
    // >>> Begin delete <<<
    delete V_Xcoord;
    delete V_XcoordErr;
    delete V_Ycoord;
    delete V_YcoordErr;
    delete V_Zcoord;
    delete V_ZcoordErr;
    delete V_Rho;
    delete V_NumDOF;
    delete V_NormChiSquared;
    delete GT_MomentumRank;
    delete GT_Pt;
    delete GT_Eta;
    delete GT_Phi;
    delete GT_VisPt;
    delete GT_VisEta;
    delete GT_VisPhi;
    delete GT_ToElectron;
    delete GT_ToMuon;
    delete GT_ToHadrons;
    delete GT_ParentId;
    delete GT_ParentP;
    delete GT_ParentPt;
    delete GT_ParentEta;
    delete GT_ParentPhi;
    delete GJ_MomentumRank;
    delete GJ_Pt;
    delete GJ_Eta;
    delete GJ_Phi;
    delete GJ_IsBjet;
    delete T_MomentumRank;
    delete T_Pt;
    delete T_Eta;
    delete T_Phi;
    delete T_NProngs;
    delete T_NSignalGammas;
    delete T_NSignalNeutrals;
    delete T_DecayMode;
    delete T_EmFraction;
    delete T_IsInTheCracks;
    delete T_HPSagainstElectronDeadECAL;
    delete T_HPSagainstElectronLoose;
    delete T_HPSagainstElectronLooseMVA2;
    delete T_HPSagainstElectronLooseMVA3;
    delete T_HPSagainstElectronMVA;
    delete T_HPSagainstElectronMVA2category;
    delete T_HPSagainstElectronMVA2raw;
    delete T_HPSagainstElectronMVA3category;
    delete T_HPSagainstElectronMVA3raw;
    delete T_HPSagainstElectronMedium;
    delete T_HPSagainstElectronMediumMVA2;
    delete T_HPSagainstElectronMediumMVA3;
    delete T_HPSagainstElectronTight;
    delete T_HPSagainstElectronTightMVA2;
    delete T_HPSagainstElectronTightMVA3;
    delete T_HPSagainstElectronVLooseMVA2;
    delete T_HPSagainstElectronVTightMVA3;
    delete T_HPSagainstMuonLoose;
    delete T_HPSagainstMuonLoose2;
    delete T_HPSagainstMuonMedium;
    delete T_HPSagainstMuonMedium2;
    delete T_HPSagainstMuonTight;
    delete T_HPSagainstMuonTight2;
    delete T_HPSbyCombinedIsolationDeltaBetaCorrRaw;
    delete T_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits;
    delete T_HPSbyIsolationMVA2raw;
    delete T_HPSbyLooseCombinedIsolationDeltaBetaCorr;
    delete T_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits;
    delete T_HPSbyLooseIsolationMVA;
    delete T_HPSbyLooseIsolationMVA2;
    delete T_HPSbyMediumCombinedIsolationDeltaBetaCorr;
    delete T_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits;
    delete T_HPSbyMediumIsolationMVA;
    delete T_HPSbyMediumIsolationMVA2;
    delete T_HPSbyTightCombinedIsolationDeltaBetaCorr;
    delete T_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits;
    delete T_HPSbyTightIsolationMVA;
    delete T_HPSbyTightIsolationMVA2;
    delete T_HPSbyVLooseCombinedIsolationDeltaBetaCorr;
    delete T_HPSdecayModeFinding;
    delete T_HPSbyIsolationMVAraw;
    delete T_LTPt;
    delete T_Charge;
    delete T_LTvalid;
    delete T_LTIpVtdxy;
    delete T_LTIpVtdz;
    delete T_LTIpVtdxyError;
    delete T_LTIpVtdzError;
    delete T_LTvx;
    delete T_LTvy;
    delete T_LTvz;
    delete T_LTValidHits;
    delete T_LTNormChiSqrd;
    delete T_TauGenMatchDaughter0Id;
    delete T_TauGenMatchDaughter1Id;
    delete T_TauGenMatchId;
    delete T_TauGenMatchMother0Id;
    delete T_TauGenMatchMother1Id;
    delete T_TauGenMatchGrandmother00Id;
    delete T_TauGenMatchGrandmother01Id;
    delete T_TauGenMatchGrandmother10Id;
    delete T_TauGenMatchGrandmother11Id;
    delete T_TauGenMatchDaughter0Status;
    delete T_TauGenMatchDaughter1Status;
    delete T_TauGenMatchStatus;
    delete T_TauGenMatchMother0Status;
    delete T_TauGenMatchMother1Status;
    delete T_TauGenMatchGrandmother00Status;
    delete T_TauGenMatchGrandmother01Status;
    delete T_TauGenMatchGrandmother10Status;
    delete T_TauGenMatchGrandmother11Status;
    delete E_MomentumRank;
    delete E_Pt;
    delete E_Eta;
    delete E_Phi;
    delete E_IsTightElectron;
    delete E_IsLooseElectron;
    delete E_ElectronGenMatchDaughter0Id;
    delete E_ElectronGenMatchDaughter1Id;
    delete E_ElectronGenMatchId;
    delete E_ElectronGenMatchMother0Id;
    delete E_ElectronGenMatchMother1Id;
    delete E_ElectronGenMatchGrandmother00Id;
    delete E_ElectronGenMatchGrandmother01Id;
    delete E_ElectronGenMatchGrandmother10Id;
    delete E_ElectronGenMatchGrandmother11Id;
    delete E_ElectronGenMatchDaughter0Status;
    delete E_ElectronGenMatchDaughter1Status;
    delete E_ElectronGenMatchStatus;
    delete E_ElectronGenMatchMother0Status;
    delete E_ElectronGenMatchMother1Status;
    delete E_ElectronGenMatchGrandmother00Status;
    delete E_ElectronGenMatchGrandmother01Status;
    delete E_ElectronGenMatchGrandmother10Status;
    delete E_ElectronGenMatchGrandmother11Status;
    delete M_MomentumRank;
    delete M_Pt;
    delete M_Eta;
    delete M_Phi;
    delete M_RelIso;
    delete M_IsTightMuon;
    delete M_IsLooseMuon;
    delete M_MuonGenMatchDaughter0Id;
    delete M_MuonGenMatchDaughter1Id;
    delete M_MuonGenMatchId;
    delete M_MuonGenMatchMother0Id;
    delete M_MuonGenMatchMother1Id;
    delete M_MuonGenMatchGrandmother00Id;
    delete M_MuonGenMatchGrandmother01Id;
    delete M_MuonGenMatchGrandmother10Id;
    delete M_MuonGenMatchGrandmother11Id;
    delete M_MuonGenMatchDaughter0Status;
    delete M_MuonGenMatchDaughter1Status;
    delete M_MuonGenMatchStatus;
    delete M_MuonGenMatchMother0Status;
    delete M_MuonGenMatchMother1Status;
    delete M_MuonGenMatchGrandmother00Status;
    delete M_MuonGenMatchGrandmother01Status;
    delete M_MuonGenMatchGrandmother10Status;
    delete M_MuonGenMatchGrandmother11Status;
    delete J_MomentumRank;
    delete J_Pt;
    delete J_Eta;
    delete J_Phi;
    delete J_combSecVtxBTag;
    delete J_combSecVtxLooseBTag;
    delete J_combSecVtxMediumBTag;
    delete J_combSecVtxTightBTag;
    delete TTL_MomentumRank;
    delete TTL_Tau1MomentumRank;
    delete TTL_Tau1Pt;
    delete TTL_Tau1Eta;
    delete TTL_Tau1Phi;
    delete TTL_Tau1NProngs;
    delete TTL_Tau1NSignalGammas;
    delete TTL_Tau1NSignalNeutrals;
    delete TTL_Tau1DecayMode;
    delete TTL_Tau1EmFraction;
    delete TTL_Tau1IsInTheCracks;
    delete TTL_Tau1HPSagainstElectronDeadECAL;
    delete TTL_Tau1HPSagainstElectronLoose;
    delete TTL_Tau1HPSagainstElectronLooseMVA2;
    delete TTL_Tau1HPSagainstElectronLooseMVA3;
    delete TTL_Tau1HPSagainstElectronMVA;
    delete TTL_Tau1HPSagainstElectronMVA2category;
    delete TTL_Tau1HPSagainstElectronMVA2raw;
    delete TTL_Tau1HPSagainstElectronMVA3category;
    delete TTL_Tau1HPSagainstElectronMVA3raw;
    delete TTL_Tau1HPSagainstElectronMedium;
    delete TTL_Tau1HPSagainstElectronMediumMVA2;
    delete TTL_Tau1HPSagainstElectronMediumMVA3;
    delete TTL_Tau1HPSagainstElectronTight;
    delete TTL_Tau1HPSagainstElectronTightMVA2;
    delete TTL_Tau1HPSagainstElectronTightMVA3;
    delete TTL_Tau1HPSagainstElectronVLooseMVA2;
    delete TTL_Tau1HPSagainstElectronVTightMVA3;
    delete TTL_Tau1HPSagainstMuonLoose;
    delete TTL_Tau1HPSagainstMuonLoose2;
    delete TTL_Tau1HPSagainstMuonMedium;
    delete TTL_Tau1HPSagainstMuonMedium2;
    delete TTL_Tau1HPSagainstMuonTight;
    delete TTL_Tau1HPSagainstMuonTight2;
    delete TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw;
    delete TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits;
    delete TTL_Tau1HPSbyIsolationMVA2raw;
    delete TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr;
    delete TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits;
    delete TTL_Tau1HPSbyLooseIsolationMVA;
    delete TTL_Tau1HPSbyLooseIsolationMVA2;
    delete TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr;
    delete TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits;
    delete TTL_Tau1HPSbyMediumIsolationMVA;
    delete TTL_Tau1HPSbyMediumIsolationMVA2;
    delete TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr;
    delete TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr3Hits;
    delete TTL_Tau1HPSbyTightIsolationMVA;
    delete TTL_Tau1HPSbyTightIsolationMVA2;
    delete TTL_Tau1HPSbyVLooseCombinedIsolationDeltaBetaCorr;
    delete TTL_Tau1HPSdecayModeFinding;
    delete TTL_Tau1HPSbyIsolationMVAraw;
    delete TTL_Tau1LTPt;
    delete TTL_Tau1Charge;
    delete TTL_Tau1LTvalid;
    delete TTL_Tau1LTIpVtdxy;
    delete TTL_Tau1LTIpVtdz;
    delete TTL_Tau1LTIpVtdxyError;
    delete TTL_Tau1LTIpVtdzError;
    delete TTL_Tau1LTvx;
    delete TTL_Tau1LTvy;
    delete TTL_Tau1LTvz;
    delete TTL_Tau1LTValidHits;
    delete TTL_Tau1LTNormChiSqrd;
    delete TTL_Tau1GenMatchDaughter0Id;
    delete TTL_Tau1GenMatchDaughter1Id;
    delete TTL_Tau1GenMatchId;
    delete TTL_Tau1GenMatchMother0Id;
    delete TTL_Tau1GenMatchMother1Id;
    delete TTL_Tau1GenMatchGrandmother00Id;
    delete TTL_Tau1GenMatchGrandmother01Id;
    delete TTL_Tau1GenMatchGrandmother10Id;
    delete TTL_Tau1GenMatchGrandmother11Id;
    delete TTL_Tau1GenMatchDaughter0Status;
    delete TTL_Tau1GenMatchDaughter1Status;
    delete TTL_Tau1GenMatchStatus;
    delete TTL_Tau1GenMatchMother0Status;
    delete TTL_Tau1GenMatchMother1Status;
    delete TTL_Tau1GenMatchGrandmother00Status;
    delete TTL_Tau1GenMatchGrandmother01Status;
    delete TTL_Tau1GenMatchGrandmother10Status;
    delete TTL_Tau1GenMatchGrandmother11Status;
    delete TTL_Tau2MomentumRank;
    delete TTL_Tau2Pt;
    delete TTL_Tau2Eta;
    delete TTL_Tau2Phi;
    delete TTL_Tau2NProngs;
    delete TTL_Tau2NSignalGammas;
    delete TTL_Tau2NSignalNeutrals;
    delete TTL_Tau2DecayMode;
    delete TTL_Tau2EmFraction;
    delete TTL_Tau2IsInTheCracks;
    delete TTL_Tau2HPSagainstElectronDeadECAL;
    delete TTL_Tau2HPSagainstElectronLoose;
    delete TTL_Tau2HPSagainstElectronLooseMVA2;
    delete TTL_Tau2HPSagainstElectronLooseMVA3;
    delete TTL_Tau2HPSagainstElectronMVA;
    delete TTL_Tau2HPSagainstElectronMVA2category;
    delete TTL_Tau2HPSagainstElectronMVA2raw;
    delete TTL_Tau2HPSagainstElectronMVA3category;
    delete TTL_Tau2HPSagainstElectronMVA3raw;
    delete TTL_Tau2HPSagainstElectronMedium;
    delete TTL_Tau2HPSagainstElectronMediumMVA2;
    delete TTL_Tau2HPSagainstElectronMediumMVA3;
    delete TTL_Tau2HPSagainstElectronTight;
    delete TTL_Tau2HPSagainstElectronTightMVA2;
    delete TTL_Tau2HPSagainstElectronTightMVA3;
    delete TTL_Tau2HPSagainstElectronVLooseMVA2;
    delete TTL_Tau2HPSagainstElectronVTightMVA3;
    delete TTL_Tau2HPSagainstMuonLoose;
    delete TTL_Tau2HPSagainstMuonLoose2;
    delete TTL_Tau2HPSagainstMuonMedium;
    delete TTL_Tau2HPSagainstMuonMedium2;
    delete TTL_Tau2HPSagainstMuonTight;
    delete TTL_Tau2HPSagainstMuonTight2;
    delete TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw;
    delete TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits;
    delete TTL_Tau2HPSbyIsolationMVA2raw;
    delete TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr;
    delete TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits;
    delete TTL_Tau2HPSbyLooseIsolationMVA;
    delete TTL_Tau2HPSbyLooseIsolationMVA2;
    delete TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr;
    delete TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits;
    delete TTL_Tau2HPSbyMediumIsolationMVA;
    delete TTL_Tau2HPSbyMediumIsolationMVA2;
    delete TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr;
    delete TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr3Hits;
    delete TTL_Tau2HPSbyTightIsolationMVA;
    delete TTL_Tau2HPSbyTightIsolationMVA2;
    delete TTL_Tau2HPSbyVLooseCombinedIsolationDeltaBetaCorr;
    delete TTL_Tau2HPSdecayModeFinding;
    delete TTL_Tau2HPSbyIsolationMVAraw;
    delete TTL_Tau2LTPt;
    delete TTL_Tau2Charge;
    delete TTL_Tau2LTvalid;
    delete TTL_Tau2LTIpVtdxy;
    delete TTL_Tau2LTIpVtdz;
    delete TTL_Tau2LTIpVtdxyError;
    delete TTL_Tau2LTIpVtdzError;
    delete TTL_Tau2LTvx;
    delete TTL_Tau2LTvy;
    delete TTL_Tau2LTvz;
    delete TTL_Tau2LTValidHits;
    delete TTL_Tau2LTNormChiSqrd;
    delete TTL_Tau2GenMatchDaughter0Id;
    delete TTL_Tau2GenMatchDaughter1Id;
    delete TTL_Tau2GenMatchId;
    delete TTL_Tau2GenMatchMother0Id;
    delete TTL_Tau2GenMatchMother1Id;
    delete TTL_Tau2GenMatchGrandmother00Id;
    delete TTL_Tau2GenMatchGrandmother01Id;
    delete TTL_Tau2GenMatchGrandmother10Id;
    delete TTL_Tau2GenMatchGrandmother11Id;
    delete TTL_Tau2GenMatchDaughter0Status;
    delete TTL_Tau2GenMatchDaughter1Status;
    delete TTL_Tau2GenMatchStatus;
    delete TTL_Tau2GenMatchMother0Status;
    delete TTL_Tau2GenMatchMother1Status;
    delete TTL_Tau2GenMatchGrandmother00Status;
    delete TTL_Tau2GenMatchGrandmother01Status;
    delete TTL_Tau2GenMatchGrandmother10Status;
    delete TTL_Tau2GenMatchGrandmother11Status;
    delete TTL_MuonMomentumRank;
    delete TTL_ElectronMomentumRank;
    delete TTL_LeptonMomentumRank;
    delete TTL_LeptonIsMuon;
    delete TTL_LeptonIsElectron;
    delete TTL_LeptonPt;
    delete TTL_LeptonEta;
    delete TTL_LeptonPhi;
    delete TTL_LeptonRelIso;
    delete TTL_LeptonIsLoose;
    delete TTL_LeptonIsTight;
    delete TTL_NumLooseMuons;
    delete TTL_NumExLooseMuons;
    delete TTL_NumTightMuons;
    delete TTL_NumLooseElectrons;
    delete TTL_NumExLooseElectrons;
    delete TTL_NumTightElectrons;
    delete TTL_LeptonGenMatchDaughter0Id;
    delete TTL_LeptonGenMatchDaughter1Id;
    delete TTL_LeptonGenMatchId;
    delete TTL_LeptonGenMatchMother0Id;
    delete TTL_LeptonGenMatchMother1Id;
    delete TTL_LeptonGenMatchGrandmother00Id;
    delete TTL_LeptonGenMatchGrandmother01Id;
    delete TTL_LeptonGenMatchGrandmother10Id;
    delete TTL_LeptonGenMatchGrandmother11Id;
    delete TTL_LeptonGenMatchDaughter0Status;
    delete TTL_LeptonGenMatchDaughter1Status;
    delete TTL_LeptonGenMatchStatus;
    delete TTL_LeptonGenMatchMother0Status;
    delete TTL_LeptonGenMatchMother1Status;
    delete TTL_LeptonGenMatchGrandmother00Status;
    delete TTL_LeptonGenMatchGrandmother01Status;
    delete TTL_LeptonGenMatchGrandmother10Status;
    delete TTL_LeptonGenMatchGrandmother11Status;
    delete TTL_DitauVisibleMass;
    delete TTL_DitauMETMass;
    delete TTL_DitauCosDeltaPhi;
    delete TTL_DitauDeltaR;
    delete TTL_Tau1LeptonDeltaR;
    delete TTL_Tau2LeptonDeltaR;
    delete TTL_HT;
    delete TTL_NumCSVLbtagJets;
    delete TTL_NumCSVMbtagJets;
    delete TTL_NumCSVTbtagJets;
    delete TTL_NumNonCSVLbtagJets;
    delete TTL_NumNonCSVMbtagJets;
    delete TTL_NumNonCSVTbtagJets;
    delete TTL_NumCleanCSVLbtagJets;
    delete TTL_NumCleanCSVMbtagJets;
    delete TTL_NumCleanCSVTbtagJets;
    delete TTL_NumCleanNonCSVLbtagJets;
    delete TTL_NumCleanNonCSVMbtagJets;
    delete TTL_NumCleanNonCSVTbtagJets;
    delete TTL_CleanJetIndices;
    delete TTL_LeptonEventWeight;
    delete CSVeventWeight;
    delete CSVeventWeightHFdown;
    delete CSVeventWeightHFup;
    delete CSVeventWeightLFdown;
    delete CSVeventWeightLFup;
    delete CSVeventWeightHFStats1down;
    delete CSVeventWeightHFStats1up;
    delete CSVeventWeightLFStats1down;
    delete CSVeventWeightLFStats1up;
    delete CSVeventWeightHFStats2down;
    delete CSVeventWeightHFStats2up;
    delete CSVeventWeightLFStats2down;
    delete CSVeventWeightLFStats2up;
    delete CSVeventWeightCErr1up;
    delete CSVeventWeightCErr1down;
    delete CSVeventWeightCErr2up;
    delete CSVeventWeightCErr2down;
    // >>> End delete <<<
}

void
ttl::Branches::Null()
{
    // >>> Begin null <<<
    Ev_runNumber = 0;
    Ev_eventNumber = 0;
    Ev_lumiBlock = 0;
    puWeight = 0;
    puWeightUp = 0;
    puWeightDown = 0;
    topPtWeight = 0;
    topPtWeightUp = 0;
    topPtWeightDown = 0;
    q2WeightUp = 0;
    q2WeightDown = 0;
    Ev_MET = 0;
    Ev_METphi = 0;
    Ev_IsTauEvent = 0;
    puWeight2012A = 0;
    puWeight2012B = 0;
    puWeight2012C = 0;
    puWeight2012D = 0;
    puWeight2012AB = 0;
    puWeight2012BC = 0;
    puWeight2012CD = 0;
    puWeight2012ABC = 0;
    V_NumVertices = 0;
    V_NumInteractionsBXm1 = 0;
    V_NumInteractionsBX0 = 0;
    V_NumInteractionsBXp1 = 0;
    V_Xcoord = 0;
    V_XcoordErr = 0;
    V_Ycoord = 0;
    V_YcoordErr = 0;
    V_Zcoord = 0;
    V_ZcoordErr = 0;
    V_Rho = 0;
    V_NumDOF = 0;
    V_NormChiSquared = 0;
    GT_NumGenTaus = 0;
    GT_MomentumRank = 0;
    GT_Pt = 0;
    GT_Eta = 0;
    GT_Phi = 0;
    GT_VisPt = 0;
    GT_VisEta = 0;
    GT_VisPhi = 0;
    GT_ToElectron = 0;
    GT_ToMuon = 0;
    GT_ToHadrons = 0;
    GT_ParentId = 0;
    GT_ParentP = 0;
    GT_ParentPt = 0;
    GT_ParentEta = 0;
    GT_ParentPhi = 0;
    GJ_NumGenJets = 0;
    GJ_MomentumRank = 0;
    GJ_Pt = 0;
    GJ_Eta = 0;
    GJ_Phi = 0;
    GJ_IsBjet = 0;
    T_NumTaus = 0;
    T_MomentumRank = 0;
    T_Pt = 0;
    T_Eta = 0;
    T_Phi = 0;
    T_NProngs = 0;
    T_NSignalGammas = 0;
    T_NSignalNeutrals = 0;
    T_DecayMode = 0;
    T_EmFraction = 0;
    T_IsInTheCracks = 0;
    T_HPSagainstElectronDeadECAL = 0;
    T_HPSagainstElectronLoose = 0;
    T_HPSagainstElectronLooseMVA2 = 0;
    T_HPSagainstElectronLooseMVA3 = 0;
    T_HPSagainstElectronMVA = 0;
    T_HPSagainstElectronMVA2category = 0;
    T_HPSagainstElectronMVA2raw = 0;
    T_HPSagainstElectronMVA3category = 0;
    T_HPSagainstElectronMVA3raw = 0;
    T_HPSagainstElectronMedium = 0;
    T_HPSagainstElectronMediumMVA2 = 0;
    T_HPSagainstElectronMediumMVA3 = 0;
    T_HPSagainstElectronTight = 0;
    T_HPSagainstElectronTightMVA2 = 0;
    T_HPSagainstElectronTightMVA3 = 0;
    T_HPSagainstElectronVLooseMVA2 = 0;
    T_HPSagainstElectronVTightMVA3 = 0;
    T_HPSagainstMuonLoose = 0;
    T_HPSagainstMuonLoose2 = 0;
    T_HPSagainstMuonMedium = 0;
    T_HPSagainstMuonMedium2 = 0;
    T_HPSagainstMuonTight = 0;
    T_HPSagainstMuonTight2 = 0;
    T_HPSbyCombinedIsolationDeltaBetaCorrRaw = 0;
    T_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits = 0;
    T_HPSbyIsolationMVA2raw = 0;
    T_HPSbyLooseCombinedIsolationDeltaBetaCorr = 0;
    T_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits = 0;
    T_HPSbyLooseIsolationMVA = 0;
    T_HPSbyLooseIsolationMVA2 = 0;
    T_HPSbyMediumCombinedIsolationDeltaBetaCorr = 0;
    T_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits = 0;
    T_HPSbyMediumIsolationMVA = 0;
    T_HPSbyMediumIsolationMVA2 = 0;
    T_HPSbyTightCombinedIsolationDeltaBetaCorr = 0;
    T_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits = 0;
    T_HPSbyTightIsolationMVA = 0;
    T_HPSbyTightIsolationMVA2 = 0;
    T_HPSbyVLooseCombinedIsolationDeltaBetaCorr = 0;
    T_HPSdecayModeFinding = 0;
    T_HPSbyIsolationMVAraw = 0;
    T_LTPt = 0;
    T_Charge = 0;
    T_LTvalid = 0;
    T_LTIpVtdxy = 0;
    T_LTIpVtdz = 0;
    T_LTIpVtdxyError = 0;
    T_LTIpVtdzError = 0;
    T_LTvx = 0;
    T_LTvy = 0;
    T_LTvz = 0;
    T_LTValidHits = 0;
    T_LTNormChiSqrd = 0;
    T_TauGenMatchDaughter0Id = 0;
    T_TauGenMatchDaughter1Id = 0;
    T_TauGenMatchId = 0;
    T_TauGenMatchMother0Id = 0;
    T_TauGenMatchMother1Id = 0;
    T_TauGenMatchGrandmother00Id = 0;
    T_TauGenMatchGrandmother01Id = 0;
    T_TauGenMatchGrandmother10Id = 0;
    T_TauGenMatchGrandmother11Id = 0;
    T_TauGenMatchDaughter0Status = 0;
    T_TauGenMatchDaughter1Status = 0;
    T_TauGenMatchStatus = 0;
    T_TauGenMatchMother0Status = 0;
    T_TauGenMatchMother1Status = 0;
    T_TauGenMatchGrandmother00Status = 0;
    T_TauGenMatchGrandmother01Status = 0;
    T_TauGenMatchGrandmother10Status = 0;
    T_TauGenMatchGrandmother11Status = 0;
    E_NumElectrons = 0;
    E_MomentumRank = 0;
    E_Pt = 0;
    E_Eta = 0;
    E_Phi = 0;
    E_IsTightElectron = 0;
    E_IsLooseElectron = 0;
    E_ElectronGenMatchDaughter0Id = 0;
    E_ElectronGenMatchDaughter1Id = 0;
    E_ElectronGenMatchId = 0;
    E_ElectronGenMatchMother0Id = 0;
    E_ElectronGenMatchMother1Id = 0;
    E_ElectronGenMatchGrandmother00Id = 0;
    E_ElectronGenMatchGrandmother01Id = 0;
    E_ElectronGenMatchGrandmother10Id = 0;
    E_ElectronGenMatchGrandmother11Id = 0;
    E_ElectronGenMatchDaughter0Status = 0;
    E_ElectronGenMatchDaughter1Status = 0;
    E_ElectronGenMatchStatus = 0;
    E_ElectronGenMatchMother0Status = 0;
    E_ElectronGenMatchMother1Status = 0;
    E_ElectronGenMatchGrandmother00Status = 0;
    E_ElectronGenMatchGrandmother01Status = 0;
    E_ElectronGenMatchGrandmother10Status = 0;
    E_ElectronGenMatchGrandmother11Status = 0;
    M_NumMuons = 0;
    M_MomentumRank = 0;
    M_Pt = 0;
    M_Eta = 0;
    M_Phi = 0;
    M_RelIso = 0;
    M_IsTightMuon = 0;
    M_IsLooseMuon = 0;
    M_MuonGenMatchDaughter0Id = 0;
    M_MuonGenMatchDaughter1Id = 0;
    M_MuonGenMatchId = 0;
    M_MuonGenMatchMother0Id = 0;
    M_MuonGenMatchMother1Id = 0;
    M_MuonGenMatchGrandmother00Id = 0;
    M_MuonGenMatchGrandmother01Id = 0;
    M_MuonGenMatchGrandmother10Id = 0;
    M_MuonGenMatchGrandmother11Id = 0;
    M_MuonGenMatchDaughter0Status = 0;
    M_MuonGenMatchDaughter1Status = 0;
    M_MuonGenMatchStatus = 0;
    M_MuonGenMatchMother0Status = 0;
    M_MuonGenMatchMother1Status = 0;
    M_MuonGenMatchGrandmother00Status = 0;
    M_MuonGenMatchGrandmother01Status = 0;
    M_MuonGenMatchGrandmother10Status = 0;
    M_MuonGenMatchGrandmother11Status = 0;
    J_NumJets = 0;
    J_MomentumRank = 0;
    J_Pt = 0;
    J_Eta = 0;
    J_Phi = 0;
    J_combSecVtxBTag = 0;
    J_combSecVtxLooseBTag = 0;
    J_combSecVtxMediumBTag = 0;
    J_combSecVtxTightBTag = 0;
    TTL_NumTaus = 0;
    TTL_NumMuons = 0;
    TTL_NumElectrons = 0;
    TTL_NumLeptons = 0;
    TTL_NumCombos = 0;
    TTL_MomentumRank = 0;
    TTL_Tau1MomentumRank = 0;
    TTL_Tau1Pt = 0;
    TTL_Tau1Eta = 0;
    TTL_Tau1Phi = 0;
    TTL_Tau1NProngs = 0;
    TTL_Tau1NSignalGammas = 0;
    TTL_Tau1NSignalNeutrals = 0;
    TTL_Tau1DecayMode = 0;
    TTL_Tau1EmFraction = 0;
    TTL_Tau1IsInTheCracks = 0;
    TTL_Tau1HPSagainstElectronDeadECAL = 0;
    TTL_Tau1HPSagainstElectronLoose = 0;
    TTL_Tau1HPSagainstElectronLooseMVA2 = 0;
    TTL_Tau1HPSagainstElectronLooseMVA3 = 0;
    TTL_Tau1HPSagainstElectronMVA = 0;
    TTL_Tau1HPSagainstElectronMVA2category = 0;
    TTL_Tau1HPSagainstElectronMVA2raw = 0;
    TTL_Tau1HPSagainstElectronMVA3category = 0;
    TTL_Tau1HPSagainstElectronMVA3raw = 0;
    TTL_Tau1HPSagainstElectronMedium = 0;
    TTL_Tau1HPSagainstElectronMediumMVA2 = 0;
    TTL_Tau1HPSagainstElectronMediumMVA3 = 0;
    TTL_Tau1HPSagainstElectronTight = 0;
    TTL_Tau1HPSagainstElectronTightMVA2 = 0;
    TTL_Tau1HPSagainstElectronTightMVA3 = 0;
    TTL_Tau1HPSagainstElectronVLooseMVA2 = 0;
    TTL_Tau1HPSagainstElectronVTightMVA3 = 0;
    TTL_Tau1HPSagainstMuonLoose = 0;
    TTL_Tau1HPSagainstMuonLoose2 = 0;
    TTL_Tau1HPSagainstMuonMedium = 0;
    TTL_Tau1HPSagainstMuonMedium2 = 0;
    TTL_Tau1HPSagainstMuonTight = 0;
    TTL_Tau1HPSagainstMuonTight2 = 0;
    TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw = 0;
    TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits = 0;
    TTL_Tau1HPSbyIsolationMVA2raw = 0;
    TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr = 0;
    TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits = 0;
    TTL_Tau1HPSbyLooseIsolationMVA = 0;
    TTL_Tau1HPSbyLooseIsolationMVA2 = 0;
    TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr = 0;
    TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits = 0;
    TTL_Tau1HPSbyMediumIsolationMVA = 0;
    TTL_Tau1HPSbyMediumIsolationMVA2 = 0;
    TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr = 0;
    TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr3Hits = 0;
    TTL_Tau1HPSbyTightIsolationMVA = 0;
    TTL_Tau1HPSbyTightIsolationMVA2 = 0;
    TTL_Tau1HPSbyVLooseCombinedIsolationDeltaBetaCorr = 0;
    TTL_Tau1HPSdecayModeFinding = 0;
    TTL_Tau1HPSbyIsolationMVAraw = 0;
    TTL_Tau1LTPt = 0;
    TTL_Tau1Charge = 0;
    TTL_Tau1LTvalid = 0;
    TTL_Tau1LTIpVtdxy = 0;
    TTL_Tau1LTIpVtdz = 0;
    TTL_Tau1LTIpVtdxyError = 0;
    TTL_Tau1LTIpVtdzError = 0;
    TTL_Tau1LTvx = 0;
    TTL_Tau1LTvy = 0;
    TTL_Tau1LTvz = 0;
    TTL_Tau1LTValidHits = 0;
    TTL_Tau1LTNormChiSqrd = 0;
    TTL_Tau1GenMatchDaughter0Id = 0;
    TTL_Tau1GenMatchDaughter1Id = 0;
    TTL_Tau1GenMatchId = 0;
    TTL_Tau1GenMatchMother0Id = 0;
    TTL_Tau1GenMatchMother1Id = 0;
    TTL_Tau1GenMatchGrandmother00Id = 0;
    TTL_Tau1GenMatchGrandmother01Id = 0;
    TTL_Tau1GenMatchGrandmother10Id = 0;
    TTL_Tau1GenMatchGrandmother11Id = 0;
    TTL_Tau1GenMatchDaughter0Status = 0;
    TTL_Tau1GenMatchDaughter1Status = 0;
    TTL_Tau1GenMatchStatus = 0;
    TTL_Tau1GenMatchMother0Status = 0;
    TTL_Tau1GenMatchMother1Status = 0;
    TTL_Tau1GenMatchGrandmother00Status = 0;
    TTL_Tau1GenMatchGrandmother01Status = 0;
    TTL_Tau1GenMatchGrandmother10Status = 0;
    TTL_Tau1GenMatchGrandmother11Status = 0;
    TTL_Tau2MomentumRank = 0;
    TTL_Tau2Pt = 0;
    TTL_Tau2Eta = 0;
    TTL_Tau2Phi = 0;
    TTL_Tau2NProngs = 0;
    TTL_Tau2NSignalGammas = 0;
    TTL_Tau2NSignalNeutrals = 0;
    TTL_Tau2DecayMode = 0;
    TTL_Tau2EmFraction = 0;
    TTL_Tau2IsInTheCracks = 0;
    TTL_Tau2HPSagainstElectronDeadECAL = 0;
    TTL_Tau2HPSagainstElectronLoose = 0;
    TTL_Tau2HPSagainstElectronLooseMVA2 = 0;
    TTL_Tau2HPSagainstElectronLooseMVA3 = 0;
    TTL_Tau2HPSagainstElectronMVA = 0;
    TTL_Tau2HPSagainstElectronMVA2category = 0;
    TTL_Tau2HPSagainstElectronMVA2raw = 0;
    TTL_Tau2HPSagainstElectronMVA3category = 0;
    TTL_Tau2HPSagainstElectronMVA3raw = 0;
    TTL_Tau2HPSagainstElectronMedium = 0;
    TTL_Tau2HPSagainstElectronMediumMVA2 = 0;
    TTL_Tau2HPSagainstElectronMediumMVA3 = 0;
    TTL_Tau2HPSagainstElectronTight = 0;
    TTL_Tau2HPSagainstElectronTightMVA2 = 0;
    TTL_Tau2HPSagainstElectronTightMVA3 = 0;
    TTL_Tau2HPSagainstElectronVLooseMVA2 = 0;
    TTL_Tau2HPSagainstElectronVTightMVA3 = 0;
    TTL_Tau2HPSagainstMuonLoose = 0;
    TTL_Tau2HPSagainstMuonLoose2 = 0;
    TTL_Tau2HPSagainstMuonMedium = 0;
    TTL_Tau2HPSagainstMuonMedium2 = 0;
    TTL_Tau2HPSagainstMuonTight = 0;
    TTL_Tau2HPSagainstMuonTight2 = 0;
    TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw = 0;
    TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits = 0;
    TTL_Tau2HPSbyIsolationMVA2raw = 0;
    TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr = 0;
    TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits = 0;
    TTL_Tau2HPSbyLooseIsolationMVA = 0;
    TTL_Tau2HPSbyLooseIsolationMVA2 = 0;
    TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr = 0;
    TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits = 0;
    TTL_Tau2HPSbyMediumIsolationMVA = 0;
    TTL_Tau2HPSbyMediumIsolationMVA2 = 0;
    TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr = 0;
    TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr3Hits = 0;
    TTL_Tau2HPSbyTightIsolationMVA = 0;
    TTL_Tau2HPSbyTightIsolationMVA2 = 0;
    TTL_Tau2HPSbyVLooseCombinedIsolationDeltaBetaCorr = 0;
    TTL_Tau2HPSdecayModeFinding = 0;
    TTL_Tau2HPSbyIsolationMVAraw = 0;
    TTL_Tau2LTPt = 0;
    TTL_Tau2Charge = 0;
    TTL_Tau2LTvalid = 0;
    TTL_Tau2LTIpVtdxy = 0;
    TTL_Tau2LTIpVtdz = 0;
    TTL_Tau2LTIpVtdxyError = 0;
    TTL_Tau2LTIpVtdzError = 0;
    TTL_Tau2LTvx = 0;
    TTL_Tau2LTvy = 0;
    TTL_Tau2LTvz = 0;
    TTL_Tau2LTValidHits = 0;
    TTL_Tau2LTNormChiSqrd = 0;
    TTL_Tau2GenMatchDaughter0Id = 0;
    TTL_Tau2GenMatchDaughter1Id = 0;
    TTL_Tau2GenMatchId = 0;
    TTL_Tau2GenMatchMother0Id = 0;
    TTL_Tau2GenMatchMother1Id = 0;
    TTL_Tau2GenMatchGrandmother00Id = 0;
    TTL_Tau2GenMatchGrandmother01Id = 0;
    TTL_Tau2GenMatchGrandmother10Id = 0;
    TTL_Tau2GenMatchGrandmother11Id = 0;
    TTL_Tau2GenMatchDaughter0Status = 0;
    TTL_Tau2GenMatchDaughter1Status = 0;
    TTL_Tau2GenMatchStatus = 0;
    TTL_Tau2GenMatchMother0Status = 0;
    TTL_Tau2GenMatchMother1Status = 0;
    TTL_Tau2GenMatchGrandmother00Status = 0;
    TTL_Tau2GenMatchGrandmother01Status = 0;
    TTL_Tau2GenMatchGrandmother10Status = 0;
    TTL_Tau2GenMatchGrandmother11Status = 0;
    TTL_MuonMomentumRank = 0;
    TTL_ElectronMomentumRank = 0;
    TTL_LeptonMomentumRank = 0;
    TTL_LeptonIsMuon = 0;
    TTL_LeptonIsElectron = 0;
    TTL_LeptonPt = 0;
    TTL_LeptonEta = 0;
    TTL_LeptonPhi = 0;
    TTL_LeptonRelIso = 0;
    TTL_LeptonIsLoose = 0;
    TTL_LeptonIsTight = 0;
    TTL_NumLooseMuons = 0;
    TTL_NumExLooseMuons = 0;
    TTL_NumTightMuons = 0;
    TTL_NumLooseElectrons = 0;
    TTL_NumExLooseElectrons = 0;
    TTL_NumTightElectrons = 0;
    TTL_LeptonGenMatchDaughter0Id = 0;
    TTL_LeptonGenMatchDaughter1Id = 0;
    TTL_LeptonGenMatchId = 0;
    TTL_LeptonGenMatchMother0Id = 0;
    TTL_LeptonGenMatchMother1Id = 0;
    TTL_LeptonGenMatchGrandmother00Id = 0;
    TTL_LeptonGenMatchGrandmother01Id = 0;
    TTL_LeptonGenMatchGrandmother10Id = 0;
    TTL_LeptonGenMatchGrandmother11Id = 0;
    TTL_LeptonGenMatchDaughter0Status = 0;
    TTL_LeptonGenMatchDaughter1Status = 0;
    TTL_LeptonGenMatchStatus = 0;
    TTL_LeptonGenMatchMother0Status = 0;
    TTL_LeptonGenMatchMother1Status = 0;
    TTL_LeptonGenMatchGrandmother00Status = 0;
    TTL_LeptonGenMatchGrandmother01Status = 0;
    TTL_LeptonGenMatchGrandmother10Status = 0;
    TTL_LeptonGenMatchGrandmother11Status = 0;
    TTL_DitauVisibleMass = 0;
    TTL_DitauMETMass = 0;
    TTL_DitauCosDeltaPhi = 0;
    TTL_DitauDeltaR = 0;
    TTL_Tau1LeptonDeltaR = 0;
    TTL_Tau2LeptonDeltaR = 0;
    TTL_HT = 0;
    TTL_NumCSVLbtagJets = 0;
    TTL_NumCSVMbtagJets = 0;
    TTL_NumCSVTbtagJets = 0;
    TTL_NumNonCSVLbtagJets = 0;
    TTL_NumNonCSVMbtagJets = 0;
    TTL_NumNonCSVTbtagJets = 0;
    TTL_NumCleanCSVLbtagJets = 0;
    TTL_NumCleanCSVMbtagJets = 0;
    TTL_NumCleanCSVTbtagJets = 0;
    TTL_NumCleanNonCSVLbtagJets = 0;
    TTL_NumCleanNonCSVMbtagJets = 0;
    TTL_NumCleanNonCSVTbtagJets = 0;
    TTL_CleanJetIndices = 0;
    TTL_LeptonEventWeight = 0;
    CSVeventWeight = 0;
    CSVeventWeightHFdown = 0;
    CSVeventWeightHFup = 0;
    CSVeventWeightLFdown = 0;
    CSVeventWeightLFup = 0;
    CSVeventWeightHFStats1down = 0;
    CSVeventWeightHFStats1up = 0;
    CSVeventWeightLFStats1down = 0;
    CSVeventWeightLFStats1up = 0;
    CSVeventWeightHFStats2down = 0;
    CSVeventWeightHFStats2up = 0;
    CSVeventWeightLFStats2down = 0;
    CSVeventWeightLFStats2up = 0;
    CSVeventWeightCErr1up = 0;
    CSVeventWeightCErr1down = 0;
    CSVeventWeightCErr2up = 0;
    CSVeventWeightCErr2down = 0;
    // >>> End null <<<
}

void
ttl::Branches::SetBranchAddresses()
{
    // >>> Begin address <<<
    fChain->SetBranchAddress("Ev_runNumber", &Ev_runNumber);
    fChain->SetBranchAddress("Ev_eventNumber", &Ev_eventNumber);
    fChain->SetBranchAddress("Ev_lumiBlock", &Ev_lumiBlock);
    fChain->SetBranchAddress("Ev_puWeight", &puWeight);
    fChain->SetBranchAddress("Ev_puWeightUp", &puWeightUp);
    fChain->SetBranchAddress("Ev_puWeightDown", &puWeightDown);
    fChain->SetBranchAddress("Ev_topPtWeight", &topPtWeight);
    fChain->SetBranchAddress("Ev_topPtWeightUp", &topPtWeightUp);
    fChain->SetBranchAddress("Ev_topPtWeightDown", &topPtWeightDown);
    fChain->SetBranchAddress("Ev_q2WeightUp", &q2WeightUp);
    fChain->SetBranchAddress("Ev_q2WeightDown", &q2WeightDown);
    fChain->SetBranchAddress("Ev_MET", &Ev_MET);
    fChain->SetBranchAddress("Ev_METphi", &Ev_METphi);
    fChain->SetBranchAddress("Ev_IsTauEvent", &Ev_IsTauEvent);
    fChain->SetBranchAddress("Ev_puWeight2012A", &puWeight2012A);
    fChain->SetBranchAddress("Ev_puWeight2012B", &puWeight2012B);
    fChain->SetBranchAddress("Ev_puWeight2012C", &puWeight2012C);
    fChain->SetBranchAddress("Ev_puWeight2012D", &puWeight2012D);
    fChain->SetBranchAddress("Ev_puWeight2012AB", &puWeight2012AB);
    fChain->SetBranchAddress("Ev_puWeight2012BC", &puWeight2012BC);
    fChain->SetBranchAddress("Ev_puWeight2012CD", &puWeight2012CD);
    fChain->SetBranchAddress("Ev_puWeight2012ABC", &puWeight2012ABC);
    fChain->SetBranchAddress("V_NumVertices", &V_NumVertices);
    fChain->SetBranchAddress("V_NumInteractionsBXm1", &V_NumInteractionsBXm1);
    fChain->SetBranchAddress("V_NumInteractionsBX0", &V_NumInteractionsBX0);
    fChain->SetBranchAddress("V_NumInteractionsBXp1", &V_NumInteractionsBXp1);
    fChain->SetBranchAddress("V_Xcoord", &V_Xcoord);
    fChain->SetBranchAddress("V_XcoordErr", &V_XcoordErr);
    fChain->SetBranchAddress("V_Ycoord", &V_Ycoord);
    fChain->SetBranchAddress("V_YcoordErr", &V_YcoordErr);
    fChain->SetBranchAddress("V_Zcoord", &V_Zcoord);
    fChain->SetBranchAddress("V_ZcoordErr", &V_ZcoordErr);
    fChain->SetBranchAddress("V_Rho", &V_Rho);
    fChain->SetBranchAddress("V_NumDOF", &V_NumDOF);
    fChain->SetBranchAddress("V_NormChiSquared", &V_NormChiSquared);
    fChain->SetBranchAddress("GT_NumGenTaus", &GT_NumGenTaus);
    fChain->SetBranchAddress("GT_MomentumRank", &GT_MomentumRank);
    fChain->SetBranchAddress("GT_Pt", &GT_Pt);
    fChain->SetBranchAddress("GT_Eta", &GT_Eta);
    fChain->SetBranchAddress("GT_Phi", &GT_Phi);
    fChain->SetBranchAddress("GT_VisPt", &GT_VisPt);
    fChain->SetBranchAddress("GT_VisEta", &GT_VisEta);
    fChain->SetBranchAddress("GT_VisPhi", &GT_VisPhi);
    fChain->SetBranchAddress("GT_ToElectron", &GT_ToElectron);
    fChain->SetBranchAddress("GT_ToMuon", &GT_ToMuon);
    fChain->SetBranchAddress("GT_ToHadrons", &GT_ToHadrons);
    fChain->SetBranchAddress("GT_ParentId", &GT_ParentId);
    fChain->SetBranchAddress("GT_ParentP", &GT_ParentP);
    fChain->SetBranchAddress("GT_ParentPt", &GT_ParentPt);
    fChain->SetBranchAddress("GT_ParentEta", &GT_ParentEta);
    fChain->SetBranchAddress("GT_ParentPhi", &GT_ParentPhi);
    fChain->SetBranchAddress("GJ_NumGenJets", &GJ_NumGenJets);
    fChain->SetBranchAddress("GJ_MomentumRank", &GJ_MomentumRank);
    fChain->SetBranchAddress("GJ_Pt", &GJ_Pt);
    fChain->SetBranchAddress("GJ_Eta", &GJ_Eta);
    fChain->SetBranchAddress("GJ_Phi", &GJ_Phi);
    fChain->SetBranchAddress("GJ_IsBjet", &GJ_IsBjet);
    fChain->SetBranchAddress("T_NumTaus", &T_NumTaus);
    fChain->SetBranchAddress("T_MomentumRank", &T_MomentumRank);
    fChain->SetBranchAddress("T_Pt", &T_Pt);
    fChain->SetBranchAddress("T_Eta", &T_Eta);
    fChain->SetBranchAddress("T_Phi", &T_Phi);
    fChain->SetBranchAddress("T_NProngs", &T_NProngs);
    fChain->SetBranchAddress("T_NSignalGammas", &T_NSignalGammas);
    fChain->SetBranchAddress("T_NSignalNeutrals", &T_NSignalNeutrals);
    fChain->SetBranchAddress("T_DecayMode", &T_DecayMode);
    fChain->SetBranchAddress("T_EmFraction", &T_EmFraction);
    fChain->SetBranchAddress("T_IsInTheCracks", &T_IsInTheCracks);
    fChain->SetBranchAddress("T_HPSagainstElectronDeadECAL", &T_HPSagainstElectronDeadECAL);
    fChain->SetBranchAddress("T_HPSagainstElectronLoose", &T_HPSagainstElectronLoose);
    fChain->SetBranchAddress("T_HPSagainstElectronLooseMVA2", &T_HPSagainstElectronLooseMVA2);
    fChain->SetBranchAddress("T_HPSagainstElectronLooseMVA3", &T_HPSagainstElectronLooseMVA3);
    fChain->SetBranchAddress("T_HPSagainstElectronMVA", &T_HPSagainstElectronMVA);
    fChain->SetBranchAddress("T_HPSagainstElectronMVA2category", &T_HPSagainstElectronMVA2category);
    fChain->SetBranchAddress("T_HPSagainstElectronMVA2raw", &T_HPSagainstElectronMVA2raw);
    fChain->SetBranchAddress("T_HPSagainstElectronMVA3category", &T_HPSagainstElectronMVA3category);
    fChain->SetBranchAddress("T_HPSagainstElectronMVA3raw", &T_HPSagainstElectronMVA3raw);
    fChain->SetBranchAddress("T_HPSagainstElectronMedium", &T_HPSagainstElectronMedium);
    fChain->SetBranchAddress("T_HPSagainstElectronMediumMVA2", &T_HPSagainstElectronMediumMVA2);
    fChain->SetBranchAddress("T_HPSagainstElectronMediumMVA3", &T_HPSagainstElectronMediumMVA3);
    fChain->SetBranchAddress("T_HPSagainstElectronTight", &T_HPSagainstElectronTight);
    fChain->SetBranchAddress("T_HPSagainstElectronTightMVA2", &T_HPSagainstElectronTightMVA2);
    fChain->SetBranchAddress("T_HPSagainstElectronTightMVA3", &T_HPSagainstElectronTightMVA3);
    fChain->SetBranchAddress("T_HPSagainstElectronVLooseMVA2", &T_HPSagainstElectronVLooseMVA2);
    fChain->SetBranchAddress("T_HPSagainstElectronVTightMVA3", &T_HPSagainstElectronVTightMVA3);
    fChain->SetBranchAddress("T_HPSagainstMuonLoose", &T_HPSagainstMuonLoose);
    fChain->SetBranchAddress("T_HPSagainstMuonLoose2", &T_HPSagainstMuonLoose2);
    fChain->SetBranchAddress("T_HPSagainstMuonMedium", &T_HPSagainstMuonMedium);
    fChain->SetBranchAddress("T_HPSagainstMuonMedium2", &T_HPSagainstMuonMedium2);
    fChain->SetBranchAddress("T_HPSagainstMuonTight", &T_HPSagainstMuonTight);
    fChain->SetBranchAddress("T_HPSagainstMuonTight2", &T_HPSagainstMuonTight2);
    fChain->SetBranchAddress("T_HPSbyCombinedIsolationDeltaBetaCorrRaw", &T_HPSbyCombinedIsolationDeltaBetaCorrRaw);
    fChain->SetBranchAddress("T_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits", &T_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits);
    fChain->SetBranchAddress("T_HPSbyIsolationMVA2raw", &T_HPSbyIsolationMVA2raw);
    fChain->SetBranchAddress("T_HPSbyLooseCombinedIsolationDeltaBetaCorr", &T_HPSbyLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("T_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits", &T_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("T_HPSbyLooseIsolationMVA", &T_HPSbyLooseIsolationMVA);
    fChain->SetBranchAddress("T_HPSbyLooseIsolationMVA2", &T_HPSbyLooseIsolationMVA2);
    fChain->SetBranchAddress("T_HPSbyMediumCombinedIsolationDeltaBetaCorr", &T_HPSbyMediumCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("T_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits", &T_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("T_HPSbyMediumIsolationMVA", &T_HPSbyMediumIsolationMVA);
    fChain->SetBranchAddress("T_HPSbyMediumIsolationMVA2", &T_HPSbyMediumIsolationMVA2);
    fChain->SetBranchAddress("T_HPSbyTightCombinedIsolationDeltaBetaCorr", &T_HPSbyTightCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("T_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits", &T_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("T_HPSbyTightIsolationMVA", &T_HPSbyTightIsolationMVA);
    fChain->SetBranchAddress("T_HPSbyTightIsolationMVA2", &T_HPSbyTightIsolationMVA2);
    fChain->SetBranchAddress("T_HPSbyVLooseCombinedIsolationDeltaBetaCorr", &T_HPSbyVLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("T_HPSdecayModeFinding", &T_HPSdecayModeFinding);
    fChain->SetBranchAddress("T_HPSbyIsolationMVAraw", &T_HPSbyIsolationMVAraw);
    fChain->SetBranchAddress("T_LTPt", &T_LTPt);
    fChain->SetBranchAddress("T_Charge", &T_Charge);
    fChain->SetBranchAddress("T_LTvalid", &T_LTvalid);
    fChain->SetBranchAddress("T_LTIpVtdxy", &T_LTIpVtdxy);
    fChain->SetBranchAddress("T_LTIpVtdz", &T_LTIpVtdz);
    fChain->SetBranchAddress("T_LTIpVtdxyError", &T_LTIpVtdxyError);
    fChain->SetBranchAddress("T_LTIpVtdzError", &T_LTIpVtdzError);
    fChain->SetBranchAddress("T_LTvx", &T_LTvx);
    fChain->SetBranchAddress("T_LTvy", &T_LTvy);
    fChain->SetBranchAddress("T_LTvz", &T_LTvz);
    fChain->SetBranchAddress("T_LTValidHits", &T_LTValidHits);
    fChain->SetBranchAddress("T_LTNormChiSqrd", &T_LTNormChiSqrd);
    fChain->SetBranchAddress("T_TauGenMatchDaughter0Id", &T_TauGenMatchDaughter0Id);
    fChain->SetBranchAddress("T_TauGenMatchDaughter1Id", &T_TauGenMatchDaughter1Id);
    fChain->SetBranchAddress("T_TauGenMatchId", &T_TauGenMatchId);
    fChain->SetBranchAddress("T_TauGenMatchMother0Id", &T_TauGenMatchMother0Id);
    fChain->SetBranchAddress("T_TauGenMatchMother1Id", &T_TauGenMatchMother1Id);
    fChain->SetBranchAddress("T_TauGenMatchGrandmother00Id", &T_TauGenMatchGrandmother00Id);
    fChain->SetBranchAddress("T_TauGenMatchGrandmother01Id", &T_TauGenMatchGrandmother01Id);
    fChain->SetBranchAddress("T_TauGenMatchGrandmother10Id", &T_TauGenMatchGrandmother10Id);
    fChain->SetBranchAddress("T_TauGenMatchGrandmother11Id", &T_TauGenMatchGrandmother11Id);
    fChain->SetBranchAddress("T_TauGenMatchDaughter0Status", &T_TauGenMatchDaughter0Status);
    fChain->SetBranchAddress("T_TauGenMatchDaughter1Status", &T_TauGenMatchDaughter1Status);
    fChain->SetBranchAddress("T_TauGenMatchStatus", &T_TauGenMatchStatus);
    fChain->SetBranchAddress("T_TauGenMatchMother0Status", &T_TauGenMatchMother0Status);
    fChain->SetBranchAddress("T_TauGenMatchMother1Status", &T_TauGenMatchMother1Status);
    fChain->SetBranchAddress("T_TauGenMatchGrandmother00Status", &T_TauGenMatchGrandmother00Status);
    fChain->SetBranchAddress("T_TauGenMatchGrandmother01Status", &T_TauGenMatchGrandmother01Status);
    fChain->SetBranchAddress("T_TauGenMatchGrandmother10Status", &T_TauGenMatchGrandmother10Status);
    fChain->SetBranchAddress("T_TauGenMatchGrandmother11Status", &T_TauGenMatchGrandmother11Status);
    fChain->SetBranchAddress("E_NumElectrons", &E_NumElectrons);
    fChain->SetBranchAddress("E_MomentumRank", &E_MomentumRank);
    fChain->SetBranchAddress("E_Pt", &E_Pt);
    fChain->SetBranchAddress("E_Eta", &E_Eta);
    fChain->SetBranchAddress("E_Phi", &E_Phi);
    fChain->SetBranchAddress("E_IsTightElectron", &E_IsTightElectron);
    fChain->SetBranchAddress("E_IsLooseElectron", &E_IsLooseElectron);
    fChain->SetBranchAddress("E_ElectronGenMatchDaughter0Id", &E_ElectronGenMatchDaughter0Id);
    fChain->SetBranchAddress("E_ElectronGenMatchDaughter1Id", &E_ElectronGenMatchDaughter1Id);
    fChain->SetBranchAddress("E_ElectronGenMatchId", &E_ElectronGenMatchId);
    fChain->SetBranchAddress("E_ElectronGenMatchMother0Id", &E_ElectronGenMatchMother0Id);
    fChain->SetBranchAddress("E_ElectronGenMatchMother1Id", &E_ElectronGenMatchMother1Id);
    fChain->SetBranchAddress("E_ElectronGenMatchGrandmother00Id", &E_ElectronGenMatchGrandmother00Id);
    fChain->SetBranchAddress("E_ElectronGenMatchGrandmother01Id", &E_ElectronGenMatchGrandmother01Id);
    fChain->SetBranchAddress("E_ElectronGenMatchGrandmother10Id", &E_ElectronGenMatchGrandmother10Id);
    fChain->SetBranchAddress("E_ElectronGenMatchGrandmother11Id", &E_ElectronGenMatchGrandmother11Id);
    fChain->SetBranchAddress("E_ElectronGenMatchDaughter0Status", &E_ElectronGenMatchDaughter0Status);
    fChain->SetBranchAddress("E_ElectronGenMatchDaughter1Status", &E_ElectronGenMatchDaughter1Status);
    fChain->SetBranchAddress("E_ElectronGenMatchStatus", &E_ElectronGenMatchStatus);
    fChain->SetBranchAddress("E_ElectronGenMatchMother0Status", &E_ElectronGenMatchMother0Status);
    fChain->SetBranchAddress("E_ElectronGenMatchMother1Status", &E_ElectronGenMatchMother1Status);
    fChain->SetBranchAddress("E_ElectronGenMatchGrandmother00Status", &E_ElectronGenMatchGrandmother00Status);
    fChain->SetBranchAddress("E_ElectronGenMatchGrandmother01Status", &E_ElectronGenMatchGrandmother01Status);
    fChain->SetBranchAddress("E_ElectronGenMatchGrandmother10Status", &E_ElectronGenMatchGrandmother10Status);
    fChain->SetBranchAddress("E_ElectronGenMatchGrandmother11Status", &E_ElectronGenMatchGrandmother11Status);
    fChain->SetBranchAddress("M_NumMuons", &M_NumMuons);
    fChain->SetBranchAddress("M_MomentumRank", &M_MomentumRank);
    fChain->SetBranchAddress("M_Pt", &M_Pt);
    fChain->SetBranchAddress("M_Eta", &M_Eta);
    fChain->SetBranchAddress("M_Phi", &M_Phi);
    fChain->SetBranchAddress("M_RelIso", &M_RelIso);
    fChain->SetBranchAddress("M_IsTightMuon", &M_IsTightMuon);
    fChain->SetBranchAddress("M_IsLooseMuon", &M_IsLooseMuon);
    fChain->SetBranchAddress("M_MuonGenMatchDaughter0Id", &M_MuonGenMatchDaughter0Id);
    fChain->SetBranchAddress("M_MuonGenMatchDaughter1Id", &M_MuonGenMatchDaughter1Id);
    fChain->SetBranchAddress("M_MuonGenMatchId", &M_MuonGenMatchId);
    fChain->SetBranchAddress("M_MuonGenMatchMother0Id", &M_MuonGenMatchMother0Id);
    fChain->SetBranchAddress("M_MuonGenMatchMother1Id", &M_MuonGenMatchMother1Id);
    fChain->SetBranchAddress("M_MuonGenMatchGrandmother00Id", &M_MuonGenMatchGrandmother00Id);
    fChain->SetBranchAddress("M_MuonGenMatchGrandmother01Id", &M_MuonGenMatchGrandmother01Id);
    fChain->SetBranchAddress("M_MuonGenMatchGrandmother10Id", &M_MuonGenMatchGrandmother10Id);
    fChain->SetBranchAddress("M_MuonGenMatchGrandmother11Id", &M_MuonGenMatchGrandmother11Id);
    fChain->SetBranchAddress("M_MuonGenMatchDaughter0Status", &M_MuonGenMatchDaughter0Status);
    fChain->SetBranchAddress("M_MuonGenMatchDaughter1Status", &M_MuonGenMatchDaughter1Status);
    fChain->SetBranchAddress("M_MuonGenMatchStatus", &M_MuonGenMatchStatus);
    fChain->SetBranchAddress("M_MuonGenMatchMother0Status", &M_MuonGenMatchMother0Status);
    fChain->SetBranchAddress("M_MuonGenMatchMother1Status", &M_MuonGenMatchMother1Status);
    fChain->SetBranchAddress("M_MuonGenMatchGrandmother00Status", &M_MuonGenMatchGrandmother00Status);
    fChain->SetBranchAddress("M_MuonGenMatchGrandmother01Status", &M_MuonGenMatchGrandmother01Status);
    fChain->SetBranchAddress("M_MuonGenMatchGrandmother10Status", &M_MuonGenMatchGrandmother10Status);
    fChain->SetBranchAddress("M_MuonGenMatchGrandmother11Status", &M_MuonGenMatchGrandmother11Status);
    fChain->SetBranchAddress("J_NumJets", &J_NumJets);
    fChain->SetBranchAddress("J_MomentumRank", &J_MomentumRank);
    fChain->SetBranchAddress("J_Pt", &J_Pt);
    fChain->SetBranchAddress("J_Eta", &J_Eta);
    fChain->SetBranchAddress("J_Phi", &J_Phi);
    fChain->SetBranchAddress("J_combSecVtxBTag", &J_combSecVtxBTag);
    fChain->SetBranchAddress("J_combSecVtxLooseBTag", &J_combSecVtxLooseBTag);
    fChain->SetBranchAddress("J_combSecVtxMediumBTag", &J_combSecVtxMediumBTag);
    fChain->SetBranchAddress("J_combSecVtxTightBTag", &J_combSecVtxTightBTag);
    fChain->SetBranchAddress("TTL_NumTaus", &TTL_NumTaus);
    fChain->SetBranchAddress("TTL_NumMuons", &TTL_NumMuons);
    fChain->SetBranchAddress("TTL_NumElectrons", &TTL_NumElectrons);
    fChain->SetBranchAddress("TTL_NumLeptons", &TTL_NumLeptons);
    fChain->SetBranchAddress("TTL_NumCombos", &TTL_NumCombos);
    fChain->SetBranchAddress("TTL_MomentumRank", &TTL_MomentumRank);
    fChain->SetBranchAddress("TTL_Tau1MomentumRank", &TTL_Tau1MomentumRank);
    fChain->SetBranchAddress("TTL_Tau1Pt", &TTL_Tau1Pt);
    fChain->SetBranchAddress("TTL_Tau1Eta", &TTL_Tau1Eta);
    fChain->SetBranchAddress("TTL_Tau1Phi", &TTL_Tau1Phi);
    fChain->SetBranchAddress("TTL_Tau1NProngs", &TTL_Tau1NProngs);
    fChain->SetBranchAddress("TTL_Tau1NSignalGammas", &TTL_Tau1NSignalGammas);
    fChain->SetBranchAddress("TTL_Tau1NSignalNeutrals", &TTL_Tau1NSignalNeutrals);
    fChain->SetBranchAddress("TTL_Tau1DecayMode", &TTL_Tau1DecayMode);
    fChain->SetBranchAddress("TTL_Tau1EmFraction", &TTL_Tau1EmFraction);
    fChain->SetBranchAddress("TTL_Tau1IsInTheCracks", &TTL_Tau1IsInTheCracks);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronDeadECAL", &TTL_Tau1HPSagainstElectronDeadECAL);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronLoose", &TTL_Tau1HPSagainstElectronLoose);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronLooseMVA2", &TTL_Tau1HPSagainstElectronLooseMVA2);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronLooseMVA3", &TTL_Tau1HPSagainstElectronLooseMVA3);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronMVA", &TTL_Tau1HPSagainstElectronMVA);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronMVA2category", &TTL_Tau1HPSagainstElectronMVA2category);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronMVA2raw", &TTL_Tau1HPSagainstElectronMVA2raw);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronMVA3category", &TTL_Tau1HPSagainstElectronMVA3category);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronMVA3raw", &TTL_Tau1HPSagainstElectronMVA3raw);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronMedium", &TTL_Tau1HPSagainstElectronMedium);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronMediumMVA2", &TTL_Tau1HPSagainstElectronMediumMVA2);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronMediumMVA3", &TTL_Tau1HPSagainstElectronMediumMVA3);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronTight", &TTL_Tau1HPSagainstElectronTight);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronTightMVA2", &TTL_Tau1HPSagainstElectronTightMVA2);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronTightMVA3", &TTL_Tau1HPSagainstElectronTightMVA3);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronVLooseMVA2", &TTL_Tau1HPSagainstElectronVLooseMVA2);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronVTightMVA3", &TTL_Tau1HPSagainstElectronVTightMVA3);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstMuonLoose", &TTL_Tau1HPSagainstMuonLoose);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstMuonLoose2", &TTL_Tau1HPSagainstMuonLoose2);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstMuonMedium", &TTL_Tau1HPSagainstMuonMedium);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstMuonMedium2", &TTL_Tau1HPSagainstMuonMedium2);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstMuonTight", &TTL_Tau1HPSagainstMuonTight);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstMuonTight2", &TTL_Tau1HPSagainstMuonTight2);
    fChain->SetBranchAddress("TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw", &TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw);
    fChain->SetBranchAddress("TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits", &TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits);
    fChain->SetBranchAddress("TTL_Tau1HPSbyIsolationMVA2raw", &TTL_Tau1HPSbyIsolationMVA2raw);
    fChain->SetBranchAddress("TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr", &TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits", &TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("TTL_Tau1HPSbyLooseIsolationMVA", &TTL_Tau1HPSbyLooseIsolationMVA);
    fChain->SetBranchAddress("TTL_Tau1HPSbyLooseIsolationMVA2", &TTL_Tau1HPSbyLooseIsolationMVA2);
    fChain->SetBranchAddress("TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr", &TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits", &TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("TTL_Tau1HPSbyMediumIsolationMVA", &TTL_Tau1HPSbyMediumIsolationMVA);
    fChain->SetBranchAddress("TTL_Tau1HPSbyMediumIsolationMVA2", &TTL_Tau1HPSbyMediumIsolationMVA2);
    fChain->SetBranchAddress("TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr", &TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr3Hits", &TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("TTL_Tau1HPSbyTightIsolationMVA", &TTL_Tau1HPSbyTightIsolationMVA);
    fChain->SetBranchAddress("TTL_Tau1HPSbyTightIsolationMVA2", &TTL_Tau1HPSbyTightIsolationMVA2);
    fChain->SetBranchAddress("TTL_Tau1HPSbyVLooseCombinedIsolationDeltaBetaCorr", &TTL_Tau1HPSbyVLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TTL_Tau1HPSdecayModeFinding", &TTL_Tau1HPSdecayModeFinding);
    fChain->SetBranchAddress("TTL_Tau1HPSbyIsolationMVAraw", &TTL_Tau1HPSbyIsolationMVAraw);
    fChain->SetBranchAddress("TTL_Tau1LTPt", &TTL_Tau1LTPt);
    fChain->SetBranchAddress("TTL_Tau1Charge", &TTL_Tau1Charge);
    fChain->SetBranchAddress("TTL_Tau1LTvalid", &TTL_Tau1LTvalid);
    fChain->SetBranchAddress("TTL_Tau1LTIpVtdxy", &TTL_Tau1LTIpVtdxy);
    fChain->SetBranchAddress("TTL_Tau1LTIpVtdz", &TTL_Tau1LTIpVtdz);
    fChain->SetBranchAddress("TTL_Tau1LTIpVtdxyError", &TTL_Tau1LTIpVtdxyError);
    fChain->SetBranchAddress("TTL_Tau1LTIpVtdzError", &TTL_Tau1LTIpVtdzError);
    fChain->SetBranchAddress("TTL_Tau1LTvx", &TTL_Tau1LTvx);
    fChain->SetBranchAddress("TTL_Tau1LTvy", &TTL_Tau1LTvy);
    fChain->SetBranchAddress("TTL_Tau1LTvz", &TTL_Tau1LTvz);
    fChain->SetBranchAddress("TTL_Tau1LTValidHits", &TTL_Tau1LTValidHits);
    fChain->SetBranchAddress("TTL_Tau1LTNormChiSqrd", &TTL_Tau1LTNormChiSqrd);
    fChain->SetBranchAddress("TTL_Tau1GenMatchDaughter0Id", &TTL_Tau1GenMatchDaughter0Id);
    fChain->SetBranchAddress("TTL_Tau1GenMatchDaughter1Id", &TTL_Tau1GenMatchDaughter1Id);
    fChain->SetBranchAddress("TTL_Tau1GenMatchId", &TTL_Tau1GenMatchId);
    fChain->SetBranchAddress("TTL_Tau1GenMatchMother0Id", &TTL_Tau1GenMatchMother0Id);
    fChain->SetBranchAddress("TTL_Tau1GenMatchMother1Id", &TTL_Tau1GenMatchMother1Id);
    fChain->SetBranchAddress("TTL_Tau1GenMatchGrandmother00Id", &TTL_Tau1GenMatchGrandmother00Id);
    fChain->SetBranchAddress("TTL_Tau1GenMatchGrandmother01Id", &TTL_Tau1GenMatchGrandmother01Id);
    fChain->SetBranchAddress("TTL_Tau1GenMatchGrandmother10Id", &TTL_Tau1GenMatchGrandmother10Id);
    fChain->SetBranchAddress("TTL_Tau1GenMatchGrandmother11Id", &TTL_Tau1GenMatchGrandmother11Id);
    fChain->SetBranchAddress("TTL_Tau1GenMatchDaughter0Status", &TTL_Tau1GenMatchDaughter0Status);
    fChain->SetBranchAddress("TTL_Tau1GenMatchDaughter1Status", &TTL_Tau1GenMatchDaughter1Status);
    fChain->SetBranchAddress("TTL_Tau1GenMatchStatus", &TTL_Tau1GenMatchStatus);
    fChain->SetBranchAddress("TTL_Tau1GenMatchMother0Status", &TTL_Tau1GenMatchMother0Status);
    fChain->SetBranchAddress("TTL_Tau1GenMatchMother1Status", &TTL_Tau1GenMatchMother1Status);
    fChain->SetBranchAddress("TTL_Tau1GenMatchGrandmother00Status", &TTL_Tau1GenMatchGrandmother00Status);
    fChain->SetBranchAddress("TTL_Tau1GenMatchGrandmother01Status", &TTL_Tau1GenMatchGrandmother01Status);
    fChain->SetBranchAddress("TTL_Tau1GenMatchGrandmother10Status", &TTL_Tau1GenMatchGrandmother10Status);
    fChain->SetBranchAddress("TTL_Tau1GenMatchGrandmother11Status", &TTL_Tau1GenMatchGrandmother11Status);
    fChain->SetBranchAddress("TTL_Tau2MomentumRank", &TTL_Tau2MomentumRank);
    fChain->SetBranchAddress("TTL_Tau2Pt", &TTL_Tau2Pt);
    fChain->SetBranchAddress("TTL_Tau2Eta", &TTL_Tau2Eta);
    fChain->SetBranchAddress("TTL_Tau2Phi", &TTL_Tau2Phi);
    fChain->SetBranchAddress("TTL_Tau2NProngs", &TTL_Tau2NProngs);
    fChain->SetBranchAddress("TTL_Tau2NSignalGammas", &TTL_Tau2NSignalGammas);
    fChain->SetBranchAddress("TTL_Tau2NSignalNeutrals", &TTL_Tau2NSignalNeutrals);
    fChain->SetBranchAddress("TTL_Tau2DecayMode", &TTL_Tau2DecayMode);
    fChain->SetBranchAddress("TTL_Tau2EmFraction", &TTL_Tau2EmFraction);
    fChain->SetBranchAddress("TTL_Tau2IsInTheCracks", &TTL_Tau2IsInTheCracks);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronDeadECAL", &TTL_Tau2HPSagainstElectronDeadECAL);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronLoose", &TTL_Tau2HPSagainstElectronLoose);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronLooseMVA2", &TTL_Tau2HPSagainstElectronLooseMVA2);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronLooseMVA3", &TTL_Tau2HPSagainstElectronLooseMVA3);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronMVA", &TTL_Tau2HPSagainstElectronMVA);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronMVA2category", &TTL_Tau2HPSagainstElectronMVA2category);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronMVA2raw", &TTL_Tau2HPSagainstElectronMVA2raw);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronMVA3category", &TTL_Tau2HPSagainstElectronMVA3category);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronMVA3raw", &TTL_Tau2HPSagainstElectronMVA3raw);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronMedium", &TTL_Tau2HPSagainstElectronMedium);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronMediumMVA2", &TTL_Tau2HPSagainstElectronMediumMVA2);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronMediumMVA3", &TTL_Tau2HPSagainstElectronMediumMVA3);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronTight", &TTL_Tau2HPSagainstElectronTight);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronTightMVA2", &TTL_Tau2HPSagainstElectronTightMVA2);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronTightMVA3", &TTL_Tau2HPSagainstElectronTightMVA3);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronVLooseMVA2", &TTL_Tau2HPSagainstElectronVLooseMVA2);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronVTightMVA3", &TTL_Tau2HPSagainstElectronVTightMVA3);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstMuonLoose", &TTL_Tau2HPSagainstMuonLoose);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstMuonLoose2", &TTL_Tau2HPSagainstMuonLoose2);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstMuonMedium", &TTL_Tau2HPSagainstMuonMedium);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstMuonMedium2", &TTL_Tau2HPSagainstMuonMedium2);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstMuonTight", &TTL_Tau2HPSagainstMuonTight);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstMuonTight2", &TTL_Tau2HPSagainstMuonTight2);
    fChain->SetBranchAddress("TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw", &TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw);
    fChain->SetBranchAddress("TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits", &TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits);
    fChain->SetBranchAddress("TTL_Tau2HPSbyIsolationMVA2raw", &TTL_Tau2HPSbyIsolationMVA2raw);
    fChain->SetBranchAddress("TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr", &TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits", &TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("TTL_Tau2HPSbyLooseIsolationMVA", &TTL_Tau2HPSbyLooseIsolationMVA);
    fChain->SetBranchAddress("TTL_Tau2HPSbyLooseIsolationMVA2", &TTL_Tau2HPSbyLooseIsolationMVA2);
    fChain->SetBranchAddress("TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr", &TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits", &TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("TTL_Tau2HPSbyMediumIsolationMVA", &TTL_Tau2HPSbyMediumIsolationMVA);
    fChain->SetBranchAddress("TTL_Tau2HPSbyMediumIsolationMVA2", &TTL_Tau2HPSbyMediumIsolationMVA2);
    fChain->SetBranchAddress("TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr", &TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr3Hits", &TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("TTL_Tau2HPSbyTightIsolationMVA", &TTL_Tau2HPSbyTightIsolationMVA);
    fChain->SetBranchAddress("TTL_Tau2HPSbyTightIsolationMVA2", &TTL_Tau2HPSbyTightIsolationMVA2);
    fChain->SetBranchAddress("TTL_Tau2HPSbyVLooseCombinedIsolationDeltaBetaCorr", &TTL_Tau2HPSbyVLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TTL_Tau2HPSdecayModeFinding", &TTL_Tau2HPSdecayModeFinding);
    fChain->SetBranchAddress("TTL_Tau2HPSbyIsolationMVAraw", &TTL_Tau2HPSbyIsolationMVAraw);
    fChain->SetBranchAddress("TTL_Tau2LTPt", &TTL_Tau2LTPt);
    fChain->SetBranchAddress("TTL_Tau2Charge", &TTL_Tau2Charge);
    fChain->SetBranchAddress("TTL_Tau2LTvalid", &TTL_Tau2LTvalid);
    fChain->SetBranchAddress("TTL_Tau2LTIpVtdxy", &TTL_Tau2LTIpVtdxy);
    fChain->SetBranchAddress("TTL_Tau2LTIpVtdz", &TTL_Tau2LTIpVtdz);
    fChain->SetBranchAddress("TTL_Tau2LTIpVtdxyError", &TTL_Tau2LTIpVtdxyError);
    fChain->SetBranchAddress("TTL_Tau2LTIpVtdzError", &TTL_Tau2LTIpVtdzError);
    fChain->SetBranchAddress("TTL_Tau2LTvx", &TTL_Tau2LTvx);
    fChain->SetBranchAddress("TTL_Tau2LTvy", &TTL_Tau2LTvy);
    fChain->SetBranchAddress("TTL_Tau2LTvz", &TTL_Tau2LTvz);
    fChain->SetBranchAddress("TTL_Tau2LTValidHits", &TTL_Tau2LTValidHits);
    fChain->SetBranchAddress("TTL_Tau2LTNormChiSqrd", &TTL_Tau2LTNormChiSqrd);
    fChain->SetBranchAddress("TTL_Tau2GenMatchDaughter0Id", &TTL_Tau2GenMatchDaughter0Id);
    fChain->SetBranchAddress("TTL_Tau2GenMatchDaughter1Id", &TTL_Tau2GenMatchDaughter1Id);
    fChain->SetBranchAddress("TTL_Tau2GenMatchId", &TTL_Tau2GenMatchId);
    fChain->SetBranchAddress("TTL_Tau2GenMatchMother0Id", &TTL_Tau2GenMatchMother0Id);
    fChain->SetBranchAddress("TTL_Tau2GenMatchMother1Id", &TTL_Tau2GenMatchMother1Id);
    fChain->SetBranchAddress("TTL_Tau2GenMatchGrandmother00Id", &TTL_Tau2GenMatchGrandmother00Id);
    fChain->SetBranchAddress("TTL_Tau2GenMatchGrandmother01Id", &TTL_Tau2GenMatchGrandmother01Id);
    fChain->SetBranchAddress("TTL_Tau2GenMatchGrandmother10Id", &TTL_Tau2GenMatchGrandmother10Id);
    fChain->SetBranchAddress("TTL_Tau2GenMatchGrandmother11Id", &TTL_Tau2GenMatchGrandmother11Id);
    fChain->SetBranchAddress("TTL_Tau2GenMatchDaughter0Status", &TTL_Tau2GenMatchDaughter0Status);
    fChain->SetBranchAddress("TTL_Tau2GenMatchDaughter1Status", &TTL_Tau2GenMatchDaughter1Status);
    fChain->SetBranchAddress("TTL_Tau2GenMatchStatus", &TTL_Tau2GenMatchStatus);
    fChain->SetBranchAddress("TTL_Tau2GenMatchMother0Status", &TTL_Tau2GenMatchMother0Status);
    fChain->SetBranchAddress("TTL_Tau2GenMatchMother1Status", &TTL_Tau2GenMatchMother1Status);
    fChain->SetBranchAddress("TTL_Tau2GenMatchGrandmother00Status", &TTL_Tau2GenMatchGrandmother00Status);
    fChain->SetBranchAddress("TTL_Tau2GenMatchGrandmother01Status", &TTL_Tau2GenMatchGrandmother01Status);
    fChain->SetBranchAddress("TTL_Tau2GenMatchGrandmother10Status", &TTL_Tau2GenMatchGrandmother10Status);
    fChain->SetBranchAddress("TTL_Tau2GenMatchGrandmother11Status", &TTL_Tau2GenMatchGrandmother11Status);
    fChain->SetBranchAddress("TTL_MuonMomentumRank", &TTL_MuonMomentumRank);
    fChain->SetBranchAddress("TTL_ElectronMomentumRank", &TTL_ElectronMomentumRank);
    fChain->SetBranchAddress("TTL_LeptonMomentumRank", &TTL_LeptonMomentumRank);
    fChain->SetBranchAddress("TTL_LeptonIsMuon", &TTL_LeptonIsMuon);
    fChain->SetBranchAddress("TTL_LeptonIsElectron", &TTL_LeptonIsElectron);
    fChain->SetBranchAddress("TTL_LeptonPt", &TTL_LeptonPt);
    fChain->SetBranchAddress("TTL_LeptonEta", &TTL_LeptonEta);
    fChain->SetBranchAddress("TTL_LeptonPhi", &TTL_LeptonPhi);
    fChain->SetBranchAddress("TTL_LeptonRelIso", &TTL_LeptonRelIso);
    fChain->SetBranchAddress("TTL_LeptonIsLoose", &TTL_LeptonIsLoose);
    fChain->SetBranchAddress("TTL_LeptonIsTight", &TTL_LeptonIsTight);
    fChain->SetBranchAddress("TTL_NumLooseMuons", &TTL_NumLooseMuons);
    fChain->SetBranchAddress("TTL_NumExLooseMuons", &TTL_NumExLooseMuons);
    fChain->SetBranchAddress("TTL_NumTightMuons", &TTL_NumTightMuons);
    fChain->SetBranchAddress("TTL_NumLooseElectrons", &TTL_NumLooseElectrons);
    fChain->SetBranchAddress("TTL_NumExLooseElectrons", &TTL_NumExLooseElectrons);
    fChain->SetBranchAddress("TTL_NumTightElectrons", &TTL_NumTightElectrons);
    fChain->SetBranchAddress("TTL_LeptonGenMatchDaughter0Id", &TTL_LeptonGenMatchDaughter0Id);
    fChain->SetBranchAddress("TTL_LeptonGenMatchDaughter1Id", &TTL_LeptonGenMatchDaughter1Id);
    fChain->SetBranchAddress("TTL_LeptonGenMatchId", &TTL_LeptonGenMatchId);
    fChain->SetBranchAddress("TTL_LeptonGenMatchMother0Id", &TTL_LeptonGenMatchMother0Id);
    fChain->SetBranchAddress("TTL_LeptonGenMatchMother1Id", &TTL_LeptonGenMatchMother1Id);
    fChain->SetBranchAddress("TTL_LeptonGenMatchGrandmother00Id", &TTL_LeptonGenMatchGrandmother00Id);
    fChain->SetBranchAddress("TTL_LeptonGenMatchGrandmother01Id", &TTL_LeptonGenMatchGrandmother01Id);
    fChain->SetBranchAddress("TTL_LeptonGenMatchGrandmother10Id", &TTL_LeptonGenMatchGrandmother10Id);
    fChain->SetBranchAddress("TTL_LeptonGenMatchGrandmother11Id", &TTL_LeptonGenMatchGrandmother11Id);
    fChain->SetBranchAddress("TTL_LeptonGenMatchDaughter0Status", &TTL_LeptonGenMatchDaughter0Status);
    fChain->SetBranchAddress("TTL_LeptonGenMatchDaughter1Status", &TTL_LeptonGenMatchDaughter1Status);
    fChain->SetBranchAddress("TTL_LeptonGenMatchStatus", &TTL_LeptonGenMatchStatus);
    fChain->SetBranchAddress("TTL_LeptonGenMatchMother0Status", &TTL_LeptonGenMatchMother0Status);
    fChain->SetBranchAddress("TTL_LeptonGenMatchMother1Status", &TTL_LeptonGenMatchMother1Status);
    fChain->SetBranchAddress("TTL_LeptonGenMatchGrandmother00Status", &TTL_LeptonGenMatchGrandmother00Status);
    fChain->SetBranchAddress("TTL_LeptonGenMatchGrandmother01Status", &TTL_LeptonGenMatchGrandmother01Status);
    fChain->SetBranchAddress("TTL_LeptonGenMatchGrandmother10Status", &TTL_LeptonGenMatchGrandmother10Status);
    fChain->SetBranchAddress("TTL_LeptonGenMatchGrandmother11Status", &TTL_LeptonGenMatchGrandmother11Status);
    fChain->SetBranchAddress("TTL_DitauVisibleMass", &TTL_DitauVisibleMass);
    fChain->SetBranchAddress("TTL_DitauMETMass", &TTL_DitauMETMass);
    fChain->SetBranchAddress("TTL_DitauCosDeltaPhi", &TTL_DitauCosDeltaPhi);
    fChain->SetBranchAddress("TTL_DitauDeltaR", &TTL_DitauDeltaR);
    fChain->SetBranchAddress("TTL_Tau1LeptonDeltaR", &TTL_Tau1LeptonDeltaR);
    fChain->SetBranchAddress("TTL_Tau2LeptonDeltaR", &TTL_Tau2LeptonDeltaR);
    fChain->SetBranchAddress("TTL_HT", &TTL_HT);
    fChain->SetBranchAddress("TTL_NumCSVLbtagJets", &TTL_NumCSVLbtagJets);
    fChain->SetBranchAddress("TTL_NumCSVMbtagJets", &TTL_NumCSVMbtagJets);
    fChain->SetBranchAddress("TTL_NumCSVTbtagJets", &TTL_NumCSVTbtagJets);
    fChain->SetBranchAddress("TTL_NumNonCSVLbtagJets", &TTL_NumNonCSVLbtagJets);
    fChain->SetBranchAddress("TTL_NumNonCSVMbtagJets", &TTL_NumNonCSVMbtagJets);
    fChain->SetBranchAddress("TTL_NumNonCSVTbtagJets", &TTL_NumNonCSVTbtagJets);
    fChain->SetBranchAddress("TTL_NumCleanCSVLbtagJets", &TTL_NumCleanCSVLbtagJets);
    fChain->SetBranchAddress("TTL_NumCleanCSVMbtagJets", &TTL_NumCleanCSVMbtagJets);
    fChain->SetBranchAddress("TTL_NumCleanCSVTbtagJets", &TTL_NumCleanCSVTbtagJets);
    fChain->SetBranchAddress("TTL_NumCleanNonCSVLbtagJets", &TTL_NumCleanNonCSVLbtagJets);
    fChain->SetBranchAddress("TTL_NumCleanNonCSVMbtagJets", &TTL_NumCleanNonCSVMbtagJets);
    fChain->SetBranchAddress("TTL_NumCleanNonCSVTbtagJets", &TTL_NumCleanNonCSVTbtagJets);
    fChain->SetBranchAddress("TTL_CleanJetIndices", &TTL_CleanJetIndices);
    fChain->SetBranchAddress("TTL_LeptonEventWeight", &TTL_LeptonEventWeight);
    fChain->SetBranchAddress("TTL_CSVeventWeight", &CSVeventWeight);
    fChain->SetBranchAddress("TTL_CSVeventWeightHFdown", &CSVeventWeightHFdown);
    fChain->SetBranchAddress("TTL_CSVeventWeightHFup", &CSVeventWeightHFup);
    fChain->SetBranchAddress("TTL_CSVeventWeightLFdown", &CSVeventWeightLFdown);
    fChain->SetBranchAddress("TTL_CSVeventWeightLFup", &CSVeventWeightLFup);
    fChain->SetBranchAddress("TTL_CSVeventWeightHFStats1down", &CSVeventWeightHFStats1down);
    fChain->SetBranchAddress("TTL_CSVeventWeightHFStats1up", &CSVeventWeightHFStats1up);
    fChain->SetBranchAddress("TTL_CSVeventWeightLFStats1down", &CSVeventWeightLFStats1down);
    fChain->SetBranchAddress("TTL_CSVeventWeightLFStats1up", &CSVeventWeightLFStats1up);
    fChain->SetBranchAddress("TTL_CSVeventWeightHFStats2down", &CSVeventWeightHFStats2down);
    fChain->SetBranchAddress("TTL_CSVeventWeightHFStats2up", &CSVeventWeightHFStats2up);
    fChain->SetBranchAddress("TTL_CSVeventWeightLFStats2down", &CSVeventWeightLFStats2down);
    fChain->SetBranchAddress("TTL_CSVeventWeightLFStats2up", &CSVeventWeightLFStats2up);
    fChain->SetBranchAddress("TTL_CSVeventWeightCErr1up", &CSVeventWeightCErr1up);
    fChain->SetBranchAddress("TTL_CSVeventWeightCErr1down", &CSVeventWeightCErr1down);
    fChain->SetBranchAddress("TTL_CSVeventWeightCErr2up", &CSVeventWeightCErr2up);
    fChain->SetBranchAddress("TTL_CSVeventWeightCErr2down", &CSVeventWeightCErr2down);
    // >>> End address <<<
}
