// vim: ts=4:sw=4:et:sta
#include "../interface/TTLBranches.h"

using namespace roast;

void
ttl::Branches::Clear()
{
    roast::Branches::Clear();

    // >>> Begin clear <<<
    TTL_DitauCosDeltaPhi->clear();
    TTL_DitauDeltaR->clear();
    TTL_DitauMETMass->clear();
    TTL_DitauVisibleMass->clear();
    TTL_ElectronMomentumRank->clear();
    TTL_LeptonCharge->clear();
    TTL_LeptonCorrectedD0->clear();
    TTL_LeptonCorrectedDZ->clear();
    TTL_LeptonEta->clear();
    TTL_LeptonEventWeight->clear();
    TTL_LeptonGenMatchDaughter0Id->clear();
    TTL_LeptonGenMatchDaughter0Status->clear();
    TTL_LeptonGenMatchDaughter1Id->clear();
    TTL_LeptonGenMatchDaughter1Status->clear();
    TTL_LeptonGenMatchGrandmother00Id->clear();
    TTL_LeptonGenMatchGrandmother00Status->clear();
    TTL_LeptonGenMatchGrandmother01Id->clear();
    TTL_LeptonGenMatchGrandmother01Status->clear();
    TTL_LeptonGenMatchGrandmother10Id->clear();
    TTL_LeptonGenMatchGrandmother10Status->clear();
    TTL_LeptonGenMatchGrandmother11Id->clear();
    TTL_LeptonGenMatchGrandmother11Status->clear();
    TTL_LeptonGenMatchId->clear();
    TTL_LeptonGenMatchMother0Id->clear();
    TTL_LeptonGenMatchMother0Status->clear();
    TTL_LeptonGenMatchMother1Id->clear();
    TTL_LeptonGenMatchMother1Status->clear();
    TTL_LeptonGenMatchStatus->clear();
    TTL_LeptonImpactParameter->clear();
    TTL_LeptonIsElectron->clear();
    TTL_LeptonIsLoose->clear();
    TTL_LeptonIsMuon->clear();
    TTL_LeptonIsTight->clear();
    TTL_LeptonMomentumRank->clear();
    TTL_LeptonMt->clear();
    TTL_LeptonMt2->clear();
    TTL_LeptonPhi->clear();
    TTL_LeptonPt->clear();
    TTL_LeptonRelIso->clear();
    TTL_MuonMomentumRank->clear();
    TTL_NumElectrons = 0;
    TTL_NumLeptons = 0;
    TTL_NumMuons = 0;
    TTL_Tau1Charge->clear();
    TTL_Tau1DecayMode->clear();
    TTL_Tau1EmFraction->clear();
    TTL_Tau1Eta->clear();
    TTL_Tau1GenMatchDaughter0Id->clear();
    TTL_Tau1GenMatchDaughter0Status->clear();
    TTL_Tau1GenMatchDaughter1Id->clear();
    TTL_Tau1GenMatchDaughter1Status->clear();
    TTL_Tau1GenMatchGrandmother00Id->clear();
    TTL_Tau1GenMatchGrandmother00Status->clear();
    TTL_Tau1GenMatchGrandmother01Id->clear();
    TTL_Tau1GenMatchGrandmother01Status->clear();
    TTL_Tau1GenMatchGrandmother10Id->clear();
    TTL_Tau1GenMatchGrandmother10Status->clear();
    TTL_Tau1GenMatchGrandmother11Id->clear();
    TTL_Tau1GenMatchGrandmother11Status->clear();
    TTL_Tau1GenMatchId->clear();
    TTL_Tau1GenMatchMother0Id->clear();
    TTL_Tau1GenMatchMother0Status->clear();
    TTL_Tau1GenMatchMother1Id->clear();
    TTL_Tau1GenMatchMother1Status->clear();
    TTL_Tau1GenMatchStatus->clear();
    TTL_Tau1HPSagainstElectronDeadECAL->clear();
    TTL_Tau1HPSagainstElectronLoose->clear();
    TTL_Tau1HPSagainstElectronLooseMVA2->clear();
    TTL_Tau1HPSagainstElectronLooseMVA3->clear();
    TTL_Tau1HPSagainstElectronMVA->clear();
    TTL_Tau1HPSagainstElectronMVA2category->clear();
    TTL_Tau1HPSagainstElectronMVA2raw->clear();
    TTL_Tau1HPSagainstElectronMVA3category->clear();
    TTL_Tau1HPSagainstElectronMVA3raw->clear();
    TTL_Tau1HPSagainstElectronMedium->clear();
    TTL_Tau1HPSagainstElectronMediumMVA2->clear();
    TTL_Tau1HPSagainstElectronMediumMVA3->clear();
    TTL_Tau1HPSagainstElectronTight->clear();
    TTL_Tau1HPSagainstElectronTightMVA2->clear();
    TTL_Tau1HPSagainstElectronTightMVA3->clear();
    TTL_Tau1HPSagainstElectronVLooseMVA2->clear();
    TTL_Tau1HPSagainstElectronVTightMVA3->clear();
    TTL_Tau1HPSagainstMuonLoose->clear();
    TTL_Tau1HPSagainstMuonLoose2->clear();
    TTL_Tau1HPSagainstMuonMedium->clear();
    TTL_Tau1HPSagainstMuonMedium2->clear();
    TTL_Tau1HPSagainstMuonTight->clear();
    TTL_Tau1HPSagainstMuonTight2->clear();
    TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw->clear();
    TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits->clear();
    TTL_Tau1HPSbyIsolationMVA2raw->clear();
    TTL_Tau1HPSbyIsolationMVAraw->clear();
    TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr->clear();
    TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits->clear();
    TTL_Tau1HPSbyLooseIsolationMVA->clear();
    TTL_Tau1HPSbyLooseIsolationMVA2->clear();
    TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr->clear();
    TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits->clear();
    TTL_Tau1HPSbyMediumIsolationMVA->clear();
    TTL_Tau1HPSbyMediumIsolationMVA2->clear();
    TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr->clear();
    TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr3Hits->clear();
    TTL_Tau1HPSbyTightIsolationMVA->clear();
    TTL_Tau1HPSbyTightIsolationMVA2->clear();
    TTL_Tau1HPSbyVLooseCombinedIsolationDeltaBetaCorr->clear();
    TTL_Tau1HPSdecayModeFinding->clear();
    TTL_Tau1IsInTheCracks->clear();
    TTL_Tau1LTIpVtdxy->clear();
    TTL_Tau1LTIpVtdxyError->clear();
    TTL_Tau1LTIpVtdz->clear();
    TTL_Tau1LTIpVtdzError->clear();
    TTL_Tau1LTNormChiSqrd->clear();
    TTL_Tau1LTPt->clear();
    TTL_Tau1LTValidHits->clear();
    TTL_Tau1LTvalid->clear();
    TTL_Tau1LTvx->clear();
    TTL_Tau1LTvy->clear();
    TTL_Tau1LTvz->clear();
    TTL_Tau1LeptonDeltaR->clear();
    TTL_Tau1MomentumRank->clear();
    TTL_Tau1NProngs->clear();
    TTL_Tau1NSignalGammas->clear();
    TTL_Tau1NSignalNeutrals->clear();
    TTL_Tau1Phi->clear();
    TTL_Tau1Pt->clear();
    TTL_Tau2Charge->clear();
    TTL_Tau2DecayMode->clear();
    TTL_Tau2EmFraction->clear();
    TTL_Tau2Eta->clear();
    TTL_Tau2GenMatchDaughter0Id->clear();
    TTL_Tau2GenMatchDaughter0Status->clear();
    TTL_Tau2GenMatchDaughter1Id->clear();
    TTL_Tau2GenMatchDaughter1Status->clear();
    TTL_Tau2GenMatchGrandmother00Id->clear();
    TTL_Tau2GenMatchGrandmother00Status->clear();
    TTL_Tau2GenMatchGrandmother01Id->clear();
    TTL_Tau2GenMatchGrandmother01Status->clear();
    TTL_Tau2GenMatchGrandmother10Id->clear();
    TTL_Tau2GenMatchGrandmother10Status->clear();
    TTL_Tau2GenMatchGrandmother11Id->clear();
    TTL_Tau2GenMatchGrandmother11Status->clear();
    TTL_Tau2GenMatchId->clear();
    TTL_Tau2GenMatchMother0Id->clear();
    TTL_Tau2GenMatchMother0Status->clear();
    TTL_Tau2GenMatchMother1Id->clear();
    TTL_Tau2GenMatchMother1Status->clear();
    TTL_Tau2GenMatchStatus->clear();
    TTL_Tau2HPSagainstElectronDeadECAL->clear();
    TTL_Tau2HPSagainstElectronLoose->clear();
    TTL_Tau2HPSagainstElectronLooseMVA2->clear();
    TTL_Tau2HPSagainstElectronLooseMVA3->clear();
    TTL_Tau2HPSagainstElectronMVA->clear();
    TTL_Tau2HPSagainstElectronMVA2category->clear();
    TTL_Tau2HPSagainstElectronMVA2raw->clear();
    TTL_Tau2HPSagainstElectronMVA3category->clear();
    TTL_Tau2HPSagainstElectronMVA3raw->clear();
    TTL_Tau2HPSagainstElectronMedium->clear();
    TTL_Tau2HPSagainstElectronMediumMVA2->clear();
    TTL_Tau2HPSagainstElectronMediumMVA3->clear();
    TTL_Tau2HPSagainstElectronTight->clear();
    TTL_Tau2HPSagainstElectronTightMVA2->clear();
    TTL_Tau2HPSagainstElectronTightMVA3->clear();
    TTL_Tau2HPSagainstElectronVLooseMVA2->clear();
    TTL_Tau2HPSagainstElectronVTightMVA3->clear();
    TTL_Tau2HPSagainstMuonLoose->clear();
    TTL_Tau2HPSagainstMuonLoose2->clear();
    TTL_Tau2HPSagainstMuonMedium->clear();
    TTL_Tau2HPSagainstMuonMedium2->clear();
    TTL_Tau2HPSagainstMuonTight->clear();
    TTL_Tau2HPSagainstMuonTight2->clear();
    TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw->clear();
    TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits->clear();
    TTL_Tau2HPSbyIsolationMVA2raw->clear();
    TTL_Tau2HPSbyIsolationMVAraw->clear();
    TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr->clear();
    TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits->clear();
    TTL_Tau2HPSbyLooseIsolationMVA->clear();
    TTL_Tau2HPSbyLooseIsolationMVA2->clear();
    TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr->clear();
    TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits->clear();
    TTL_Tau2HPSbyMediumIsolationMVA->clear();
    TTL_Tau2HPSbyMediumIsolationMVA2->clear();
    TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr->clear();
    TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr3Hits->clear();
    TTL_Tau2HPSbyTightIsolationMVA->clear();
    TTL_Tau2HPSbyTightIsolationMVA2->clear();
    TTL_Tau2HPSbyVLooseCombinedIsolationDeltaBetaCorr->clear();
    TTL_Tau2HPSdecayModeFinding->clear();
    TTL_Tau2IsInTheCracks->clear();
    TTL_Tau2LTIpVtdxy->clear();
    TTL_Tau2LTIpVtdxyError->clear();
    TTL_Tau2LTIpVtdz->clear();
    TTL_Tau2LTIpVtdzError->clear();
    TTL_Tau2LTNormChiSqrd->clear();
    TTL_Tau2LTPt->clear();
    TTL_Tau2LTValidHits->clear();
    TTL_Tau2LTvalid->clear();
    TTL_Tau2LTvx->clear();
    TTL_Tau2LTvy->clear();
    TTL_Tau2LTvz->clear();
    TTL_Tau2LeptonDeltaR->clear();
    TTL_Tau2MomentumRank->clear();
    TTL_Tau2NProngs->clear();
    TTL_Tau2NSignalGammas->clear();
    TTL_Tau2NSignalNeutrals->clear();
    TTL_Tau2Phi->clear();
    TTL_Tau2Pt->clear();
    // >>> End clear <<<
}

void
ttl::Branches::Delete()
{
    roast::Branches::Delete();

    // >>> Begin delete <<<
    delete TTL_DitauCosDeltaPhi;
    delete TTL_DitauDeltaR;
    delete TTL_DitauMETMass;
    delete TTL_DitauVisibleMass;
    delete TTL_ElectronMomentumRank;
    delete TTL_LeptonCharge;
    delete TTL_LeptonCorrectedD0;
    delete TTL_LeptonCorrectedDZ;
    delete TTL_LeptonEta;
    delete TTL_LeptonEventWeight;
    delete TTL_LeptonGenMatchDaughter0Id;
    delete TTL_LeptonGenMatchDaughter0Status;
    delete TTL_LeptonGenMatchDaughter1Id;
    delete TTL_LeptonGenMatchDaughter1Status;
    delete TTL_LeptonGenMatchGrandmother00Id;
    delete TTL_LeptonGenMatchGrandmother00Status;
    delete TTL_LeptonGenMatchGrandmother01Id;
    delete TTL_LeptonGenMatchGrandmother01Status;
    delete TTL_LeptonGenMatchGrandmother10Id;
    delete TTL_LeptonGenMatchGrandmother10Status;
    delete TTL_LeptonGenMatchGrandmother11Id;
    delete TTL_LeptonGenMatchGrandmother11Status;
    delete TTL_LeptonGenMatchId;
    delete TTL_LeptonGenMatchMother0Id;
    delete TTL_LeptonGenMatchMother0Status;
    delete TTL_LeptonGenMatchMother1Id;
    delete TTL_LeptonGenMatchMother1Status;
    delete TTL_LeptonGenMatchStatus;
    delete TTL_LeptonImpactParameter;
    delete TTL_LeptonIsElectron;
    delete TTL_LeptonIsLoose;
    delete TTL_LeptonIsMuon;
    delete TTL_LeptonIsTight;
    delete TTL_LeptonMomentumRank;
    delete TTL_LeptonMt;
    delete TTL_LeptonMt2;
    delete TTL_LeptonPhi;
    delete TTL_LeptonPt;
    delete TTL_LeptonRelIso;
    delete TTL_MuonMomentumRank;
    delete TTL_Tau1Charge;
    delete TTL_Tau1DecayMode;
    delete TTL_Tau1EmFraction;
    delete TTL_Tau1Eta;
    delete TTL_Tau1GenMatchDaughter0Id;
    delete TTL_Tau1GenMatchDaughter0Status;
    delete TTL_Tau1GenMatchDaughter1Id;
    delete TTL_Tau1GenMatchDaughter1Status;
    delete TTL_Tau1GenMatchGrandmother00Id;
    delete TTL_Tau1GenMatchGrandmother00Status;
    delete TTL_Tau1GenMatchGrandmother01Id;
    delete TTL_Tau1GenMatchGrandmother01Status;
    delete TTL_Tau1GenMatchGrandmother10Id;
    delete TTL_Tau1GenMatchGrandmother10Status;
    delete TTL_Tau1GenMatchGrandmother11Id;
    delete TTL_Tau1GenMatchGrandmother11Status;
    delete TTL_Tau1GenMatchId;
    delete TTL_Tau1GenMatchMother0Id;
    delete TTL_Tau1GenMatchMother0Status;
    delete TTL_Tau1GenMatchMother1Id;
    delete TTL_Tau1GenMatchMother1Status;
    delete TTL_Tau1GenMatchStatus;
    delete TTL_Tau1HPSagainstElectronDeadECAL;
    delete TTL_Tau1HPSagainstElectronLoose;
    delete TTL_Tau1HPSagainstElectronLooseMVA2;
    delete TTL_Tau1HPSagainstElectronLooseMVA3;
    delete TTL_Tau1HPSagainstElectronMVA;
    delete TTL_Tau1HPSagainstElectronMVA2category;
    delete TTL_Tau1HPSagainstElectronMVA2raw;
    delete TTL_Tau1HPSagainstElectronMVA3category;
    delete TTL_Tau1HPSagainstElectronMVA3raw;
    delete TTL_Tau1HPSagainstElectronMedium;
    delete TTL_Tau1HPSagainstElectronMediumMVA2;
    delete TTL_Tau1HPSagainstElectronMediumMVA3;
    delete TTL_Tau1HPSagainstElectronTight;
    delete TTL_Tau1HPSagainstElectronTightMVA2;
    delete TTL_Tau1HPSagainstElectronTightMVA3;
    delete TTL_Tau1HPSagainstElectronVLooseMVA2;
    delete TTL_Tau1HPSagainstElectronVTightMVA3;
    delete TTL_Tau1HPSagainstMuonLoose;
    delete TTL_Tau1HPSagainstMuonLoose2;
    delete TTL_Tau1HPSagainstMuonMedium;
    delete TTL_Tau1HPSagainstMuonMedium2;
    delete TTL_Tau1HPSagainstMuonTight;
    delete TTL_Tau1HPSagainstMuonTight2;
    delete TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw;
    delete TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits;
    delete TTL_Tau1HPSbyIsolationMVA2raw;
    delete TTL_Tau1HPSbyIsolationMVAraw;
    delete TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr;
    delete TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits;
    delete TTL_Tau1HPSbyLooseIsolationMVA;
    delete TTL_Tau1HPSbyLooseIsolationMVA2;
    delete TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr;
    delete TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits;
    delete TTL_Tau1HPSbyMediumIsolationMVA;
    delete TTL_Tau1HPSbyMediumIsolationMVA2;
    delete TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr;
    delete TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr3Hits;
    delete TTL_Tau1HPSbyTightIsolationMVA;
    delete TTL_Tau1HPSbyTightIsolationMVA2;
    delete TTL_Tau1HPSbyVLooseCombinedIsolationDeltaBetaCorr;
    delete TTL_Tau1HPSdecayModeFinding;
    delete TTL_Tau1IsInTheCracks;
    delete TTL_Tau1LTIpVtdxy;
    delete TTL_Tau1LTIpVtdxyError;
    delete TTL_Tau1LTIpVtdz;
    delete TTL_Tau1LTIpVtdzError;
    delete TTL_Tau1LTNormChiSqrd;
    delete TTL_Tau1LTPt;
    delete TTL_Tau1LTValidHits;
    delete TTL_Tau1LTvalid;
    delete TTL_Tau1LTvx;
    delete TTL_Tau1LTvy;
    delete TTL_Tau1LTvz;
    delete TTL_Tau1LeptonDeltaR;
    delete TTL_Tau1MomentumRank;
    delete TTL_Tau1NProngs;
    delete TTL_Tau1NSignalGammas;
    delete TTL_Tau1NSignalNeutrals;
    delete TTL_Tau1Phi;
    delete TTL_Tau1Pt;
    delete TTL_Tau2Charge;
    delete TTL_Tau2DecayMode;
    delete TTL_Tau2EmFraction;
    delete TTL_Tau2Eta;
    delete TTL_Tau2GenMatchDaughter0Id;
    delete TTL_Tau2GenMatchDaughter0Status;
    delete TTL_Tau2GenMatchDaughter1Id;
    delete TTL_Tau2GenMatchDaughter1Status;
    delete TTL_Tau2GenMatchGrandmother00Id;
    delete TTL_Tau2GenMatchGrandmother00Status;
    delete TTL_Tau2GenMatchGrandmother01Id;
    delete TTL_Tau2GenMatchGrandmother01Status;
    delete TTL_Tau2GenMatchGrandmother10Id;
    delete TTL_Tau2GenMatchGrandmother10Status;
    delete TTL_Tau2GenMatchGrandmother11Id;
    delete TTL_Tau2GenMatchGrandmother11Status;
    delete TTL_Tau2GenMatchId;
    delete TTL_Tau2GenMatchMother0Id;
    delete TTL_Tau2GenMatchMother0Status;
    delete TTL_Tau2GenMatchMother1Id;
    delete TTL_Tau2GenMatchMother1Status;
    delete TTL_Tau2GenMatchStatus;
    delete TTL_Tau2HPSagainstElectronDeadECAL;
    delete TTL_Tau2HPSagainstElectronLoose;
    delete TTL_Tau2HPSagainstElectronLooseMVA2;
    delete TTL_Tau2HPSagainstElectronLooseMVA3;
    delete TTL_Tau2HPSagainstElectronMVA;
    delete TTL_Tau2HPSagainstElectronMVA2category;
    delete TTL_Tau2HPSagainstElectronMVA2raw;
    delete TTL_Tau2HPSagainstElectronMVA3category;
    delete TTL_Tau2HPSagainstElectronMVA3raw;
    delete TTL_Tau2HPSagainstElectronMedium;
    delete TTL_Tau2HPSagainstElectronMediumMVA2;
    delete TTL_Tau2HPSagainstElectronMediumMVA3;
    delete TTL_Tau2HPSagainstElectronTight;
    delete TTL_Tau2HPSagainstElectronTightMVA2;
    delete TTL_Tau2HPSagainstElectronTightMVA3;
    delete TTL_Tau2HPSagainstElectronVLooseMVA2;
    delete TTL_Tau2HPSagainstElectronVTightMVA3;
    delete TTL_Tau2HPSagainstMuonLoose;
    delete TTL_Tau2HPSagainstMuonLoose2;
    delete TTL_Tau2HPSagainstMuonMedium;
    delete TTL_Tau2HPSagainstMuonMedium2;
    delete TTL_Tau2HPSagainstMuonTight;
    delete TTL_Tau2HPSagainstMuonTight2;
    delete TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw;
    delete TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits;
    delete TTL_Tau2HPSbyIsolationMVA2raw;
    delete TTL_Tau2HPSbyIsolationMVAraw;
    delete TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr;
    delete TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits;
    delete TTL_Tau2HPSbyLooseIsolationMVA;
    delete TTL_Tau2HPSbyLooseIsolationMVA2;
    delete TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr;
    delete TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits;
    delete TTL_Tau2HPSbyMediumIsolationMVA;
    delete TTL_Tau2HPSbyMediumIsolationMVA2;
    delete TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr;
    delete TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr3Hits;
    delete TTL_Tau2HPSbyTightIsolationMVA;
    delete TTL_Tau2HPSbyTightIsolationMVA2;
    delete TTL_Tau2HPSbyVLooseCombinedIsolationDeltaBetaCorr;
    delete TTL_Tau2HPSdecayModeFinding;
    delete TTL_Tau2IsInTheCracks;
    delete TTL_Tau2LTIpVtdxy;
    delete TTL_Tau2LTIpVtdxyError;
    delete TTL_Tau2LTIpVtdz;
    delete TTL_Tau2LTIpVtdzError;
    delete TTL_Tau2LTNormChiSqrd;
    delete TTL_Tau2LTPt;
    delete TTL_Tau2LTValidHits;
    delete TTL_Tau2LTvalid;
    delete TTL_Tau2LTvx;
    delete TTL_Tau2LTvy;
    delete TTL_Tau2LTvz;
    delete TTL_Tau2LeptonDeltaR;
    delete TTL_Tau2MomentumRank;
    delete TTL_Tau2NProngs;
    delete TTL_Tau2NSignalGammas;
    delete TTL_Tau2NSignalNeutrals;
    delete TTL_Tau2Phi;
    delete TTL_Tau2Pt;
    // >>> End delete <<<
}

void
ttl::Branches::Null()
{
    roast::Branches::Null();

    // >>> Begin null <<<
    TTL_DitauCosDeltaPhi = 0;
    TTL_DitauDeltaR = 0;
    TTL_DitauMETMass = 0;
    TTL_DitauVisibleMass = 0;
    TTL_ElectronMomentumRank = 0;
    TTL_LeptonCharge = 0;
    TTL_LeptonCorrectedD0 = 0;
    TTL_LeptonCorrectedDZ = 0;
    TTL_LeptonEta = 0;
    TTL_LeptonEventWeight = 0;
    TTL_LeptonGenMatchDaughter0Id = 0;
    TTL_LeptonGenMatchDaughter0Status = 0;
    TTL_LeptonGenMatchDaughter1Id = 0;
    TTL_LeptonGenMatchDaughter1Status = 0;
    TTL_LeptonGenMatchGrandmother00Id = 0;
    TTL_LeptonGenMatchGrandmother00Status = 0;
    TTL_LeptonGenMatchGrandmother01Id = 0;
    TTL_LeptonGenMatchGrandmother01Status = 0;
    TTL_LeptonGenMatchGrandmother10Id = 0;
    TTL_LeptonGenMatchGrandmother10Status = 0;
    TTL_LeptonGenMatchGrandmother11Id = 0;
    TTL_LeptonGenMatchGrandmother11Status = 0;
    TTL_LeptonGenMatchId = 0;
    TTL_LeptonGenMatchMother0Id = 0;
    TTL_LeptonGenMatchMother0Status = 0;
    TTL_LeptonGenMatchMother1Id = 0;
    TTL_LeptonGenMatchMother1Status = 0;
    TTL_LeptonGenMatchStatus = 0;
    TTL_LeptonImpactParameter = 0;
    TTL_LeptonIsElectron = 0;
    TTL_LeptonIsLoose = 0;
    TTL_LeptonIsMuon = 0;
    TTL_LeptonIsTight = 0;
    TTL_LeptonMomentumRank = 0;
    TTL_LeptonMt = 0;
    TTL_LeptonMt2 = 0;
    TTL_LeptonPhi = 0;
    TTL_LeptonPt = 0;
    TTL_LeptonRelIso = 0;
    TTL_MuonMomentumRank = 0;
    TTL_NumElectrons = 0;
    TTL_NumLeptons = 0;
    TTL_NumMuons = 0;
    TTL_Tau1Charge = 0;
    TTL_Tau1DecayMode = 0;
    TTL_Tau1EmFraction = 0;
    TTL_Tau1Eta = 0;
    TTL_Tau1GenMatchDaughter0Id = 0;
    TTL_Tau1GenMatchDaughter0Status = 0;
    TTL_Tau1GenMatchDaughter1Id = 0;
    TTL_Tau1GenMatchDaughter1Status = 0;
    TTL_Tau1GenMatchGrandmother00Id = 0;
    TTL_Tau1GenMatchGrandmother00Status = 0;
    TTL_Tau1GenMatchGrandmother01Id = 0;
    TTL_Tau1GenMatchGrandmother01Status = 0;
    TTL_Tau1GenMatchGrandmother10Id = 0;
    TTL_Tau1GenMatchGrandmother10Status = 0;
    TTL_Tau1GenMatchGrandmother11Id = 0;
    TTL_Tau1GenMatchGrandmother11Status = 0;
    TTL_Tau1GenMatchId = 0;
    TTL_Tau1GenMatchMother0Id = 0;
    TTL_Tau1GenMatchMother0Status = 0;
    TTL_Tau1GenMatchMother1Id = 0;
    TTL_Tau1GenMatchMother1Status = 0;
    TTL_Tau1GenMatchStatus = 0;
    TTL_Tau1HPSagainstElectronDeadECAL = 0;
    TTL_Tau1HPSagainstElectronLoose = 0;
    TTL_Tau1HPSagainstElectronLooseMVA2 = 0;
    TTL_Tau1HPSagainstElectronLooseMVA3 = 0;
    TTL_Tau1HPSagainstElectronMVA = 0;
    TTL_Tau1HPSagainstElectronMVA2category = 0;
    TTL_Tau1HPSagainstElectronMVA2raw = 0;
    TTL_Tau1HPSagainstElectronMVA3category = 0;
    TTL_Tau1HPSagainstElectronMVA3raw = 0;
    TTL_Tau1HPSagainstElectronMedium = 0;
    TTL_Tau1HPSagainstElectronMediumMVA2 = 0;
    TTL_Tau1HPSagainstElectronMediumMVA3 = 0;
    TTL_Tau1HPSagainstElectronTight = 0;
    TTL_Tau1HPSagainstElectronTightMVA2 = 0;
    TTL_Tau1HPSagainstElectronTightMVA3 = 0;
    TTL_Tau1HPSagainstElectronVLooseMVA2 = 0;
    TTL_Tau1HPSagainstElectronVTightMVA3 = 0;
    TTL_Tau1HPSagainstMuonLoose = 0;
    TTL_Tau1HPSagainstMuonLoose2 = 0;
    TTL_Tau1HPSagainstMuonMedium = 0;
    TTL_Tau1HPSagainstMuonMedium2 = 0;
    TTL_Tau1HPSagainstMuonTight = 0;
    TTL_Tau1HPSagainstMuonTight2 = 0;
    TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw = 0;
    TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits = 0;
    TTL_Tau1HPSbyIsolationMVA2raw = 0;
    TTL_Tau1HPSbyIsolationMVAraw = 0;
    TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr = 0;
    TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits = 0;
    TTL_Tau1HPSbyLooseIsolationMVA = 0;
    TTL_Tau1HPSbyLooseIsolationMVA2 = 0;
    TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr = 0;
    TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits = 0;
    TTL_Tau1HPSbyMediumIsolationMVA = 0;
    TTL_Tau1HPSbyMediumIsolationMVA2 = 0;
    TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr = 0;
    TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr3Hits = 0;
    TTL_Tau1HPSbyTightIsolationMVA = 0;
    TTL_Tau1HPSbyTightIsolationMVA2 = 0;
    TTL_Tau1HPSbyVLooseCombinedIsolationDeltaBetaCorr = 0;
    TTL_Tau1HPSdecayModeFinding = 0;
    TTL_Tau1IsInTheCracks = 0;
    TTL_Tau1LTIpVtdxy = 0;
    TTL_Tau1LTIpVtdxyError = 0;
    TTL_Tau1LTIpVtdz = 0;
    TTL_Tau1LTIpVtdzError = 0;
    TTL_Tau1LTNormChiSqrd = 0;
    TTL_Tau1LTPt = 0;
    TTL_Tau1LTValidHits = 0;
    TTL_Tau1LTvalid = 0;
    TTL_Tau1LTvx = 0;
    TTL_Tau1LTvy = 0;
    TTL_Tau1LTvz = 0;
    TTL_Tau1LeptonDeltaR = 0;
    TTL_Tau1MomentumRank = 0;
    TTL_Tau1NProngs = 0;
    TTL_Tau1NSignalGammas = 0;
    TTL_Tau1NSignalNeutrals = 0;
    TTL_Tau1Phi = 0;
    TTL_Tau1Pt = 0;
    TTL_Tau2Charge = 0;
    TTL_Tau2DecayMode = 0;
    TTL_Tau2EmFraction = 0;
    TTL_Tau2Eta = 0;
    TTL_Tau2GenMatchDaughter0Id = 0;
    TTL_Tau2GenMatchDaughter0Status = 0;
    TTL_Tau2GenMatchDaughter1Id = 0;
    TTL_Tau2GenMatchDaughter1Status = 0;
    TTL_Tau2GenMatchGrandmother00Id = 0;
    TTL_Tau2GenMatchGrandmother00Status = 0;
    TTL_Tau2GenMatchGrandmother01Id = 0;
    TTL_Tau2GenMatchGrandmother01Status = 0;
    TTL_Tau2GenMatchGrandmother10Id = 0;
    TTL_Tau2GenMatchGrandmother10Status = 0;
    TTL_Tau2GenMatchGrandmother11Id = 0;
    TTL_Tau2GenMatchGrandmother11Status = 0;
    TTL_Tau2GenMatchId = 0;
    TTL_Tau2GenMatchMother0Id = 0;
    TTL_Tau2GenMatchMother0Status = 0;
    TTL_Tau2GenMatchMother1Id = 0;
    TTL_Tau2GenMatchMother1Status = 0;
    TTL_Tau2GenMatchStatus = 0;
    TTL_Tau2HPSagainstElectronDeadECAL = 0;
    TTL_Tau2HPSagainstElectronLoose = 0;
    TTL_Tau2HPSagainstElectronLooseMVA2 = 0;
    TTL_Tau2HPSagainstElectronLooseMVA3 = 0;
    TTL_Tau2HPSagainstElectronMVA = 0;
    TTL_Tau2HPSagainstElectronMVA2category = 0;
    TTL_Tau2HPSagainstElectronMVA2raw = 0;
    TTL_Tau2HPSagainstElectronMVA3category = 0;
    TTL_Tau2HPSagainstElectronMVA3raw = 0;
    TTL_Tau2HPSagainstElectronMedium = 0;
    TTL_Tau2HPSagainstElectronMediumMVA2 = 0;
    TTL_Tau2HPSagainstElectronMediumMVA3 = 0;
    TTL_Tau2HPSagainstElectronTight = 0;
    TTL_Tau2HPSagainstElectronTightMVA2 = 0;
    TTL_Tau2HPSagainstElectronTightMVA3 = 0;
    TTL_Tau2HPSagainstElectronVLooseMVA2 = 0;
    TTL_Tau2HPSagainstElectronVTightMVA3 = 0;
    TTL_Tau2HPSagainstMuonLoose = 0;
    TTL_Tau2HPSagainstMuonLoose2 = 0;
    TTL_Tau2HPSagainstMuonMedium = 0;
    TTL_Tau2HPSagainstMuonMedium2 = 0;
    TTL_Tau2HPSagainstMuonTight = 0;
    TTL_Tau2HPSagainstMuonTight2 = 0;
    TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw = 0;
    TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits = 0;
    TTL_Tau2HPSbyIsolationMVA2raw = 0;
    TTL_Tau2HPSbyIsolationMVAraw = 0;
    TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr = 0;
    TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits = 0;
    TTL_Tau2HPSbyLooseIsolationMVA = 0;
    TTL_Tau2HPSbyLooseIsolationMVA2 = 0;
    TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr = 0;
    TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits = 0;
    TTL_Tau2HPSbyMediumIsolationMVA = 0;
    TTL_Tau2HPSbyMediumIsolationMVA2 = 0;
    TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr = 0;
    TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr3Hits = 0;
    TTL_Tau2HPSbyTightIsolationMVA = 0;
    TTL_Tau2HPSbyTightIsolationMVA2 = 0;
    TTL_Tau2HPSbyVLooseCombinedIsolationDeltaBetaCorr = 0;
    TTL_Tau2HPSdecayModeFinding = 0;
    TTL_Tau2IsInTheCracks = 0;
    TTL_Tau2LTIpVtdxy = 0;
    TTL_Tau2LTIpVtdxyError = 0;
    TTL_Tau2LTIpVtdz = 0;
    TTL_Tau2LTIpVtdzError = 0;
    TTL_Tau2LTNormChiSqrd = 0;
    TTL_Tau2LTPt = 0;
    TTL_Tau2LTValidHits = 0;
    TTL_Tau2LTvalid = 0;
    TTL_Tau2LTvx = 0;
    TTL_Tau2LTvy = 0;
    TTL_Tau2LTvz = 0;
    TTL_Tau2LeptonDeltaR = 0;
    TTL_Tau2MomentumRank = 0;
    TTL_Tau2NProngs = 0;
    TTL_Tau2NSignalGammas = 0;
    TTL_Tau2NSignalNeutrals = 0;
    TTL_Tau2Phi = 0;
    TTL_Tau2Pt = 0;
    // >>> End null <<<
}

void
ttl::Branches::SetBranchAddresses()
{
    roast::Branches::SetBranchAddresses();

    // >>> Begin address <<<
    fChain->SetBranchAddress("TTL_CSVeventWeight", &CSVeventWeight);
    fChain->SetBranchAddress("TTL_CSVeventWeightCErr1down", &CSVeventWeightCErr1down);
    fChain->SetBranchAddress("TTL_CSVeventWeightCErr1up", &CSVeventWeightCErr1up);
    fChain->SetBranchAddress("TTL_CSVeventWeightCErr2down", &CSVeventWeightCErr2down);
    fChain->SetBranchAddress("TTL_CSVeventWeightCErr2up", &CSVeventWeightCErr2up);
    fChain->SetBranchAddress("TTL_CSVeventWeightHFStats1down", &CSVeventWeightHFStats1down);
    fChain->SetBranchAddress("TTL_CSVeventWeightHFStats1up", &CSVeventWeightHFStats1up);
    fChain->SetBranchAddress("TTL_CSVeventWeightHFStats2down", &CSVeventWeightHFStats2down);
    fChain->SetBranchAddress("TTL_CSVeventWeightHFStats2up", &CSVeventWeightHFStats2up);
    fChain->SetBranchAddress("TTL_CSVeventWeightHFdown", &CSVeventWeightHFdown);
    fChain->SetBranchAddress("TTL_CSVeventWeightHFup", &CSVeventWeightHFup);
    fChain->SetBranchAddress("TTL_CSVeventWeightLFStats1down", &CSVeventWeightLFStats1down);
    fChain->SetBranchAddress("TTL_CSVeventWeightLFStats1up", &CSVeventWeightLFStats1up);
    fChain->SetBranchAddress("TTL_CSVeventWeightLFStats2down", &CSVeventWeightLFStats2down);
    fChain->SetBranchAddress("TTL_CSVeventWeightLFStats2up", &CSVeventWeightLFStats2up);
    fChain->SetBranchAddress("TTL_CSVeventWeightLFdown", &CSVeventWeightLFdown);
    fChain->SetBranchAddress("TTL_CSVeventWeightLFup", &CSVeventWeightLFup);
    fChain->SetBranchAddress("TTL_CleanJetCSVMIndices", &CleanJetCSVMIndices);
    fChain->SetBranchAddress("TTL_CleanJetIndices", &CleanJetIndices);
    fChain->SetBranchAddress("TTL_CleanJetNonCSVMIndices", &CleanJetNonCSVMIndices);
    fChain->SetBranchAddress("TTL_DitauCosDeltaPhi", &TTL_DitauCosDeltaPhi);
    fChain->SetBranchAddress("TTL_DitauDeltaR", &TTL_DitauDeltaR);
    fChain->SetBranchAddress("TTL_DitauMETMass", &TTL_DitauMETMass);
    fChain->SetBranchAddress("TTL_DitauVisibleMass", &TTL_DitauVisibleMass);
    fChain->SetBranchAddress("TTL_ElectronMomentumRank", &TTL_ElectronMomentumRank);
    fChain->SetBranchAddress("TTL_HT", &HT);
    fChain->SetBranchAddress("TTL_LeptonCharge", &TTL_LeptonCharge);
    fChain->SetBranchAddress("TTL_LeptonCorrectedD0", &TTL_LeptonCorrectedD0);
    fChain->SetBranchAddress("TTL_LeptonCorrectedDZ", &TTL_LeptonCorrectedDZ);
    fChain->SetBranchAddress("TTL_LeptonEta", &TTL_LeptonEta);
    fChain->SetBranchAddress("TTL_LeptonEventWeight", &TTL_LeptonEventWeight);
    fChain->SetBranchAddress("TTL_LeptonGenMatchDaughter0Id", &TTL_LeptonGenMatchDaughter0Id);
    fChain->SetBranchAddress("TTL_LeptonGenMatchDaughter0Status", &TTL_LeptonGenMatchDaughter0Status);
    fChain->SetBranchAddress("TTL_LeptonGenMatchDaughter1Id", &TTL_LeptonGenMatchDaughter1Id);
    fChain->SetBranchAddress("TTL_LeptonGenMatchDaughter1Status", &TTL_LeptonGenMatchDaughter1Status);
    fChain->SetBranchAddress("TTL_LeptonGenMatchGrandmother00Id", &TTL_LeptonGenMatchGrandmother00Id);
    fChain->SetBranchAddress("TTL_LeptonGenMatchGrandmother00Status", &TTL_LeptonGenMatchGrandmother00Status);
    fChain->SetBranchAddress("TTL_LeptonGenMatchGrandmother01Id", &TTL_LeptonGenMatchGrandmother01Id);
    fChain->SetBranchAddress("TTL_LeptonGenMatchGrandmother01Status", &TTL_LeptonGenMatchGrandmother01Status);
    fChain->SetBranchAddress("TTL_LeptonGenMatchGrandmother10Id", &TTL_LeptonGenMatchGrandmother10Id);
    fChain->SetBranchAddress("TTL_LeptonGenMatchGrandmother10Status", &TTL_LeptonGenMatchGrandmother10Status);
    fChain->SetBranchAddress("TTL_LeptonGenMatchGrandmother11Id", &TTL_LeptonGenMatchGrandmother11Id);
    fChain->SetBranchAddress("TTL_LeptonGenMatchGrandmother11Status", &TTL_LeptonGenMatchGrandmother11Status);
    fChain->SetBranchAddress("TTL_LeptonGenMatchId", &TTL_LeptonGenMatchId);
    fChain->SetBranchAddress("TTL_LeptonGenMatchMother0Id", &TTL_LeptonGenMatchMother0Id);
    fChain->SetBranchAddress("TTL_LeptonGenMatchMother0Status", &TTL_LeptonGenMatchMother0Status);
    fChain->SetBranchAddress("TTL_LeptonGenMatchMother1Id", &TTL_LeptonGenMatchMother1Id);
    fChain->SetBranchAddress("TTL_LeptonGenMatchMother1Status", &TTL_LeptonGenMatchMother1Status);
    fChain->SetBranchAddress("TTL_LeptonGenMatchStatus", &TTL_LeptonGenMatchStatus);
    fChain->SetBranchAddress("TTL_LeptonImpactParameter", &TTL_LeptonImpactParameter);
    fChain->SetBranchAddress("TTL_LeptonIsElectron", &TTL_LeptonIsElectron);
    fChain->SetBranchAddress("TTL_LeptonIsLoose", &TTL_LeptonIsLoose);
    fChain->SetBranchAddress("TTL_LeptonIsMuon", &TTL_LeptonIsMuon);
    fChain->SetBranchAddress("TTL_LeptonIsTight", &TTL_LeptonIsTight);
    fChain->SetBranchAddress("TTL_LeptonMomentumRank", &TTL_LeptonMomentumRank);
    fChain->SetBranchAddress("TTL_LeptonMt", &TTL_LeptonMt);
    fChain->SetBranchAddress("TTL_LeptonMt2", &TTL_LeptonMt2);
    fChain->SetBranchAddress("TTL_LeptonPhi", &TTL_LeptonPhi);
    fChain->SetBranchAddress("TTL_LeptonPt", &TTL_LeptonPt);
    fChain->SetBranchAddress("TTL_LeptonRelIso", &TTL_LeptonRelIso);
    fChain->SetBranchAddress("TTL_MHT", &MHT);
    fChain->SetBranchAddress("TTL_MomentumRank", &MomentumRank);
    fChain->SetBranchAddress("TTL_MuonMomentumRank", &TTL_MuonMomentumRank);
    fChain->SetBranchAddress("TTL_NumCSVLbtagJets", &NumCSVLbtagJets);
    fChain->SetBranchAddress("TTL_NumCSVMbtagJets", &NumCSVMbtagJets);
    fChain->SetBranchAddress("TTL_NumCSVTbtagJets", &NumCSVTbtagJets);
    fChain->SetBranchAddress("TTL_NumCleanCSVLbtagJets", &NumCleanCSVLbtagJets);
    fChain->SetBranchAddress("TTL_NumCleanCSVMbtagJets", &NumCleanCSVMbtagJets);
    fChain->SetBranchAddress("TTL_NumCleanCSVTbtagJets", &NumCleanCSVTbtagJets);
    fChain->SetBranchAddress("TTL_NumCleanNonCSVLbtagJets", &NumCleanNonCSVLbtagJets);
    fChain->SetBranchAddress("TTL_NumCleanNonCSVMbtagJets", &NumCleanNonCSVMbtagJets);
    fChain->SetBranchAddress("TTL_NumCleanNonCSVTbtagJets", &NumCleanNonCSVTbtagJets);
    fChain->SetBranchAddress("TTL_NumCombos", &NumCombos);
    fChain->SetBranchAddress("TTL_NumElectrons", &TTL_NumElectrons);
    fChain->SetBranchAddress("TTL_NumExLooseElectrons", &NumExLooseElectrons);
    fChain->SetBranchAddress("TTL_NumExLooseMuons", &NumExLooseMuons);
    fChain->SetBranchAddress("TTL_NumLeptons", &TTL_NumLeptons);
    fChain->SetBranchAddress("TTL_NumLooseElectrons", &NumLooseElectrons);
    fChain->SetBranchAddress("TTL_NumLooseMuons", &NumLooseMuons);
    fChain->SetBranchAddress("TTL_NumMuons", &TTL_NumMuons);
    fChain->SetBranchAddress("TTL_NumNonCSVLbtagJets", &NumNonCSVLbtagJets);
    fChain->SetBranchAddress("TTL_NumNonCSVMbtagJets", &NumNonCSVMbtagJets);
    fChain->SetBranchAddress("TTL_NumNonCSVTbtagJets", &NumNonCSVTbtagJets);
    fChain->SetBranchAddress("TTL_NumTaus", &NumTaus);
    fChain->SetBranchAddress("TTL_NumTightElectrons", &NumTightElectrons);
    fChain->SetBranchAddress("TTL_NumTightMuons", &NumTightMuons);
    fChain->SetBranchAddress("TTL_Tau1Charge", &TTL_Tau1Charge);
    fChain->SetBranchAddress("TTL_Tau1DecayMode", &TTL_Tau1DecayMode);
    fChain->SetBranchAddress("TTL_Tau1EmFraction", &TTL_Tau1EmFraction);
    fChain->SetBranchAddress("TTL_Tau1Eta", &TTL_Tau1Eta);
    fChain->SetBranchAddress("TTL_Tau1GenMatchDaughter0Id", &TTL_Tau1GenMatchDaughter0Id);
    fChain->SetBranchAddress("TTL_Tau1GenMatchDaughter0Status", &TTL_Tau1GenMatchDaughter0Status);
    fChain->SetBranchAddress("TTL_Tau1GenMatchDaughter1Id", &TTL_Tau1GenMatchDaughter1Id);
    fChain->SetBranchAddress("TTL_Tau1GenMatchDaughter1Status", &TTL_Tau1GenMatchDaughter1Status);
    fChain->SetBranchAddress("TTL_Tau1GenMatchGrandmother00Id", &TTL_Tau1GenMatchGrandmother00Id);
    fChain->SetBranchAddress("TTL_Tau1GenMatchGrandmother00Status", &TTL_Tau1GenMatchGrandmother00Status);
    fChain->SetBranchAddress("TTL_Tau1GenMatchGrandmother01Id", &TTL_Tau1GenMatchGrandmother01Id);
    fChain->SetBranchAddress("TTL_Tau1GenMatchGrandmother01Status", &TTL_Tau1GenMatchGrandmother01Status);
    fChain->SetBranchAddress("TTL_Tau1GenMatchGrandmother10Id", &TTL_Tau1GenMatchGrandmother10Id);
    fChain->SetBranchAddress("TTL_Tau1GenMatchGrandmother10Status", &TTL_Tau1GenMatchGrandmother10Status);
    fChain->SetBranchAddress("TTL_Tau1GenMatchGrandmother11Id", &TTL_Tau1GenMatchGrandmother11Id);
    fChain->SetBranchAddress("TTL_Tau1GenMatchGrandmother11Status", &TTL_Tau1GenMatchGrandmother11Status);
    fChain->SetBranchAddress("TTL_Tau1GenMatchId", &TTL_Tau1GenMatchId);
    fChain->SetBranchAddress("TTL_Tau1GenMatchMother0Id", &TTL_Tau1GenMatchMother0Id);
    fChain->SetBranchAddress("TTL_Tau1GenMatchMother0Status", &TTL_Tau1GenMatchMother0Status);
    fChain->SetBranchAddress("TTL_Tau1GenMatchMother1Id", &TTL_Tau1GenMatchMother1Id);
    fChain->SetBranchAddress("TTL_Tau1GenMatchMother1Status", &TTL_Tau1GenMatchMother1Status);
    fChain->SetBranchAddress("TTL_Tau1GenMatchStatus", &TTL_Tau1GenMatchStatus);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronDeadECAL", &TTL_Tau1HPSagainstElectronDeadECAL);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronLoose", &TTL_Tau1HPSagainstElectronLoose);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronLooseMVA2", &TTL_Tau1HPSagainstElectronLooseMVA2);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronLooseMVA3", &TTL_Tau1HPSagainstElectronLooseMVA3);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronMVA", &TTL_Tau1HPSagainstElectronMVA);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronMVA2category", &TTL_Tau1HPSagainstElectronMVA2category);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronMVA2raw", &TTL_Tau1HPSagainstElectronMVA2raw);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronMVA3category", &TTL_Tau1HPSagainstElectronMVA3category);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronMVA3raw", &TTL_Tau1HPSagainstElectronMVA3raw);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronMedium", &TTL_Tau1HPSagainstElectronMedium);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronMediumMVA2", &TTL_Tau1HPSagainstElectronMediumMVA2);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronMediumMVA3", &TTL_Tau1HPSagainstElectronMediumMVA3);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronTight", &TTL_Tau1HPSagainstElectronTight);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronTightMVA2", &TTL_Tau1HPSagainstElectronTightMVA2);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronTightMVA3", &TTL_Tau1HPSagainstElectronTightMVA3);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronVLooseMVA2", &TTL_Tau1HPSagainstElectronVLooseMVA2);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstElectronVTightMVA3", &TTL_Tau1HPSagainstElectronVTightMVA3);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstMuonLoose", &TTL_Tau1HPSagainstMuonLoose);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstMuonLoose2", &TTL_Tau1HPSagainstMuonLoose2);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstMuonMedium", &TTL_Tau1HPSagainstMuonMedium);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstMuonMedium2", &TTL_Tau1HPSagainstMuonMedium2);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstMuonTight", &TTL_Tau1HPSagainstMuonTight);
    fChain->SetBranchAddress("TTL_Tau1HPSagainstMuonTight2", &TTL_Tau1HPSagainstMuonTight2);
    fChain->SetBranchAddress("TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw", &TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw);
    fChain->SetBranchAddress("TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits", &TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits);
    fChain->SetBranchAddress("TTL_Tau1HPSbyIsolationMVA2raw", &TTL_Tau1HPSbyIsolationMVA2raw);
    fChain->SetBranchAddress("TTL_Tau1HPSbyIsolationMVAraw", &TTL_Tau1HPSbyIsolationMVAraw);
    fChain->SetBranchAddress("TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr", &TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits", &TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("TTL_Tau1HPSbyLooseIsolationMVA", &TTL_Tau1HPSbyLooseIsolationMVA);
    fChain->SetBranchAddress("TTL_Tau1HPSbyLooseIsolationMVA2", &TTL_Tau1HPSbyLooseIsolationMVA2);
    fChain->SetBranchAddress("TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr", &TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits", &TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("TTL_Tau1HPSbyMediumIsolationMVA", &TTL_Tau1HPSbyMediumIsolationMVA);
    fChain->SetBranchAddress("TTL_Tau1HPSbyMediumIsolationMVA2", &TTL_Tau1HPSbyMediumIsolationMVA2);
    fChain->SetBranchAddress("TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr", &TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr3Hits", &TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("TTL_Tau1HPSbyTightIsolationMVA", &TTL_Tau1HPSbyTightIsolationMVA);
    fChain->SetBranchAddress("TTL_Tau1HPSbyTightIsolationMVA2", &TTL_Tau1HPSbyTightIsolationMVA2);
    fChain->SetBranchAddress("TTL_Tau1HPSbyVLooseCombinedIsolationDeltaBetaCorr", &TTL_Tau1HPSbyVLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TTL_Tau1HPSdecayModeFinding", &TTL_Tau1HPSdecayModeFinding);
    fChain->SetBranchAddress("TTL_Tau1IsInTheCracks", &TTL_Tau1IsInTheCracks);
    fChain->SetBranchAddress("TTL_Tau1LTIpVtdxy", &TTL_Tau1LTIpVtdxy);
    fChain->SetBranchAddress("TTL_Tau1LTIpVtdxyError", &TTL_Tau1LTIpVtdxyError);
    fChain->SetBranchAddress("TTL_Tau1LTIpVtdz", &TTL_Tau1LTIpVtdz);
    fChain->SetBranchAddress("TTL_Tau1LTIpVtdzError", &TTL_Tau1LTIpVtdzError);
    fChain->SetBranchAddress("TTL_Tau1LTNormChiSqrd", &TTL_Tau1LTNormChiSqrd);
    fChain->SetBranchAddress("TTL_Tau1LTPt", &TTL_Tau1LTPt);
    fChain->SetBranchAddress("TTL_Tau1LTValidHits", &TTL_Tau1LTValidHits);
    fChain->SetBranchAddress("TTL_Tau1LTvalid", &TTL_Tau1LTvalid);
    fChain->SetBranchAddress("TTL_Tau1LTvx", &TTL_Tau1LTvx);
    fChain->SetBranchAddress("TTL_Tau1LTvy", &TTL_Tau1LTvy);
    fChain->SetBranchAddress("TTL_Tau1LTvz", &TTL_Tau1LTvz);
    fChain->SetBranchAddress("TTL_Tau1LeptonDeltaR", &TTL_Tau1LeptonDeltaR);
    fChain->SetBranchAddress("TTL_Tau1MomentumRank", &TTL_Tau1MomentumRank);
    fChain->SetBranchAddress("TTL_Tau1NProngs", &TTL_Tau1NProngs);
    fChain->SetBranchAddress("TTL_Tau1NSignalGammas", &TTL_Tau1NSignalGammas);
    fChain->SetBranchAddress("TTL_Tau1NSignalNeutrals", &TTL_Tau1NSignalNeutrals);
    fChain->SetBranchAddress("TTL_Tau1Phi", &TTL_Tau1Phi);
    fChain->SetBranchAddress("TTL_Tau1Pt", &TTL_Tau1Pt);
    fChain->SetBranchAddress("TTL_Tau2Charge", &TTL_Tau2Charge);
    fChain->SetBranchAddress("TTL_Tau2DecayMode", &TTL_Tau2DecayMode);
    fChain->SetBranchAddress("TTL_Tau2EmFraction", &TTL_Tau2EmFraction);
    fChain->SetBranchAddress("TTL_Tau2Eta", &TTL_Tau2Eta);
    fChain->SetBranchAddress("TTL_Tau2GenMatchDaughter0Id", &TTL_Tau2GenMatchDaughter0Id);
    fChain->SetBranchAddress("TTL_Tau2GenMatchDaughter0Status", &TTL_Tau2GenMatchDaughter0Status);
    fChain->SetBranchAddress("TTL_Tau2GenMatchDaughter1Id", &TTL_Tau2GenMatchDaughter1Id);
    fChain->SetBranchAddress("TTL_Tau2GenMatchDaughter1Status", &TTL_Tau2GenMatchDaughter1Status);
    fChain->SetBranchAddress("TTL_Tau2GenMatchGrandmother00Id", &TTL_Tau2GenMatchGrandmother00Id);
    fChain->SetBranchAddress("TTL_Tau2GenMatchGrandmother00Status", &TTL_Tau2GenMatchGrandmother00Status);
    fChain->SetBranchAddress("TTL_Tau2GenMatchGrandmother01Id", &TTL_Tau2GenMatchGrandmother01Id);
    fChain->SetBranchAddress("TTL_Tau2GenMatchGrandmother01Status", &TTL_Tau2GenMatchGrandmother01Status);
    fChain->SetBranchAddress("TTL_Tau2GenMatchGrandmother10Id", &TTL_Tau2GenMatchGrandmother10Id);
    fChain->SetBranchAddress("TTL_Tau2GenMatchGrandmother10Status", &TTL_Tau2GenMatchGrandmother10Status);
    fChain->SetBranchAddress("TTL_Tau2GenMatchGrandmother11Id", &TTL_Tau2GenMatchGrandmother11Id);
    fChain->SetBranchAddress("TTL_Tau2GenMatchGrandmother11Status", &TTL_Tau2GenMatchGrandmother11Status);
    fChain->SetBranchAddress("TTL_Tau2GenMatchId", &TTL_Tau2GenMatchId);
    fChain->SetBranchAddress("TTL_Tau2GenMatchMother0Id", &TTL_Tau2GenMatchMother0Id);
    fChain->SetBranchAddress("TTL_Tau2GenMatchMother0Status", &TTL_Tau2GenMatchMother0Status);
    fChain->SetBranchAddress("TTL_Tau2GenMatchMother1Id", &TTL_Tau2GenMatchMother1Id);
    fChain->SetBranchAddress("TTL_Tau2GenMatchMother1Status", &TTL_Tau2GenMatchMother1Status);
    fChain->SetBranchAddress("TTL_Tau2GenMatchStatus", &TTL_Tau2GenMatchStatus);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronDeadECAL", &TTL_Tau2HPSagainstElectronDeadECAL);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronLoose", &TTL_Tau2HPSagainstElectronLoose);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronLooseMVA2", &TTL_Tau2HPSagainstElectronLooseMVA2);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronLooseMVA3", &TTL_Tau2HPSagainstElectronLooseMVA3);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronMVA", &TTL_Tau2HPSagainstElectronMVA);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronMVA2category", &TTL_Tau2HPSagainstElectronMVA2category);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronMVA2raw", &TTL_Tau2HPSagainstElectronMVA2raw);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronMVA3category", &TTL_Tau2HPSagainstElectronMVA3category);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronMVA3raw", &TTL_Tau2HPSagainstElectronMVA3raw);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronMedium", &TTL_Tau2HPSagainstElectronMedium);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronMediumMVA2", &TTL_Tau2HPSagainstElectronMediumMVA2);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronMediumMVA3", &TTL_Tau2HPSagainstElectronMediumMVA3);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronTight", &TTL_Tau2HPSagainstElectronTight);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronTightMVA2", &TTL_Tau2HPSagainstElectronTightMVA2);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronTightMVA3", &TTL_Tau2HPSagainstElectronTightMVA3);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronVLooseMVA2", &TTL_Tau2HPSagainstElectronVLooseMVA2);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstElectronVTightMVA3", &TTL_Tau2HPSagainstElectronVTightMVA3);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstMuonLoose", &TTL_Tau2HPSagainstMuonLoose);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstMuonLoose2", &TTL_Tau2HPSagainstMuonLoose2);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstMuonMedium", &TTL_Tau2HPSagainstMuonMedium);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstMuonMedium2", &TTL_Tau2HPSagainstMuonMedium2);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstMuonTight", &TTL_Tau2HPSagainstMuonTight);
    fChain->SetBranchAddress("TTL_Tau2HPSagainstMuonTight2", &TTL_Tau2HPSagainstMuonTight2);
    fChain->SetBranchAddress("TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw", &TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw);
    fChain->SetBranchAddress("TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits", &TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits);
    fChain->SetBranchAddress("TTL_Tau2HPSbyIsolationMVA2raw", &TTL_Tau2HPSbyIsolationMVA2raw);
    fChain->SetBranchAddress("TTL_Tau2HPSbyIsolationMVAraw", &TTL_Tau2HPSbyIsolationMVAraw);
    fChain->SetBranchAddress("TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr", &TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits", &TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("TTL_Tau2HPSbyLooseIsolationMVA", &TTL_Tau2HPSbyLooseIsolationMVA);
    fChain->SetBranchAddress("TTL_Tau2HPSbyLooseIsolationMVA2", &TTL_Tau2HPSbyLooseIsolationMVA2);
    fChain->SetBranchAddress("TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr", &TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits", &TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("TTL_Tau2HPSbyMediumIsolationMVA", &TTL_Tau2HPSbyMediumIsolationMVA);
    fChain->SetBranchAddress("TTL_Tau2HPSbyMediumIsolationMVA2", &TTL_Tau2HPSbyMediumIsolationMVA2);
    fChain->SetBranchAddress("TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr", &TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr3Hits", &TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("TTL_Tau2HPSbyTightIsolationMVA", &TTL_Tau2HPSbyTightIsolationMVA);
    fChain->SetBranchAddress("TTL_Tau2HPSbyTightIsolationMVA2", &TTL_Tau2HPSbyTightIsolationMVA2);
    fChain->SetBranchAddress("TTL_Tau2HPSbyVLooseCombinedIsolationDeltaBetaCorr", &TTL_Tau2HPSbyVLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("TTL_Tau2HPSdecayModeFinding", &TTL_Tau2HPSdecayModeFinding);
    fChain->SetBranchAddress("TTL_Tau2IsInTheCracks", &TTL_Tau2IsInTheCracks);
    fChain->SetBranchAddress("TTL_Tau2LTIpVtdxy", &TTL_Tau2LTIpVtdxy);
    fChain->SetBranchAddress("TTL_Tau2LTIpVtdxyError", &TTL_Tau2LTIpVtdxyError);
    fChain->SetBranchAddress("TTL_Tau2LTIpVtdz", &TTL_Tau2LTIpVtdz);
    fChain->SetBranchAddress("TTL_Tau2LTIpVtdzError", &TTL_Tau2LTIpVtdzError);
    fChain->SetBranchAddress("TTL_Tau2LTNormChiSqrd", &TTL_Tau2LTNormChiSqrd);
    fChain->SetBranchAddress("TTL_Tau2LTPt", &TTL_Tau2LTPt);
    fChain->SetBranchAddress("TTL_Tau2LTValidHits", &TTL_Tau2LTValidHits);
    fChain->SetBranchAddress("TTL_Tau2LTvalid", &TTL_Tau2LTvalid);
    fChain->SetBranchAddress("TTL_Tau2LTvx", &TTL_Tau2LTvx);
    fChain->SetBranchAddress("TTL_Tau2LTvy", &TTL_Tau2LTvy);
    fChain->SetBranchAddress("TTL_Tau2LTvz", &TTL_Tau2LTvz);
    fChain->SetBranchAddress("TTL_Tau2LeptonDeltaR", &TTL_Tau2LeptonDeltaR);
    fChain->SetBranchAddress("TTL_Tau2MomentumRank", &TTL_Tau2MomentumRank);
    fChain->SetBranchAddress("TTL_Tau2NProngs", &TTL_Tau2NProngs);
    fChain->SetBranchAddress("TTL_Tau2NSignalGammas", &TTL_Tau2NSignalGammas);
    fChain->SetBranchAddress("TTL_Tau2NSignalNeutrals", &TTL_Tau2NSignalNeutrals);
    fChain->SetBranchAddress("TTL_Tau2Phi", &TTL_Tau2Phi);
    fChain->SetBranchAddress("TTL_Tau2Pt", &TTL_Tau2Pt);
    // >>> End address <<<
}
