// vim: ts=4:sw=4:et:sta
#include "../interface/TTLBranches.h"

using namespace roast;

void
ttl::Branches::Clear()
{
    roast::Branches::Clear();

    // >>> Begin clear <<<
    L_Charge->clear();
    L_CorrectedD0->clear();
    L_CorrectedDZ->clear();
    L_EventWeight->clear();
    L_GenMatchDaughter0Id->clear();
    L_GenMatchDaughter0Status->clear();
    L_GenMatchDaughter1Id->clear();
    L_GenMatchDaughter1Status->clear();
    L_GenMatchGrandmother00Id->clear();
    L_GenMatchGrandmother00Status->clear();
    L_GenMatchGrandmother01Id->clear();
    L_GenMatchGrandmother01Status->clear();
    L_GenMatchGrandmother10Id->clear();
    L_GenMatchGrandmother10Status->clear();
    L_GenMatchGrandmother11Id->clear();
    L_GenMatchGrandmother11Status->clear();
    L_GenMatchId->clear();
    L_GenMatchMother0Id->clear();
    L_GenMatchMother0Status->clear();
    L_GenMatchMother1Id->clear();
    L_GenMatchMother1Status->clear();
    L_GenMatchStatus->clear();
    L_ImpactParameter->clear();
    L_IsElectron->clear();
    L_IsLoose->clear();
    L_IsMuon->clear();
    L_IsTight->clear();
    L_P->clear();
    L_RelIso->clear();
    NumRecoTaus = 0;
    RT_Charge->clear();
    RT_DecayMode->clear();
    RT_EmFraction->clear();
    RT_GenMatchDaughter0Id->clear();
    RT_GenMatchDaughter0Status->clear();
    RT_GenMatchDaughter1Id->clear();
    RT_GenMatchDaughter1Status->clear();
    RT_GenMatchGrandmother00Id->clear();
    RT_GenMatchGrandmother00Status->clear();
    RT_GenMatchGrandmother01Id->clear();
    RT_GenMatchGrandmother01Status->clear();
    RT_GenMatchGrandmother10Id->clear();
    RT_GenMatchGrandmother10Status->clear();
    RT_GenMatchGrandmother11Id->clear();
    RT_GenMatchGrandmother11Status->clear();
    RT_GenMatchId->clear();
    RT_GenMatchMother0Id->clear();
    RT_GenMatchMother0Status->clear();
    RT_GenMatchMother1Id->clear();
    RT_GenMatchMother1Status->clear();
    RT_GenMatchStatus->clear();
    RT_HPSagainstElectronDeadECAL->clear();
    RT_HPSagainstElectronLoose->clear();
    RT_HPSagainstElectronLooseMVA2->clear();
    RT_HPSagainstElectronLooseMVA3->clear();
    RT_HPSagainstElectronMVA->clear();
    RT_HPSagainstElectronMVA2category->clear();
    RT_HPSagainstElectronMVA2raw->clear();
    RT_HPSagainstElectronMVA3category->clear();
    RT_HPSagainstElectronMVA3raw->clear();
    RT_HPSagainstElectronMedium->clear();
    RT_HPSagainstElectronMediumMVA2->clear();
    RT_HPSagainstElectronMediumMVA3->clear();
    RT_HPSagainstElectronTight->clear();
    RT_HPSagainstElectronTightMVA2->clear();
    RT_HPSagainstElectronTightMVA3->clear();
    RT_HPSagainstElectronVLooseMVA2->clear();
    RT_HPSagainstElectronVTightMVA3->clear();
    RT_HPSagainstMuonLoose->clear();
    RT_HPSagainstMuonLoose2->clear();
    RT_HPSagainstMuonMedium->clear();
    RT_HPSagainstMuonMedium2->clear();
    RT_HPSagainstMuonTight->clear();
    RT_HPSagainstMuonTight2->clear();
    RT_HPSbyCombinedIsolationDeltaBetaCorrRaw->clear();
    RT_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits->clear();
    RT_HPSbyIsolationMVA2raw->clear();
    RT_HPSbyIsolationMVAraw->clear();
    RT_HPSbyLooseCombinedIsolationDeltaBetaCorr->clear();
    RT_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits->clear();
    RT_HPSbyLooseIsolationMVA->clear();
    RT_HPSbyLooseIsolationMVA2->clear();
    RT_HPSbyMediumCombinedIsolationDeltaBetaCorr->clear();
    RT_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits->clear();
    RT_HPSbyMediumIsolationMVA->clear();
    RT_HPSbyMediumIsolationMVA2->clear();
    RT_HPSbyTightCombinedIsolationDeltaBetaCorr->clear();
    RT_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits->clear();
    RT_HPSbyTightIsolationMVA->clear();
    RT_HPSbyTightIsolationMVA2->clear();
    RT_HPSbyVLooseCombinedIsolationDeltaBetaCorr->clear();
    RT_HPSdecayModeFinding->clear();
    RT_IsInTheCracks->clear();
    RT_JetCSV->clear();
    RT_LTIpVtdxy->clear();
    RT_LTIpVtdxyError->clear();
    RT_LTIpVtdz->clear();
    RT_LTIpVtdzError->clear();
    RT_LTNormChiSqrd->clear();
    RT_LTPt->clear();
    RT_LTValidHits->clear();
    RT_LTvalid->clear();
    RT_LTvx->clear();
    RT_LTvy->clear();
    RT_LTvz->clear();
    RT_MomentumRank->clear();
    RT_NProngs->clear();
    RT_NSignalGammas->clear();
    RT_NSignalNeutrals->clear();
    RT_P->clear();
    T1_Charge->clear();
    T1_DecayMode->clear();
    T1_EmFraction->clear();
    T1_GenMatchDaughter0Id->clear();
    T1_GenMatchDaughter0Status->clear();
    T1_GenMatchDaughter1Id->clear();
    T1_GenMatchDaughter1Status->clear();
    T1_GenMatchGrandmother00Id->clear();
    T1_GenMatchGrandmother00Status->clear();
    T1_GenMatchGrandmother01Id->clear();
    T1_GenMatchGrandmother01Status->clear();
    T1_GenMatchGrandmother10Id->clear();
    T1_GenMatchGrandmother10Status->clear();
    T1_GenMatchGrandmother11Id->clear();
    T1_GenMatchGrandmother11Status->clear();
    T1_GenMatchId->clear();
    T1_GenMatchMother0Id->clear();
    T1_GenMatchMother0Status->clear();
    T1_GenMatchMother1Id->clear();
    T1_GenMatchMother1Status->clear();
    T1_GenMatchStatus->clear();
    T1_HPSagainstElectronDeadECAL->clear();
    T1_HPSagainstElectronLoose->clear();
    T1_HPSagainstElectronLooseMVA2->clear();
    T1_HPSagainstElectronLooseMVA3->clear();
    T1_HPSagainstElectronMVA->clear();
    T1_HPSagainstElectronMVA2category->clear();
    T1_HPSagainstElectronMVA2raw->clear();
    T1_HPSagainstElectronMVA3category->clear();
    T1_HPSagainstElectronMVA3raw->clear();
    T1_HPSagainstElectronMedium->clear();
    T1_HPSagainstElectronMediumMVA2->clear();
    T1_HPSagainstElectronMediumMVA3->clear();
    T1_HPSagainstElectronTight->clear();
    T1_HPSagainstElectronTightMVA2->clear();
    T1_HPSagainstElectronTightMVA3->clear();
    T1_HPSagainstElectronVLooseMVA2->clear();
    T1_HPSagainstElectronVTightMVA3->clear();
    T1_HPSagainstMuonLoose->clear();
    T1_HPSagainstMuonLoose2->clear();
    T1_HPSagainstMuonMedium->clear();
    T1_HPSagainstMuonMedium2->clear();
    T1_HPSagainstMuonTight->clear();
    T1_HPSagainstMuonTight2->clear();
    T1_HPSbyCombinedIsolationDeltaBetaCorrRaw->clear();
    T1_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits->clear();
    T1_HPSbyIsolationMVA2raw->clear();
    T1_HPSbyIsolationMVAraw->clear();
    T1_HPSbyLooseCombinedIsolationDeltaBetaCorr->clear();
    T1_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits->clear();
    T1_HPSbyLooseIsolationMVA->clear();
    T1_HPSbyLooseIsolationMVA2->clear();
    T1_HPSbyMediumCombinedIsolationDeltaBetaCorr->clear();
    T1_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits->clear();
    T1_HPSbyMediumIsolationMVA->clear();
    T1_HPSbyMediumIsolationMVA2->clear();
    T1_HPSbyTightCombinedIsolationDeltaBetaCorr->clear();
    T1_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits->clear();
    T1_HPSbyTightIsolationMVA->clear();
    T1_HPSbyTightIsolationMVA2->clear();
    T1_HPSbyVLooseCombinedIsolationDeltaBetaCorr->clear();
    T1_HPSdecayModeFinding->clear();
    T1_IsInTheCracks->clear();
    T1_JetCSV->clear();
    T1_LTIpVtdxy->clear();
    T1_LTIpVtdxyError->clear();
    T1_LTIpVtdz->clear();
    T1_LTIpVtdzError->clear();
    T1_LTNormChiSqrd->clear();
    T1_LTPt->clear();
    T1_LTValidHits->clear();
    T1_LTvalid->clear();
    T1_LTvx->clear();
    T1_LTvy->clear();
    T1_LTvz->clear();
    T1_MomentumRank->clear();
    T1_NProngs->clear();
    T1_NSignalGammas->clear();
    T1_NSignalNeutrals->clear();
    T1_P->clear();
    T2_Charge->clear();
    T2_DecayMode->clear();
    T2_EmFraction->clear();
    T2_GenMatchDaughter0Id->clear();
    T2_GenMatchDaughter0Status->clear();
    T2_GenMatchDaughter1Id->clear();
    T2_GenMatchDaughter1Status->clear();
    T2_GenMatchGrandmother00Id->clear();
    T2_GenMatchGrandmother00Status->clear();
    T2_GenMatchGrandmother01Id->clear();
    T2_GenMatchGrandmother01Status->clear();
    T2_GenMatchGrandmother10Id->clear();
    T2_GenMatchGrandmother10Status->clear();
    T2_GenMatchGrandmother11Id->clear();
    T2_GenMatchGrandmother11Status->clear();
    T2_GenMatchId->clear();
    T2_GenMatchMother0Id->clear();
    T2_GenMatchMother0Status->clear();
    T2_GenMatchMother1Id->clear();
    T2_GenMatchMother1Status->clear();
    T2_GenMatchStatus->clear();
    T2_HPSagainstElectronDeadECAL->clear();
    T2_HPSagainstElectronLoose->clear();
    T2_HPSagainstElectronLooseMVA2->clear();
    T2_HPSagainstElectronLooseMVA3->clear();
    T2_HPSagainstElectronMVA->clear();
    T2_HPSagainstElectronMVA2category->clear();
    T2_HPSagainstElectronMVA2raw->clear();
    T2_HPSagainstElectronMVA3category->clear();
    T2_HPSagainstElectronMVA3raw->clear();
    T2_HPSagainstElectronMedium->clear();
    T2_HPSagainstElectronMediumMVA2->clear();
    T2_HPSagainstElectronMediumMVA3->clear();
    T2_HPSagainstElectronTight->clear();
    T2_HPSagainstElectronTightMVA2->clear();
    T2_HPSagainstElectronTightMVA3->clear();
    T2_HPSagainstElectronVLooseMVA2->clear();
    T2_HPSagainstElectronVTightMVA3->clear();
    T2_HPSagainstMuonLoose->clear();
    T2_HPSagainstMuonLoose2->clear();
    T2_HPSagainstMuonMedium->clear();
    T2_HPSagainstMuonMedium2->clear();
    T2_HPSagainstMuonTight->clear();
    T2_HPSagainstMuonTight2->clear();
    T2_HPSbyCombinedIsolationDeltaBetaCorrRaw->clear();
    T2_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits->clear();
    T2_HPSbyIsolationMVA2raw->clear();
    T2_HPSbyIsolationMVAraw->clear();
    T2_HPSbyLooseCombinedIsolationDeltaBetaCorr->clear();
    T2_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits->clear();
    T2_HPSbyLooseIsolationMVA->clear();
    T2_HPSbyLooseIsolationMVA2->clear();
    T2_HPSbyMediumCombinedIsolationDeltaBetaCorr->clear();
    T2_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits->clear();
    T2_HPSbyMediumIsolationMVA->clear();
    T2_HPSbyMediumIsolationMVA2->clear();
    T2_HPSbyTightCombinedIsolationDeltaBetaCorr->clear();
    T2_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits->clear();
    T2_HPSbyTightIsolationMVA->clear();
    T2_HPSbyTightIsolationMVA2->clear();
    T2_HPSbyVLooseCombinedIsolationDeltaBetaCorr->clear();
    T2_HPSdecayModeFinding->clear();
    T2_IsInTheCracks->clear();
    T2_JetCSV->clear();
    T2_LTIpVtdxy->clear();
    T2_LTIpVtdxyError->clear();
    T2_LTIpVtdz->clear();
    T2_LTIpVtdzError->clear();
    T2_LTNormChiSqrd->clear();
    T2_LTPt->clear();
    T2_LTValidHits->clear();
    T2_LTvalid->clear();
    T2_LTvx->clear();
    T2_LTvy->clear();
    T2_LTvz->clear();
    T2_MomentumRank->clear();
    T2_NProngs->clear();
    T2_NSignalGammas->clear();
    T2_NSignalNeutrals->clear();
    T2_P->clear();
    // >>> End clear <<<
}

void
ttl::Branches::Delete()
{
    roast::Branches::Delete();

    // >>> Begin delete <<<
    delete L_Charge;
    delete L_CorrectedD0;
    delete L_CorrectedDZ;
    delete L_EventWeight;
    delete L_GenMatchDaughter0Id;
    delete L_GenMatchDaughter0Status;
    delete L_GenMatchDaughter1Id;
    delete L_GenMatchDaughter1Status;
    delete L_GenMatchGrandmother00Id;
    delete L_GenMatchGrandmother00Status;
    delete L_GenMatchGrandmother01Id;
    delete L_GenMatchGrandmother01Status;
    delete L_GenMatchGrandmother10Id;
    delete L_GenMatchGrandmother10Status;
    delete L_GenMatchGrandmother11Id;
    delete L_GenMatchGrandmother11Status;
    delete L_GenMatchId;
    delete L_GenMatchMother0Id;
    delete L_GenMatchMother0Status;
    delete L_GenMatchMother1Id;
    delete L_GenMatchMother1Status;
    delete L_GenMatchStatus;
    delete L_ImpactParameter;
    delete L_IsElectron;
    delete L_IsLoose;
    delete L_IsMuon;
    delete L_IsTight;
    delete L_P;
    delete L_RelIso;
    delete RT_Charge;
    delete RT_DecayMode;
    delete RT_EmFraction;
    delete RT_GenMatchDaughter0Id;
    delete RT_GenMatchDaughter0Status;
    delete RT_GenMatchDaughter1Id;
    delete RT_GenMatchDaughter1Status;
    delete RT_GenMatchGrandmother00Id;
    delete RT_GenMatchGrandmother00Status;
    delete RT_GenMatchGrandmother01Id;
    delete RT_GenMatchGrandmother01Status;
    delete RT_GenMatchGrandmother10Id;
    delete RT_GenMatchGrandmother10Status;
    delete RT_GenMatchGrandmother11Id;
    delete RT_GenMatchGrandmother11Status;
    delete RT_GenMatchId;
    delete RT_GenMatchMother0Id;
    delete RT_GenMatchMother0Status;
    delete RT_GenMatchMother1Id;
    delete RT_GenMatchMother1Status;
    delete RT_GenMatchStatus;
    delete RT_HPSagainstElectronDeadECAL;
    delete RT_HPSagainstElectronLoose;
    delete RT_HPSagainstElectronLooseMVA2;
    delete RT_HPSagainstElectronLooseMVA3;
    delete RT_HPSagainstElectronMVA;
    delete RT_HPSagainstElectronMVA2category;
    delete RT_HPSagainstElectronMVA2raw;
    delete RT_HPSagainstElectronMVA3category;
    delete RT_HPSagainstElectronMVA3raw;
    delete RT_HPSagainstElectronMedium;
    delete RT_HPSagainstElectronMediumMVA2;
    delete RT_HPSagainstElectronMediumMVA3;
    delete RT_HPSagainstElectronTight;
    delete RT_HPSagainstElectronTightMVA2;
    delete RT_HPSagainstElectronTightMVA3;
    delete RT_HPSagainstElectronVLooseMVA2;
    delete RT_HPSagainstElectronVTightMVA3;
    delete RT_HPSagainstMuonLoose;
    delete RT_HPSagainstMuonLoose2;
    delete RT_HPSagainstMuonMedium;
    delete RT_HPSagainstMuonMedium2;
    delete RT_HPSagainstMuonTight;
    delete RT_HPSagainstMuonTight2;
    delete RT_HPSbyCombinedIsolationDeltaBetaCorrRaw;
    delete RT_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits;
    delete RT_HPSbyIsolationMVA2raw;
    delete RT_HPSbyIsolationMVAraw;
    delete RT_HPSbyLooseCombinedIsolationDeltaBetaCorr;
    delete RT_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits;
    delete RT_HPSbyLooseIsolationMVA;
    delete RT_HPSbyLooseIsolationMVA2;
    delete RT_HPSbyMediumCombinedIsolationDeltaBetaCorr;
    delete RT_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits;
    delete RT_HPSbyMediumIsolationMVA;
    delete RT_HPSbyMediumIsolationMVA2;
    delete RT_HPSbyTightCombinedIsolationDeltaBetaCorr;
    delete RT_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits;
    delete RT_HPSbyTightIsolationMVA;
    delete RT_HPSbyTightIsolationMVA2;
    delete RT_HPSbyVLooseCombinedIsolationDeltaBetaCorr;
    delete RT_HPSdecayModeFinding;
    delete RT_IsInTheCracks;
    delete RT_JetCSV;
    delete RT_LTIpVtdxy;
    delete RT_LTIpVtdxyError;
    delete RT_LTIpVtdz;
    delete RT_LTIpVtdzError;
    delete RT_LTNormChiSqrd;
    delete RT_LTPt;
    delete RT_LTValidHits;
    delete RT_LTvalid;
    delete RT_LTvx;
    delete RT_LTvy;
    delete RT_LTvz;
    delete RT_MomentumRank;
    delete RT_NProngs;
    delete RT_NSignalGammas;
    delete RT_NSignalNeutrals;
    delete RT_P;
    delete T1_Charge;
    delete T1_DecayMode;
    delete T1_EmFraction;
    delete T1_GenMatchDaughter0Id;
    delete T1_GenMatchDaughter0Status;
    delete T1_GenMatchDaughter1Id;
    delete T1_GenMatchDaughter1Status;
    delete T1_GenMatchGrandmother00Id;
    delete T1_GenMatchGrandmother00Status;
    delete T1_GenMatchGrandmother01Id;
    delete T1_GenMatchGrandmother01Status;
    delete T1_GenMatchGrandmother10Id;
    delete T1_GenMatchGrandmother10Status;
    delete T1_GenMatchGrandmother11Id;
    delete T1_GenMatchGrandmother11Status;
    delete T1_GenMatchId;
    delete T1_GenMatchMother0Id;
    delete T1_GenMatchMother0Status;
    delete T1_GenMatchMother1Id;
    delete T1_GenMatchMother1Status;
    delete T1_GenMatchStatus;
    delete T1_HPSagainstElectronDeadECAL;
    delete T1_HPSagainstElectronLoose;
    delete T1_HPSagainstElectronLooseMVA2;
    delete T1_HPSagainstElectronLooseMVA3;
    delete T1_HPSagainstElectronMVA;
    delete T1_HPSagainstElectronMVA2category;
    delete T1_HPSagainstElectronMVA2raw;
    delete T1_HPSagainstElectronMVA3category;
    delete T1_HPSagainstElectronMVA3raw;
    delete T1_HPSagainstElectronMedium;
    delete T1_HPSagainstElectronMediumMVA2;
    delete T1_HPSagainstElectronMediumMVA3;
    delete T1_HPSagainstElectronTight;
    delete T1_HPSagainstElectronTightMVA2;
    delete T1_HPSagainstElectronTightMVA3;
    delete T1_HPSagainstElectronVLooseMVA2;
    delete T1_HPSagainstElectronVTightMVA3;
    delete T1_HPSagainstMuonLoose;
    delete T1_HPSagainstMuonLoose2;
    delete T1_HPSagainstMuonMedium;
    delete T1_HPSagainstMuonMedium2;
    delete T1_HPSagainstMuonTight;
    delete T1_HPSagainstMuonTight2;
    delete T1_HPSbyCombinedIsolationDeltaBetaCorrRaw;
    delete T1_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits;
    delete T1_HPSbyIsolationMVA2raw;
    delete T1_HPSbyIsolationMVAraw;
    delete T1_HPSbyLooseCombinedIsolationDeltaBetaCorr;
    delete T1_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits;
    delete T1_HPSbyLooseIsolationMVA;
    delete T1_HPSbyLooseIsolationMVA2;
    delete T1_HPSbyMediumCombinedIsolationDeltaBetaCorr;
    delete T1_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits;
    delete T1_HPSbyMediumIsolationMVA;
    delete T1_HPSbyMediumIsolationMVA2;
    delete T1_HPSbyTightCombinedIsolationDeltaBetaCorr;
    delete T1_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits;
    delete T1_HPSbyTightIsolationMVA;
    delete T1_HPSbyTightIsolationMVA2;
    delete T1_HPSbyVLooseCombinedIsolationDeltaBetaCorr;
    delete T1_HPSdecayModeFinding;
    delete T1_IsInTheCracks;
    delete T1_JetCSV;
    delete T1_LTIpVtdxy;
    delete T1_LTIpVtdxyError;
    delete T1_LTIpVtdz;
    delete T1_LTIpVtdzError;
    delete T1_LTNormChiSqrd;
    delete T1_LTPt;
    delete T1_LTValidHits;
    delete T1_LTvalid;
    delete T1_LTvx;
    delete T1_LTvy;
    delete T1_LTvz;
    delete T1_MomentumRank;
    delete T1_NProngs;
    delete T1_NSignalGammas;
    delete T1_NSignalNeutrals;
    delete T1_P;
    delete T2_Charge;
    delete T2_DecayMode;
    delete T2_EmFraction;
    delete T2_GenMatchDaughter0Id;
    delete T2_GenMatchDaughter0Status;
    delete T2_GenMatchDaughter1Id;
    delete T2_GenMatchDaughter1Status;
    delete T2_GenMatchGrandmother00Id;
    delete T2_GenMatchGrandmother00Status;
    delete T2_GenMatchGrandmother01Id;
    delete T2_GenMatchGrandmother01Status;
    delete T2_GenMatchGrandmother10Id;
    delete T2_GenMatchGrandmother10Status;
    delete T2_GenMatchGrandmother11Id;
    delete T2_GenMatchGrandmother11Status;
    delete T2_GenMatchId;
    delete T2_GenMatchMother0Id;
    delete T2_GenMatchMother0Status;
    delete T2_GenMatchMother1Id;
    delete T2_GenMatchMother1Status;
    delete T2_GenMatchStatus;
    delete T2_HPSagainstElectronDeadECAL;
    delete T2_HPSagainstElectronLoose;
    delete T2_HPSagainstElectronLooseMVA2;
    delete T2_HPSagainstElectronLooseMVA3;
    delete T2_HPSagainstElectronMVA;
    delete T2_HPSagainstElectronMVA2category;
    delete T2_HPSagainstElectronMVA2raw;
    delete T2_HPSagainstElectronMVA3category;
    delete T2_HPSagainstElectronMVA3raw;
    delete T2_HPSagainstElectronMedium;
    delete T2_HPSagainstElectronMediumMVA2;
    delete T2_HPSagainstElectronMediumMVA3;
    delete T2_HPSagainstElectronTight;
    delete T2_HPSagainstElectronTightMVA2;
    delete T2_HPSagainstElectronTightMVA3;
    delete T2_HPSagainstElectronVLooseMVA2;
    delete T2_HPSagainstElectronVTightMVA3;
    delete T2_HPSagainstMuonLoose;
    delete T2_HPSagainstMuonLoose2;
    delete T2_HPSagainstMuonMedium;
    delete T2_HPSagainstMuonMedium2;
    delete T2_HPSagainstMuonTight;
    delete T2_HPSagainstMuonTight2;
    delete T2_HPSbyCombinedIsolationDeltaBetaCorrRaw;
    delete T2_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits;
    delete T2_HPSbyIsolationMVA2raw;
    delete T2_HPSbyIsolationMVAraw;
    delete T2_HPSbyLooseCombinedIsolationDeltaBetaCorr;
    delete T2_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits;
    delete T2_HPSbyLooseIsolationMVA;
    delete T2_HPSbyLooseIsolationMVA2;
    delete T2_HPSbyMediumCombinedIsolationDeltaBetaCorr;
    delete T2_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits;
    delete T2_HPSbyMediumIsolationMVA;
    delete T2_HPSbyMediumIsolationMVA2;
    delete T2_HPSbyTightCombinedIsolationDeltaBetaCorr;
    delete T2_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits;
    delete T2_HPSbyTightIsolationMVA;
    delete T2_HPSbyTightIsolationMVA2;
    delete T2_HPSbyVLooseCombinedIsolationDeltaBetaCorr;
    delete T2_HPSdecayModeFinding;
    delete T2_IsInTheCracks;
    delete T2_JetCSV;
    delete T2_LTIpVtdxy;
    delete T2_LTIpVtdxyError;
    delete T2_LTIpVtdz;
    delete T2_LTIpVtdzError;
    delete T2_LTNormChiSqrd;
    delete T2_LTPt;
    delete T2_LTValidHits;
    delete T2_LTvalid;
    delete T2_LTvx;
    delete T2_LTvy;
    delete T2_LTvz;
    delete T2_MomentumRank;
    delete T2_NProngs;
    delete T2_NSignalGammas;
    delete T2_NSignalNeutrals;
    delete T2_P;
    // >>> End delete <<<
}

void
ttl::Branches::Null()
{
    roast::Branches::Null();

    // >>> Begin null <<<
    L_Charge = 0;
    L_CorrectedD0 = 0;
    L_CorrectedDZ = 0;
    L_EventWeight = 0;
    L_GenMatchDaughter0Id = 0;
    L_GenMatchDaughter0Status = 0;
    L_GenMatchDaughter1Id = 0;
    L_GenMatchDaughter1Status = 0;
    L_GenMatchGrandmother00Id = 0;
    L_GenMatchGrandmother00Status = 0;
    L_GenMatchGrandmother01Id = 0;
    L_GenMatchGrandmother01Status = 0;
    L_GenMatchGrandmother10Id = 0;
    L_GenMatchGrandmother10Status = 0;
    L_GenMatchGrandmother11Id = 0;
    L_GenMatchGrandmother11Status = 0;
    L_GenMatchId = 0;
    L_GenMatchMother0Id = 0;
    L_GenMatchMother0Status = 0;
    L_GenMatchMother1Id = 0;
    L_GenMatchMother1Status = 0;
    L_GenMatchStatus = 0;
    L_ImpactParameter = 0;
    L_IsElectron = 0;
    L_IsLoose = 0;
    L_IsMuon = 0;
    L_IsTight = 0;
    L_P = 0;
    L_RelIso = 0;
    NumRecoTaus = 0;
    RT_Charge = 0;
    RT_DecayMode = 0;
    RT_EmFraction = 0;
    RT_GenMatchDaughter0Id = 0;
    RT_GenMatchDaughter0Status = 0;
    RT_GenMatchDaughter1Id = 0;
    RT_GenMatchDaughter1Status = 0;
    RT_GenMatchGrandmother00Id = 0;
    RT_GenMatchGrandmother00Status = 0;
    RT_GenMatchGrandmother01Id = 0;
    RT_GenMatchGrandmother01Status = 0;
    RT_GenMatchGrandmother10Id = 0;
    RT_GenMatchGrandmother10Status = 0;
    RT_GenMatchGrandmother11Id = 0;
    RT_GenMatchGrandmother11Status = 0;
    RT_GenMatchId = 0;
    RT_GenMatchMother0Id = 0;
    RT_GenMatchMother0Status = 0;
    RT_GenMatchMother1Id = 0;
    RT_GenMatchMother1Status = 0;
    RT_GenMatchStatus = 0;
    RT_HPSagainstElectronDeadECAL = 0;
    RT_HPSagainstElectronLoose = 0;
    RT_HPSagainstElectronLooseMVA2 = 0;
    RT_HPSagainstElectronLooseMVA3 = 0;
    RT_HPSagainstElectronMVA = 0;
    RT_HPSagainstElectronMVA2category = 0;
    RT_HPSagainstElectronMVA2raw = 0;
    RT_HPSagainstElectronMVA3category = 0;
    RT_HPSagainstElectronMVA3raw = 0;
    RT_HPSagainstElectronMedium = 0;
    RT_HPSagainstElectronMediumMVA2 = 0;
    RT_HPSagainstElectronMediumMVA3 = 0;
    RT_HPSagainstElectronTight = 0;
    RT_HPSagainstElectronTightMVA2 = 0;
    RT_HPSagainstElectronTightMVA3 = 0;
    RT_HPSagainstElectronVLooseMVA2 = 0;
    RT_HPSagainstElectronVTightMVA3 = 0;
    RT_HPSagainstMuonLoose = 0;
    RT_HPSagainstMuonLoose2 = 0;
    RT_HPSagainstMuonMedium = 0;
    RT_HPSagainstMuonMedium2 = 0;
    RT_HPSagainstMuonTight = 0;
    RT_HPSagainstMuonTight2 = 0;
    RT_HPSbyCombinedIsolationDeltaBetaCorrRaw = 0;
    RT_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits = 0;
    RT_HPSbyIsolationMVA2raw = 0;
    RT_HPSbyIsolationMVAraw = 0;
    RT_HPSbyLooseCombinedIsolationDeltaBetaCorr = 0;
    RT_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits = 0;
    RT_HPSbyLooseIsolationMVA = 0;
    RT_HPSbyLooseIsolationMVA2 = 0;
    RT_HPSbyMediumCombinedIsolationDeltaBetaCorr = 0;
    RT_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits = 0;
    RT_HPSbyMediumIsolationMVA = 0;
    RT_HPSbyMediumIsolationMVA2 = 0;
    RT_HPSbyTightCombinedIsolationDeltaBetaCorr = 0;
    RT_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits = 0;
    RT_HPSbyTightIsolationMVA = 0;
    RT_HPSbyTightIsolationMVA2 = 0;
    RT_HPSbyVLooseCombinedIsolationDeltaBetaCorr = 0;
    RT_HPSdecayModeFinding = 0;
    RT_IsInTheCracks = 0;
    RT_JetCSV = 0;
    RT_LTIpVtdxy = 0;
    RT_LTIpVtdxyError = 0;
    RT_LTIpVtdz = 0;
    RT_LTIpVtdzError = 0;
    RT_LTNormChiSqrd = 0;
    RT_LTPt = 0;
    RT_LTValidHits = 0;
    RT_LTvalid = 0;
    RT_LTvx = 0;
    RT_LTvy = 0;
    RT_LTvz = 0;
    RT_MomentumRank = 0;
    RT_NProngs = 0;
    RT_NSignalGammas = 0;
    RT_NSignalNeutrals = 0;
    RT_P = 0;
    T1_Charge = 0;
    T1_DecayMode = 0;
    T1_EmFraction = 0;
    T1_GenMatchDaughter0Id = 0;
    T1_GenMatchDaughter0Status = 0;
    T1_GenMatchDaughter1Id = 0;
    T1_GenMatchDaughter1Status = 0;
    T1_GenMatchGrandmother00Id = 0;
    T1_GenMatchGrandmother00Status = 0;
    T1_GenMatchGrandmother01Id = 0;
    T1_GenMatchGrandmother01Status = 0;
    T1_GenMatchGrandmother10Id = 0;
    T1_GenMatchGrandmother10Status = 0;
    T1_GenMatchGrandmother11Id = 0;
    T1_GenMatchGrandmother11Status = 0;
    T1_GenMatchId = 0;
    T1_GenMatchMother0Id = 0;
    T1_GenMatchMother0Status = 0;
    T1_GenMatchMother1Id = 0;
    T1_GenMatchMother1Status = 0;
    T1_GenMatchStatus = 0;
    T1_HPSagainstElectronDeadECAL = 0;
    T1_HPSagainstElectronLoose = 0;
    T1_HPSagainstElectronLooseMVA2 = 0;
    T1_HPSagainstElectronLooseMVA3 = 0;
    T1_HPSagainstElectronMVA = 0;
    T1_HPSagainstElectronMVA2category = 0;
    T1_HPSagainstElectronMVA2raw = 0;
    T1_HPSagainstElectronMVA3category = 0;
    T1_HPSagainstElectronMVA3raw = 0;
    T1_HPSagainstElectronMedium = 0;
    T1_HPSagainstElectronMediumMVA2 = 0;
    T1_HPSagainstElectronMediumMVA3 = 0;
    T1_HPSagainstElectronTight = 0;
    T1_HPSagainstElectronTightMVA2 = 0;
    T1_HPSagainstElectronTightMVA3 = 0;
    T1_HPSagainstElectronVLooseMVA2 = 0;
    T1_HPSagainstElectronVTightMVA3 = 0;
    T1_HPSagainstMuonLoose = 0;
    T1_HPSagainstMuonLoose2 = 0;
    T1_HPSagainstMuonMedium = 0;
    T1_HPSagainstMuonMedium2 = 0;
    T1_HPSagainstMuonTight = 0;
    T1_HPSagainstMuonTight2 = 0;
    T1_HPSbyCombinedIsolationDeltaBetaCorrRaw = 0;
    T1_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits = 0;
    T1_HPSbyIsolationMVA2raw = 0;
    T1_HPSbyIsolationMVAraw = 0;
    T1_HPSbyLooseCombinedIsolationDeltaBetaCorr = 0;
    T1_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits = 0;
    T1_HPSbyLooseIsolationMVA = 0;
    T1_HPSbyLooseIsolationMVA2 = 0;
    T1_HPSbyMediumCombinedIsolationDeltaBetaCorr = 0;
    T1_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits = 0;
    T1_HPSbyMediumIsolationMVA = 0;
    T1_HPSbyMediumIsolationMVA2 = 0;
    T1_HPSbyTightCombinedIsolationDeltaBetaCorr = 0;
    T1_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits = 0;
    T1_HPSbyTightIsolationMVA = 0;
    T1_HPSbyTightIsolationMVA2 = 0;
    T1_HPSbyVLooseCombinedIsolationDeltaBetaCorr = 0;
    T1_HPSdecayModeFinding = 0;
    T1_IsInTheCracks = 0;
    T1_JetCSV = 0;
    T1_LTIpVtdxy = 0;
    T1_LTIpVtdxyError = 0;
    T1_LTIpVtdz = 0;
    T1_LTIpVtdzError = 0;
    T1_LTNormChiSqrd = 0;
    T1_LTPt = 0;
    T1_LTValidHits = 0;
    T1_LTvalid = 0;
    T1_LTvx = 0;
    T1_LTvy = 0;
    T1_LTvz = 0;
    T1_MomentumRank = 0;
    T1_NProngs = 0;
    T1_NSignalGammas = 0;
    T1_NSignalNeutrals = 0;
    T1_P = 0;
    T2_Charge = 0;
    T2_DecayMode = 0;
    T2_EmFraction = 0;
    T2_GenMatchDaughter0Id = 0;
    T2_GenMatchDaughter0Status = 0;
    T2_GenMatchDaughter1Id = 0;
    T2_GenMatchDaughter1Status = 0;
    T2_GenMatchGrandmother00Id = 0;
    T2_GenMatchGrandmother00Status = 0;
    T2_GenMatchGrandmother01Id = 0;
    T2_GenMatchGrandmother01Status = 0;
    T2_GenMatchGrandmother10Id = 0;
    T2_GenMatchGrandmother10Status = 0;
    T2_GenMatchGrandmother11Id = 0;
    T2_GenMatchGrandmother11Status = 0;
    T2_GenMatchId = 0;
    T2_GenMatchMother0Id = 0;
    T2_GenMatchMother0Status = 0;
    T2_GenMatchMother1Id = 0;
    T2_GenMatchMother1Status = 0;
    T2_GenMatchStatus = 0;
    T2_HPSagainstElectronDeadECAL = 0;
    T2_HPSagainstElectronLoose = 0;
    T2_HPSagainstElectronLooseMVA2 = 0;
    T2_HPSagainstElectronLooseMVA3 = 0;
    T2_HPSagainstElectronMVA = 0;
    T2_HPSagainstElectronMVA2category = 0;
    T2_HPSagainstElectronMVA2raw = 0;
    T2_HPSagainstElectronMVA3category = 0;
    T2_HPSagainstElectronMVA3raw = 0;
    T2_HPSagainstElectronMedium = 0;
    T2_HPSagainstElectronMediumMVA2 = 0;
    T2_HPSagainstElectronMediumMVA3 = 0;
    T2_HPSagainstElectronTight = 0;
    T2_HPSagainstElectronTightMVA2 = 0;
    T2_HPSagainstElectronTightMVA3 = 0;
    T2_HPSagainstElectronVLooseMVA2 = 0;
    T2_HPSagainstElectronVTightMVA3 = 0;
    T2_HPSagainstMuonLoose = 0;
    T2_HPSagainstMuonLoose2 = 0;
    T2_HPSagainstMuonMedium = 0;
    T2_HPSagainstMuonMedium2 = 0;
    T2_HPSagainstMuonTight = 0;
    T2_HPSagainstMuonTight2 = 0;
    T2_HPSbyCombinedIsolationDeltaBetaCorrRaw = 0;
    T2_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits = 0;
    T2_HPSbyIsolationMVA2raw = 0;
    T2_HPSbyIsolationMVAraw = 0;
    T2_HPSbyLooseCombinedIsolationDeltaBetaCorr = 0;
    T2_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits = 0;
    T2_HPSbyLooseIsolationMVA = 0;
    T2_HPSbyLooseIsolationMVA2 = 0;
    T2_HPSbyMediumCombinedIsolationDeltaBetaCorr = 0;
    T2_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits = 0;
    T2_HPSbyMediumIsolationMVA = 0;
    T2_HPSbyMediumIsolationMVA2 = 0;
    T2_HPSbyTightCombinedIsolationDeltaBetaCorr = 0;
    T2_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits = 0;
    T2_HPSbyTightIsolationMVA = 0;
    T2_HPSbyTightIsolationMVA2 = 0;
    T2_HPSbyVLooseCombinedIsolationDeltaBetaCorr = 0;
    T2_HPSdecayModeFinding = 0;
    T2_IsInTheCracks = 0;
    T2_JetCSV = 0;
    T2_LTIpVtdxy = 0;
    T2_LTIpVtdxyError = 0;
    T2_LTIpVtdz = 0;
    T2_LTIpVtdzError = 0;
    T2_LTNormChiSqrd = 0;
    T2_LTPt = 0;
    T2_LTValidHits = 0;
    T2_LTvalid = 0;
    T2_LTvx = 0;
    T2_LTvy = 0;
    T2_LTvz = 0;
    T2_MomentumRank = 0;
    T2_NProngs = 0;
    T2_NSignalGammas = 0;
    T2_NSignalNeutrals = 0;
    T2_P = 0;
    // >>> End null <<<
}

void
ttl::Branches::SetBranchAddresses()
{
    roast::Branches::SetBranchAddresses();

    // >>> Begin address <<<
    fChain->SetBranchAddress("L_Charge", &L_Charge);
    fChain->SetBranchAddress("L_CorrectedD0", &L_CorrectedD0);
    fChain->SetBranchAddress("L_CorrectedDZ", &L_CorrectedDZ);
    fChain->SetBranchAddress("L_EventWeight", &L_EventWeight);
    fChain->SetBranchAddress("L_GenMatchDaughter0Id", &L_GenMatchDaughter0Id);
    fChain->SetBranchAddress("L_GenMatchDaughter0Status", &L_GenMatchDaughter0Status);
    fChain->SetBranchAddress("L_GenMatchDaughter1Id", &L_GenMatchDaughter1Id);
    fChain->SetBranchAddress("L_GenMatchDaughter1Status", &L_GenMatchDaughter1Status);
    fChain->SetBranchAddress("L_GenMatchGrandmother00Id", &L_GenMatchGrandmother00Id);
    fChain->SetBranchAddress("L_GenMatchGrandmother00Status", &L_GenMatchGrandmother00Status);
    fChain->SetBranchAddress("L_GenMatchGrandmother01Id", &L_GenMatchGrandmother01Id);
    fChain->SetBranchAddress("L_GenMatchGrandmother01Status", &L_GenMatchGrandmother01Status);
    fChain->SetBranchAddress("L_GenMatchGrandmother10Id", &L_GenMatchGrandmother10Id);
    fChain->SetBranchAddress("L_GenMatchGrandmother10Status", &L_GenMatchGrandmother10Status);
    fChain->SetBranchAddress("L_GenMatchGrandmother11Id", &L_GenMatchGrandmother11Id);
    fChain->SetBranchAddress("L_GenMatchGrandmother11Status", &L_GenMatchGrandmother11Status);
    fChain->SetBranchAddress("L_GenMatchId", &L_GenMatchId);
    fChain->SetBranchAddress("L_GenMatchMother0Id", &L_GenMatchMother0Id);
    fChain->SetBranchAddress("L_GenMatchMother0Status", &L_GenMatchMother0Status);
    fChain->SetBranchAddress("L_GenMatchMother1Id", &L_GenMatchMother1Id);
    fChain->SetBranchAddress("L_GenMatchMother1Status", &L_GenMatchMother1Status);
    fChain->SetBranchAddress("L_GenMatchStatus", &L_GenMatchStatus);
    fChain->SetBranchAddress("L_ImpactParameter", &L_ImpactParameter);
    fChain->SetBranchAddress("L_IsElectron", &L_IsElectron);
    fChain->SetBranchAddress("L_IsLoose", &L_IsLoose);
    fChain->SetBranchAddress("L_IsMuon", &L_IsMuon);
    fChain->SetBranchAddress("L_IsTight", &L_IsTight);
    fChain->SetBranchAddress("L_P", &L_P);
    fChain->SetBranchAddress("L_RelIso", &L_RelIso);
    fChain->SetBranchAddress("NumRecoTaus", &NumRecoTaus);
    fChain->SetBranchAddress("RT_Charge", &RT_Charge);
    fChain->SetBranchAddress("RT_DecayMode", &RT_DecayMode);
    fChain->SetBranchAddress("RT_EmFraction", &RT_EmFraction);
    fChain->SetBranchAddress("RT_GenMatchDaughter0Id", &RT_GenMatchDaughter0Id);
    fChain->SetBranchAddress("RT_GenMatchDaughter0Status", &RT_GenMatchDaughter0Status);
    fChain->SetBranchAddress("RT_GenMatchDaughter1Id", &RT_GenMatchDaughter1Id);
    fChain->SetBranchAddress("RT_GenMatchDaughter1Status", &RT_GenMatchDaughter1Status);
    fChain->SetBranchAddress("RT_GenMatchGrandmother00Id", &RT_GenMatchGrandmother00Id);
    fChain->SetBranchAddress("RT_GenMatchGrandmother00Status", &RT_GenMatchGrandmother00Status);
    fChain->SetBranchAddress("RT_GenMatchGrandmother01Id", &RT_GenMatchGrandmother01Id);
    fChain->SetBranchAddress("RT_GenMatchGrandmother01Status", &RT_GenMatchGrandmother01Status);
    fChain->SetBranchAddress("RT_GenMatchGrandmother10Id", &RT_GenMatchGrandmother10Id);
    fChain->SetBranchAddress("RT_GenMatchGrandmother10Status", &RT_GenMatchGrandmother10Status);
    fChain->SetBranchAddress("RT_GenMatchGrandmother11Id", &RT_GenMatchGrandmother11Id);
    fChain->SetBranchAddress("RT_GenMatchGrandmother11Status", &RT_GenMatchGrandmother11Status);
    fChain->SetBranchAddress("RT_GenMatchId", &RT_GenMatchId);
    fChain->SetBranchAddress("RT_GenMatchMother0Id", &RT_GenMatchMother0Id);
    fChain->SetBranchAddress("RT_GenMatchMother0Status", &RT_GenMatchMother0Status);
    fChain->SetBranchAddress("RT_GenMatchMother1Id", &RT_GenMatchMother1Id);
    fChain->SetBranchAddress("RT_GenMatchMother1Status", &RT_GenMatchMother1Status);
    fChain->SetBranchAddress("RT_GenMatchStatus", &RT_GenMatchStatus);
    fChain->SetBranchAddress("RT_HPSagainstElectronDeadECAL", &RT_HPSagainstElectronDeadECAL);
    fChain->SetBranchAddress("RT_HPSagainstElectronLoose", &RT_HPSagainstElectronLoose);
    fChain->SetBranchAddress("RT_HPSagainstElectronLooseMVA2", &RT_HPSagainstElectronLooseMVA2);
    fChain->SetBranchAddress("RT_HPSagainstElectronLooseMVA3", &RT_HPSagainstElectronLooseMVA3);
    fChain->SetBranchAddress("RT_HPSagainstElectronMVA", &RT_HPSagainstElectronMVA);
    fChain->SetBranchAddress("RT_HPSagainstElectronMVA2category", &RT_HPSagainstElectronMVA2category);
    fChain->SetBranchAddress("RT_HPSagainstElectronMVA2raw", &RT_HPSagainstElectronMVA2raw);
    fChain->SetBranchAddress("RT_HPSagainstElectronMVA3category", &RT_HPSagainstElectronMVA3category);
    fChain->SetBranchAddress("RT_HPSagainstElectronMVA3raw", &RT_HPSagainstElectronMVA3raw);
    fChain->SetBranchAddress("RT_HPSagainstElectronMedium", &RT_HPSagainstElectronMedium);
    fChain->SetBranchAddress("RT_HPSagainstElectronMediumMVA2", &RT_HPSagainstElectronMediumMVA2);
    fChain->SetBranchAddress("RT_HPSagainstElectronMediumMVA3", &RT_HPSagainstElectronMediumMVA3);
    fChain->SetBranchAddress("RT_HPSagainstElectronTight", &RT_HPSagainstElectronTight);
    fChain->SetBranchAddress("RT_HPSagainstElectronTightMVA2", &RT_HPSagainstElectronTightMVA2);
    fChain->SetBranchAddress("RT_HPSagainstElectronTightMVA3", &RT_HPSagainstElectronTightMVA3);
    fChain->SetBranchAddress("RT_HPSagainstElectronVLooseMVA2", &RT_HPSagainstElectronVLooseMVA2);
    fChain->SetBranchAddress("RT_HPSagainstElectronVTightMVA3", &RT_HPSagainstElectronVTightMVA3);
    fChain->SetBranchAddress("RT_HPSagainstMuonLoose", &RT_HPSagainstMuonLoose);
    fChain->SetBranchAddress("RT_HPSagainstMuonLoose2", &RT_HPSagainstMuonLoose2);
    fChain->SetBranchAddress("RT_HPSagainstMuonMedium", &RT_HPSagainstMuonMedium);
    fChain->SetBranchAddress("RT_HPSagainstMuonMedium2", &RT_HPSagainstMuonMedium2);
    fChain->SetBranchAddress("RT_HPSagainstMuonTight", &RT_HPSagainstMuonTight);
    fChain->SetBranchAddress("RT_HPSagainstMuonTight2", &RT_HPSagainstMuonTight2);
    fChain->SetBranchAddress("RT_HPSbyCombinedIsolationDeltaBetaCorrRaw", &RT_HPSbyCombinedIsolationDeltaBetaCorrRaw);
    fChain->SetBranchAddress("RT_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits", &RT_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits);
    fChain->SetBranchAddress("RT_HPSbyIsolationMVA2raw", &RT_HPSbyIsolationMVA2raw);
    fChain->SetBranchAddress("RT_HPSbyIsolationMVAraw", &RT_HPSbyIsolationMVAraw);
    fChain->SetBranchAddress("RT_HPSbyLooseCombinedIsolationDeltaBetaCorr", &RT_HPSbyLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("RT_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits", &RT_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("RT_HPSbyLooseIsolationMVA", &RT_HPSbyLooseIsolationMVA);
    fChain->SetBranchAddress("RT_HPSbyLooseIsolationMVA2", &RT_HPSbyLooseIsolationMVA2);
    fChain->SetBranchAddress("RT_HPSbyMediumCombinedIsolationDeltaBetaCorr", &RT_HPSbyMediumCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("RT_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits", &RT_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("RT_HPSbyMediumIsolationMVA", &RT_HPSbyMediumIsolationMVA);
    fChain->SetBranchAddress("RT_HPSbyMediumIsolationMVA2", &RT_HPSbyMediumIsolationMVA2);
    fChain->SetBranchAddress("RT_HPSbyTightCombinedIsolationDeltaBetaCorr", &RT_HPSbyTightCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("RT_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits", &RT_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("RT_HPSbyTightIsolationMVA", &RT_HPSbyTightIsolationMVA);
    fChain->SetBranchAddress("RT_HPSbyTightIsolationMVA2", &RT_HPSbyTightIsolationMVA2);
    fChain->SetBranchAddress("RT_HPSbyVLooseCombinedIsolationDeltaBetaCorr", &RT_HPSbyVLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("RT_HPSdecayModeFinding", &RT_HPSdecayModeFinding);
    fChain->SetBranchAddress("RT_IsInTheCracks", &RT_IsInTheCracks);
    fChain->SetBranchAddress("RT_JetCSV", &RT_JetCSV);
    fChain->SetBranchAddress("RT_LTIpVtdxy", &RT_LTIpVtdxy);
    fChain->SetBranchAddress("RT_LTIpVtdxyError", &RT_LTIpVtdxyError);
    fChain->SetBranchAddress("RT_LTIpVtdz", &RT_LTIpVtdz);
    fChain->SetBranchAddress("RT_LTIpVtdzError", &RT_LTIpVtdzError);
    fChain->SetBranchAddress("RT_LTNormChiSqrd", &RT_LTNormChiSqrd);
    fChain->SetBranchAddress("RT_LTPt", &RT_LTPt);
    fChain->SetBranchAddress("RT_LTValidHits", &RT_LTValidHits);
    fChain->SetBranchAddress("RT_LTvalid", &RT_LTvalid);
    fChain->SetBranchAddress("RT_LTvx", &RT_LTvx);
    fChain->SetBranchAddress("RT_LTvy", &RT_LTvy);
    fChain->SetBranchAddress("RT_LTvz", &RT_LTvz);
    fChain->SetBranchAddress("RT_MomentumRank", &RT_MomentumRank);
    fChain->SetBranchAddress("RT_NProngs", &RT_NProngs);
    fChain->SetBranchAddress("RT_NSignalGammas", &RT_NSignalGammas);
    fChain->SetBranchAddress("RT_NSignalNeutrals", &RT_NSignalNeutrals);
    fChain->SetBranchAddress("RT_P", &RT_P);
    fChain->SetBranchAddress("T1_Charge", &T1_Charge);
    fChain->SetBranchAddress("T1_DecayMode", &T1_DecayMode);
    fChain->SetBranchAddress("T1_EmFraction", &T1_EmFraction);
    fChain->SetBranchAddress("T1_GenMatchDaughter0Id", &T1_GenMatchDaughter0Id);
    fChain->SetBranchAddress("T1_GenMatchDaughter0Status", &T1_GenMatchDaughter0Status);
    fChain->SetBranchAddress("T1_GenMatchDaughter1Id", &T1_GenMatchDaughter1Id);
    fChain->SetBranchAddress("T1_GenMatchDaughter1Status", &T1_GenMatchDaughter1Status);
    fChain->SetBranchAddress("T1_GenMatchGrandmother00Id", &T1_GenMatchGrandmother00Id);
    fChain->SetBranchAddress("T1_GenMatchGrandmother00Status", &T1_GenMatchGrandmother00Status);
    fChain->SetBranchAddress("T1_GenMatchGrandmother01Id", &T1_GenMatchGrandmother01Id);
    fChain->SetBranchAddress("T1_GenMatchGrandmother01Status", &T1_GenMatchGrandmother01Status);
    fChain->SetBranchAddress("T1_GenMatchGrandmother10Id", &T1_GenMatchGrandmother10Id);
    fChain->SetBranchAddress("T1_GenMatchGrandmother10Status", &T1_GenMatchGrandmother10Status);
    fChain->SetBranchAddress("T1_GenMatchGrandmother11Id", &T1_GenMatchGrandmother11Id);
    fChain->SetBranchAddress("T1_GenMatchGrandmother11Status", &T1_GenMatchGrandmother11Status);
    fChain->SetBranchAddress("T1_GenMatchId", &T1_GenMatchId);
    fChain->SetBranchAddress("T1_GenMatchMother0Id", &T1_GenMatchMother0Id);
    fChain->SetBranchAddress("T1_GenMatchMother0Status", &T1_GenMatchMother0Status);
    fChain->SetBranchAddress("T1_GenMatchMother1Id", &T1_GenMatchMother1Id);
    fChain->SetBranchAddress("T1_GenMatchMother1Status", &T1_GenMatchMother1Status);
    fChain->SetBranchAddress("T1_GenMatchStatus", &T1_GenMatchStatus);
    fChain->SetBranchAddress("T1_HPSagainstElectronDeadECAL", &T1_HPSagainstElectronDeadECAL);
    fChain->SetBranchAddress("T1_HPSagainstElectronLoose", &T1_HPSagainstElectronLoose);
    fChain->SetBranchAddress("T1_HPSagainstElectronLooseMVA2", &T1_HPSagainstElectronLooseMVA2);
    fChain->SetBranchAddress("T1_HPSagainstElectronLooseMVA3", &T1_HPSagainstElectronLooseMVA3);
    fChain->SetBranchAddress("T1_HPSagainstElectronMVA", &T1_HPSagainstElectronMVA);
    fChain->SetBranchAddress("T1_HPSagainstElectronMVA2category", &T1_HPSagainstElectronMVA2category);
    fChain->SetBranchAddress("T1_HPSagainstElectronMVA2raw", &T1_HPSagainstElectronMVA2raw);
    fChain->SetBranchAddress("T1_HPSagainstElectronMVA3category", &T1_HPSagainstElectronMVA3category);
    fChain->SetBranchAddress("T1_HPSagainstElectronMVA3raw", &T1_HPSagainstElectronMVA3raw);
    fChain->SetBranchAddress("T1_HPSagainstElectronMedium", &T1_HPSagainstElectronMedium);
    fChain->SetBranchAddress("T1_HPSagainstElectronMediumMVA2", &T1_HPSagainstElectronMediumMVA2);
    fChain->SetBranchAddress("T1_HPSagainstElectronMediumMVA3", &T1_HPSagainstElectronMediumMVA3);
    fChain->SetBranchAddress("T1_HPSagainstElectronTight", &T1_HPSagainstElectronTight);
    fChain->SetBranchAddress("T1_HPSagainstElectronTightMVA2", &T1_HPSagainstElectronTightMVA2);
    fChain->SetBranchAddress("T1_HPSagainstElectronTightMVA3", &T1_HPSagainstElectronTightMVA3);
    fChain->SetBranchAddress("T1_HPSagainstElectronVLooseMVA2", &T1_HPSagainstElectronVLooseMVA2);
    fChain->SetBranchAddress("T1_HPSagainstElectronVTightMVA3", &T1_HPSagainstElectronVTightMVA3);
    fChain->SetBranchAddress("T1_HPSagainstMuonLoose", &T1_HPSagainstMuonLoose);
    fChain->SetBranchAddress("T1_HPSagainstMuonLoose2", &T1_HPSagainstMuonLoose2);
    fChain->SetBranchAddress("T1_HPSagainstMuonMedium", &T1_HPSagainstMuonMedium);
    fChain->SetBranchAddress("T1_HPSagainstMuonMedium2", &T1_HPSagainstMuonMedium2);
    fChain->SetBranchAddress("T1_HPSagainstMuonTight", &T1_HPSagainstMuonTight);
    fChain->SetBranchAddress("T1_HPSagainstMuonTight2", &T1_HPSagainstMuonTight2);
    fChain->SetBranchAddress("T1_HPSbyCombinedIsolationDeltaBetaCorrRaw", &T1_HPSbyCombinedIsolationDeltaBetaCorrRaw);
    fChain->SetBranchAddress("T1_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits", &T1_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits);
    fChain->SetBranchAddress("T1_HPSbyIsolationMVA2raw", &T1_HPSbyIsolationMVA2raw);
    fChain->SetBranchAddress("T1_HPSbyIsolationMVAraw", &T1_HPSbyIsolationMVAraw);
    fChain->SetBranchAddress("T1_HPSbyLooseCombinedIsolationDeltaBetaCorr", &T1_HPSbyLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("T1_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits", &T1_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("T1_HPSbyLooseIsolationMVA", &T1_HPSbyLooseIsolationMVA);
    fChain->SetBranchAddress("T1_HPSbyLooseIsolationMVA2", &T1_HPSbyLooseIsolationMVA2);
    fChain->SetBranchAddress("T1_HPSbyMediumCombinedIsolationDeltaBetaCorr", &T1_HPSbyMediumCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("T1_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits", &T1_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("T1_HPSbyMediumIsolationMVA", &T1_HPSbyMediumIsolationMVA);
    fChain->SetBranchAddress("T1_HPSbyMediumIsolationMVA2", &T1_HPSbyMediumIsolationMVA2);
    fChain->SetBranchAddress("T1_HPSbyTightCombinedIsolationDeltaBetaCorr", &T1_HPSbyTightCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("T1_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits", &T1_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("T1_HPSbyTightIsolationMVA", &T1_HPSbyTightIsolationMVA);
    fChain->SetBranchAddress("T1_HPSbyTightIsolationMVA2", &T1_HPSbyTightIsolationMVA2);
    fChain->SetBranchAddress("T1_HPSbyVLooseCombinedIsolationDeltaBetaCorr", &T1_HPSbyVLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("T1_HPSdecayModeFinding", &T1_HPSdecayModeFinding);
    fChain->SetBranchAddress("T1_IsInTheCracks", &T1_IsInTheCracks);
    fChain->SetBranchAddress("T1_JetCSV", &T1_JetCSV);
    fChain->SetBranchAddress("T1_LTIpVtdxy", &T1_LTIpVtdxy);
    fChain->SetBranchAddress("T1_LTIpVtdxyError", &T1_LTIpVtdxyError);
    fChain->SetBranchAddress("T1_LTIpVtdz", &T1_LTIpVtdz);
    fChain->SetBranchAddress("T1_LTIpVtdzError", &T1_LTIpVtdzError);
    fChain->SetBranchAddress("T1_LTNormChiSqrd", &T1_LTNormChiSqrd);
    fChain->SetBranchAddress("T1_LTPt", &T1_LTPt);
    fChain->SetBranchAddress("T1_LTValidHits", &T1_LTValidHits);
    fChain->SetBranchAddress("T1_LTvalid", &T1_LTvalid);
    fChain->SetBranchAddress("T1_LTvx", &T1_LTvx);
    fChain->SetBranchAddress("T1_LTvy", &T1_LTvy);
    fChain->SetBranchAddress("T1_LTvz", &T1_LTvz);
    fChain->SetBranchAddress("T1_MomentumRank", &T1_MomentumRank);
    fChain->SetBranchAddress("T1_NProngs", &T1_NProngs);
    fChain->SetBranchAddress("T1_NSignalGammas", &T1_NSignalGammas);
    fChain->SetBranchAddress("T1_NSignalNeutrals", &T1_NSignalNeutrals);
    fChain->SetBranchAddress("T1_P", &T1_P);
    fChain->SetBranchAddress("T2_Charge", &T2_Charge);
    fChain->SetBranchAddress("T2_DecayMode", &T2_DecayMode);
    fChain->SetBranchAddress("T2_EmFraction", &T2_EmFraction);
    fChain->SetBranchAddress("T2_GenMatchDaughter0Id", &T2_GenMatchDaughter0Id);
    fChain->SetBranchAddress("T2_GenMatchDaughter0Status", &T2_GenMatchDaughter0Status);
    fChain->SetBranchAddress("T2_GenMatchDaughter1Id", &T2_GenMatchDaughter1Id);
    fChain->SetBranchAddress("T2_GenMatchDaughter1Status", &T2_GenMatchDaughter1Status);
    fChain->SetBranchAddress("T2_GenMatchGrandmother00Id", &T2_GenMatchGrandmother00Id);
    fChain->SetBranchAddress("T2_GenMatchGrandmother00Status", &T2_GenMatchGrandmother00Status);
    fChain->SetBranchAddress("T2_GenMatchGrandmother01Id", &T2_GenMatchGrandmother01Id);
    fChain->SetBranchAddress("T2_GenMatchGrandmother01Status", &T2_GenMatchGrandmother01Status);
    fChain->SetBranchAddress("T2_GenMatchGrandmother10Id", &T2_GenMatchGrandmother10Id);
    fChain->SetBranchAddress("T2_GenMatchGrandmother10Status", &T2_GenMatchGrandmother10Status);
    fChain->SetBranchAddress("T2_GenMatchGrandmother11Id", &T2_GenMatchGrandmother11Id);
    fChain->SetBranchAddress("T2_GenMatchGrandmother11Status", &T2_GenMatchGrandmother11Status);
    fChain->SetBranchAddress("T2_GenMatchId", &T2_GenMatchId);
    fChain->SetBranchAddress("T2_GenMatchMother0Id", &T2_GenMatchMother0Id);
    fChain->SetBranchAddress("T2_GenMatchMother0Status", &T2_GenMatchMother0Status);
    fChain->SetBranchAddress("T2_GenMatchMother1Id", &T2_GenMatchMother1Id);
    fChain->SetBranchAddress("T2_GenMatchMother1Status", &T2_GenMatchMother1Status);
    fChain->SetBranchAddress("T2_GenMatchStatus", &T2_GenMatchStatus);
    fChain->SetBranchAddress("T2_HPSagainstElectronDeadECAL", &T2_HPSagainstElectronDeadECAL);
    fChain->SetBranchAddress("T2_HPSagainstElectronLoose", &T2_HPSagainstElectronLoose);
    fChain->SetBranchAddress("T2_HPSagainstElectronLooseMVA2", &T2_HPSagainstElectronLooseMVA2);
    fChain->SetBranchAddress("T2_HPSagainstElectronLooseMVA3", &T2_HPSagainstElectronLooseMVA3);
    fChain->SetBranchAddress("T2_HPSagainstElectronMVA", &T2_HPSagainstElectronMVA);
    fChain->SetBranchAddress("T2_HPSagainstElectronMVA2category", &T2_HPSagainstElectronMVA2category);
    fChain->SetBranchAddress("T2_HPSagainstElectronMVA2raw", &T2_HPSagainstElectronMVA2raw);
    fChain->SetBranchAddress("T2_HPSagainstElectronMVA3category", &T2_HPSagainstElectronMVA3category);
    fChain->SetBranchAddress("T2_HPSagainstElectronMVA3raw", &T2_HPSagainstElectronMVA3raw);
    fChain->SetBranchAddress("T2_HPSagainstElectronMedium", &T2_HPSagainstElectronMedium);
    fChain->SetBranchAddress("T2_HPSagainstElectronMediumMVA2", &T2_HPSagainstElectronMediumMVA2);
    fChain->SetBranchAddress("T2_HPSagainstElectronMediumMVA3", &T2_HPSagainstElectronMediumMVA3);
    fChain->SetBranchAddress("T2_HPSagainstElectronTight", &T2_HPSagainstElectronTight);
    fChain->SetBranchAddress("T2_HPSagainstElectronTightMVA2", &T2_HPSagainstElectronTightMVA2);
    fChain->SetBranchAddress("T2_HPSagainstElectronTightMVA3", &T2_HPSagainstElectronTightMVA3);
    fChain->SetBranchAddress("T2_HPSagainstElectronVLooseMVA2", &T2_HPSagainstElectronVLooseMVA2);
    fChain->SetBranchAddress("T2_HPSagainstElectronVTightMVA3", &T2_HPSagainstElectronVTightMVA3);
    fChain->SetBranchAddress("T2_HPSagainstMuonLoose", &T2_HPSagainstMuonLoose);
    fChain->SetBranchAddress("T2_HPSagainstMuonLoose2", &T2_HPSagainstMuonLoose2);
    fChain->SetBranchAddress("T2_HPSagainstMuonMedium", &T2_HPSagainstMuonMedium);
    fChain->SetBranchAddress("T2_HPSagainstMuonMedium2", &T2_HPSagainstMuonMedium2);
    fChain->SetBranchAddress("T2_HPSagainstMuonTight", &T2_HPSagainstMuonTight);
    fChain->SetBranchAddress("T2_HPSagainstMuonTight2", &T2_HPSagainstMuonTight2);
    fChain->SetBranchAddress("T2_HPSbyCombinedIsolationDeltaBetaCorrRaw", &T2_HPSbyCombinedIsolationDeltaBetaCorrRaw);
    fChain->SetBranchAddress("T2_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits", &T2_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits);
    fChain->SetBranchAddress("T2_HPSbyIsolationMVA2raw", &T2_HPSbyIsolationMVA2raw);
    fChain->SetBranchAddress("T2_HPSbyIsolationMVAraw", &T2_HPSbyIsolationMVAraw);
    fChain->SetBranchAddress("T2_HPSbyLooseCombinedIsolationDeltaBetaCorr", &T2_HPSbyLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("T2_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits", &T2_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("T2_HPSbyLooseIsolationMVA", &T2_HPSbyLooseIsolationMVA);
    fChain->SetBranchAddress("T2_HPSbyLooseIsolationMVA2", &T2_HPSbyLooseIsolationMVA2);
    fChain->SetBranchAddress("T2_HPSbyMediumCombinedIsolationDeltaBetaCorr", &T2_HPSbyMediumCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("T2_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits", &T2_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("T2_HPSbyMediumIsolationMVA", &T2_HPSbyMediumIsolationMVA);
    fChain->SetBranchAddress("T2_HPSbyMediumIsolationMVA2", &T2_HPSbyMediumIsolationMVA2);
    fChain->SetBranchAddress("T2_HPSbyTightCombinedIsolationDeltaBetaCorr", &T2_HPSbyTightCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("T2_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits", &T2_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits);
    fChain->SetBranchAddress("T2_HPSbyTightIsolationMVA", &T2_HPSbyTightIsolationMVA);
    fChain->SetBranchAddress("T2_HPSbyTightIsolationMVA2", &T2_HPSbyTightIsolationMVA2);
    fChain->SetBranchAddress("T2_HPSbyVLooseCombinedIsolationDeltaBetaCorr", &T2_HPSbyVLooseCombinedIsolationDeltaBetaCorr);
    fChain->SetBranchAddress("T2_HPSdecayModeFinding", &T2_HPSdecayModeFinding);
    fChain->SetBranchAddress("T2_IsInTheCracks", &T2_IsInTheCracks);
    fChain->SetBranchAddress("T2_JetCSV", &T2_JetCSV);
    fChain->SetBranchAddress("T2_LTIpVtdxy", &T2_LTIpVtdxy);
    fChain->SetBranchAddress("T2_LTIpVtdxyError", &T2_LTIpVtdxyError);
    fChain->SetBranchAddress("T2_LTIpVtdz", &T2_LTIpVtdz);
    fChain->SetBranchAddress("T2_LTIpVtdzError", &T2_LTIpVtdzError);
    fChain->SetBranchAddress("T2_LTNormChiSqrd", &T2_LTNormChiSqrd);
    fChain->SetBranchAddress("T2_LTPt", &T2_LTPt);
    fChain->SetBranchAddress("T2_LTValidHits", &T2_LTValidHits);
    fChain->SetBranchAddress("T2_LTvalid", &T2_LTvalid);
    fChain->SetBranchAddress("T2_LTvx", &T2_LTvx);
    fChain->SetBranchAddress("T2_LTvy", &T2_LTvy);
    fChain->SetBranchAddress("T2_LTvz", &T2_LTvz);
    fChain->SetBranchAddress("T2_MomentumRank", &T2_MomentumRank);
    fChain->SetBranchAddress("T2_NProngs", &T2_NProngs);
    fChain->SetBranchAddress("T2_NSignalGammas", &T2_NSignalGammas);
    fChain->SetBranchAddress("T2_NSignalNeutrals", &T2_NSignalNeutrals);
    fChain->SetBranchAddress("T2_P", &T2_P);
    // >>> End address <<<
}
